//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

__attribute__((visibility("hidden")))
@interface _TtC8WhatsAppP33_4370247F64A6F4EA80E052DEEDC570CA13MediaUploader : SwiftObject
{
    // Error parsing type: , name: internalQueue
    // Error parsing type: , name: externalQueue
    // Error parsing type: , name: spaceAvailable
    // Error parsing type: , name: terminalError
    // Error parsing type: , name: inFlightBytesWindow
    // Error parsing type: , name: inFlightBytes
    // Error parsing type: , name: inFlightOperations
    // Error parsing type: , name: inFlightGroup
    // Error parsing type: , name: database
}

@end

