//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSLayoutConstraint, UILabel;

__attribute__((visibility("hidden")))
@interface _WACountryTableViewCell : UITableViewCell
{
    NSLayoutConstraint *_countryCodeTrailingToSuperview;
    UILabel *_countryNameLabel;
    UILabel *_countryCodeLabel;
}

@property(readonly, nonatomic) UILabel *countryCodeLabel; // @synthesize countryCodeLabel=_countryCodeLabel;
@property(readonly, nonatomic) UILabel *countryNameLabel; // @synthesize countryNameLabel=_countryNameLabel;
- (void).cxx_destruct;
- (void)setAccessoryType:(long long)arg1;
- (void)addAutoLayoutConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

