//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

__attribute__((visibility("hidden")))
@interface _WAExpiredLiveLocationFooterView : UIView
{
    UILabel *_infoLabel;
    UILabel *_lastUpdatedLabel;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithLastUpdatedDate:(id)arg1;

@end

