//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WAStaticTableViewController.h>

__attribute__((visibility("hidden")))
@interface EditQuickReplyViewController : WAStaticTableViewController
{
    // Error parsing type: , name: maxNumKeywords
    // Error parsing type: , name: keywordSectionIndex
    // Error parsing type: , name: quickReply
    // Error parsing type: , name: editMode
    // Error parsing type: , name: messageCell
    // Error parsing type: , name: shortcutCell
    // Error parsing type: , name: addKeywordCell
    // Error parsing type: , name: addKeywordRow
    // Error parsing type: , name: numKeywordRowsAdded
    // Error parsing type: , name: keywordsChanged
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (void)saveActionWithSender:(id)arg1;
- (void)cancelActionWithSender:(id)arg1;
- (void)addKeywordActionWithSender:(id)arg1;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

