//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

__attribute__((visibility("hidden")))
@interface ProductImagesViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    // Error parsing type: , name: productDescriptor
    // Error parsing type: , name: reuseIdentifier
    // Error parsing type: , name: flowLayout
    // Error parsing type: , name: scrollToIndex
    // Error parsing type: , name: lastScrollToIndex
    // Error parsing type: , name: donatedImages
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)finishTransitionWithContext:(id)arg1;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (_Bool)shouldUseImageToImageTransitionForOperation:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

