//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface ProductDescriptionView : UIView
{
    // Error parsing type: , name: productDescriptionViewDelegate
    // Error parsing type: , name: descriptor
    // Error parsing type: , name: nameLabel
    // Error parsing type: , name: detailLabel
    // Error parsing type: , name: urlLabel
    // Error parsing type: , name: skuLabel
    // Error parsing type: , name: visitButton
    // Error parsing type: , name: chatButton
    // Error parsing type: , name: menuButton
    // Error parsing type: , name: buttonHeight
    // Error parsing type: , name: visitButtonFontMinder
}

- (CDUnknownBlockType).cxx_destruct;
- (void)menu:(id)arg1;
- (void)chat:(id)arg1;
- (void)visit:(id)arg1;
- (void)openURL:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

