//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

__attribute__((visibility("hidden")))
@interface ReportProductViewController : UIViewController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: reuseIdentifier
    // Error parsing type: , name: productIdentifier
}

- (CDUnknownBlockType).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)submit:(id)arg1;
- (void)cancel:(id)arg1;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

