//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString, WABatchDispatcher, WACallLoggerAggregateEventMutableArray;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WACallLogger : NSObject
{
    NSMutableArray *_allEvents;
    WACallLoggerAggregateEventMutableArray *_aggregateEvents;
    NSObject<OS_dispatch_queue> *_saveQueue;
    _Bool _dirty;
    WABatchDispatcher *_syncDidFinishNotificationDispatcher;
}

+ (id)sharedLogger;
- (void).cxx_destruct;
- (void)logRankingDataForCallEvent:(id)arg1;
- (void)synchronize;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (id)aggregateEventsForTextSearchQuery:(id)arg1 numberSearchQuery:(id)arg2;
- (void)reloadAllContactNames;
- (void)syncManagerDidFinishSync:(id)arg1;
@property(readonly, nonatomic) NSArray *missedCallOnlyAggregateEvents;
@property(readonly, nonatomic) NSArray *indexPathsOfUnmissedCallAggregateEvents;
@property(readonly, nonatomic) NSArray *aggregateEvents;
- (void)clearAllCallEvents;
- (void)removeAggregateCallEvent:(id)arg1;
- (void)addCallEvent:(id)arg1;
- (void)insertAggregateEvent:(id)arg1;
- (void)setMissedCallCount:(long long)arg1;
- (void)clearMissedCallCount;
- (void)incrementMissedCallCount;
@property(readonly, nonatomic) long long missedCallCount;
@property(readonly, nonatomic) long long missedCallCountSinceGoingToBackground;
- (void)rebuildAggregateCallEvents;
@property(readonly, copy) NSString *backupFilePath;
@property(readonly, copy) NSString *filePath;
- (void)dealloc;
- (id)init;

@end

