//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface WACameraHelper : NSObject
{
}

+ (void)requestCameraPermissionWithCompletionHandler:(CDUnknownBlockType)arg1;
+ (void)showCameraAccessReminderScreenForSource:(id)arg1;
+ (void)recoverUnsavedMediaIfNeeded;
+ (id)temporaryMediaPathWithExtension:(id)arg1;
+ (id)cameraMediaDirectory;
+ (id)videoCaptureDeviceWithPreferredPosition:(long long)arg1;
+ (double)rightAnglesForVideoOrientation:(long long)arg1;
+ (void)setUpPersistentAudioActivityIfNeeded;
+ (void)cameraDidEnterBackground:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

