//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WACDSticker, WACaptionBar, WAGIFAssetCollection, WAMultiSendMediaItem;

@protocol WACaptionBarDelegate <NSObject>
- (void)captionBarDidRequestToShowStickerStore:(WACaptionBar *)arg1;
- (void)captionBar:(WACaptionBar *)arg1 didRequestToShowGIFSearchWithPreloadedItems:(WAGIFAssetCollection *)arg2;
- (void)captionBar:(WACaptionBar *)arg1 didRequestSendGIF:(WAMultiSendMediaItem *)arg2;
- (void)captionBar:(WACaptionBar *)arg1 didRequestSendSticker:(WACDSticker *)arg2;
- (double)captionBarContainerHeight:(WACaptionBar *)arg1;
- (void)captionBarDidBeginEditing:(WACaptionBar *)arg1;
- (void)captionBarDidRequestAddMedia:(WACaptionBar *)arg1;
- (void)captionBarDidChangeHeight:(WACaptionBar *)arg1;
- (void)captionBarDidChangeDistanceFromBottom:(WACaptionBar *)arg1;
- (void)captionBarDidChangeText:(WACaptionBar *)arg1;
- (void)captionBarIgnoreWillShowKeyboard:(WACaptionBar *)arg1;
- (void)captionBarDidHideKeyboard:(WACaptionBar *)arg1;
- (void)captionBarWillHideKeyboard:(WACaptionBar *)arg1;
- (void)captionBarDidShowKeyboard:(WACaptionBar *)arg1;
- (void)captionBarWillShowKeyboard:(WACaptionBar *)arg1;
- (_Bool)captionBar:(WACaptionBar *)arg1 canMentionUser:(NSString *)arg2;
- (void)captionBarDidStopEditingMention:(WACaptionBar *)arg1;
- (void)captionBar:(WACaptionBar *)arg1 didEditMention:(NSString *)arg2 inRange:(struct _NSRange)arg3;
- (_Bool)captionBarShouldTrackMentions:(WACaptionBar *)arg1;
- (_Bool)canCaptionBarAddMedia:(WACaptionBar *)arg1;
- (void)captionBarDidRequestSendMessage:(WACaptionBar *)arg1;
- (void)captionBarDidFinishEditing:(WACaptionBar *)arg1;
@end

