//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WAChatStorage.h>

@interface WAChatStorage (VCards)
- (_Bool)indexVCardMentionsForMessages:(id)arg1 chatContext:(id)arg2 contactStorage:(id)arg3;
- (id)indexVCardMentionsForMessagesInContext:(id)arg1 startDate:(id)arg2 limit:(unsigned long long)arg3 contactsStorage:(id)arg4;
- (void)fetchVCardsFromKnownContactsForWhatsAppID:(id)arg1 contactsStorage:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)trustedSenderJIDs:(id)arg1 chatContext:(id)arg2 contactStorage:(id)arg3;
@end

