//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WAChatStorage.h>

@interface WAChatStorage (MessageSearch)
- (void)reportSearchEngineFieldStatsWithUnindexedPredicate:(id)arg1 doneIndexing:(_Bool)arg2;
- (void)countMessagesMatchingText:(id)arg1 chatSessionJIDs:(id)arg2 type:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)searchMessagesMatchingText:(id)arg1 chatSessionJIDs:(id)arg2 starredOnly:(_Bool)arg3 type:(long long)arg4 offset:(unsigned long long)arg5 limit:(unsigned long long)arg6 completion:(CDUnknownBlockType)arg7;
- (void)runWithTimeout:(double)arg1 orWhenIndexUpdated:(CDUnknownBlockType)arg2;
- (void)setBalancedShouldIndexRapidly:(_Bool)arg1;
- (void)setShouldIndexRapidly:(_Bool)arg1;
- (void)startIndexingMessages;
@end

