//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WAChatStorage.h>

@class WATask;

@interface WAChatStorage (Tasks)
- (id)removeOrphanedFilesTaskForStore:(id)arg1;
- (id)orphanedFileTaskForStore:(id)arg1;
- (void)addAllExistingFilePathsToStore:(id)arg1;
- (void)searchForOrphanedMediaFilesIfNeededUsingQueue:(id)arg1;
- (id)task_cleanHSMMetadata;
- (id)task_fixSpotlightStatus;
- (id)task_cleanMediaCache;
- (id)task_cleanFirstScanLengthMediaKeyCache;
- (id)task_cleanFirstScanSidecarMediaKeyCache;
- (id)task_fixMediaBrowserStreamingItems;
- (id)task_cleanStreamingMediaKeyCache;
- (id)task_indexVCardsMentions;
- (id)task_deleteMessagesWithoutChatSessions;
- (void)extractWebURLsForChatSessionIfNeeded:(id)arg1 shouldRunAgain:(CDUnknownBlockType)arg2;
- (id)task_extractWebURLs;
- (id)createDeleteMessagesTask;
@property(readonly, nonatomic) WATask *taskDeleteMessages;
- (void)setUpRecurringTasks;
@end

