//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WAViewController.h>

@class NSArray, UILabel, UIView, WACloudBackupManager;
@protocol WACloudReminderViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface WACloudReminderViewController : WAViewController
{
    id <WACloudReminderViewControllerDelegate> _delegate;
    WACloudBackupManager *_manager;
    NSArray *_listNumberLabels;
    UIView *_contentView;
    UILabel *_labelTitle;
    NSArray *_textLabels;
    NSArray *_icons;
    UILabel *_labelText1;
    UILabel *_labelText2;
    UILabel *_labelText3;
    UILabel *_labelText4;
    UIView *_viewWhatsApp;
    UILabel *_labelWhatsApp;
}

+ (id)createFromStoryboard;
@property(nonatomic) __weak UILabel *labelWhatsApp; // @synthesize labelWhatsApp=_labelWhatsApp;
@property(nonatomic) __weak UIView *viewWhatsApp; // @synthesize viewWhatsApp=_viewWhatsApp;
@property(nonatomic) __weak UILabel *labelText4; // @synthesize labelText4=_labelText4;
@property(nonatomic) __weak UILabel *labelText3; // @synthesize labelText3=_labelText3;
@property(nonatomic) __weak UILabel *labelText2; // @synthesize labelText2=_labelText2;
@property(nonatomic) __weak UILabel *labelText1; // @synthesize labelText1=_labelText1;
@property(copy, nonatomic) NSArray *icons; // @synthesize icons=_icons;
@property(copy, nonatomic) NSArray *textLabels; // @synthesize textLabels=_textLabels;
@property(nonatomic) __weak UILabel *labelTitle; // @synthesize labelTitle=_labelTitle;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) NSArray *listNumberLabels; // @synthesize listNumberLabels=_listNumberLabels;
@property(retain, nonatomic) WACloudBackupManager *manager; // @synthesize manager=_manager;
@property(nonatomic) __weak id <WACloudReminderViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)nextAction:(id)arg1;
- (void)addNextButton;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1 andManager:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

