//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface WACloudConstants : NSObject
{
}

+ (id)identifierForFilename:(id)arg1;
+ (id)encryptedPathForPath:(id)arg1;
+ (id)recentForNormalTarFile:(id)arg1;
+ (_Bool)isRecentTarFileOrRelative:(id)arg1;
+ (_Bool)isTarFileOrRelative:(id)arg1;
+ (_Bool)isRecentTarFile:(id)arg1;
+ (_Bool)isTarFile:(id)arg1;
+ (id)filesToExtractLaterForInformation:(id)arg1;
+ (id)filesToExtractForInformation:(id)arg1;
+ (id)filesToDownloadForInformation:(id)arg1;
+ (id)baseFileListForInformation:(id)arg1;
+ (id)baseFileList;
+ (id)fileNamesToEncryptForInformation:(id)arg1;

@end

