//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WATableViewController.h>

#import "UITableViewDelegate-Protocol.h"
#import "WAAddressBookCountryPickerDelegate-Protocol.h"
#import "WAAddressBookLabelPickerDelegate-Protocol.h"
#import "WAAddressBookPropertyPickerDelegate-Protocol.h"
#import "WAContactAddressEditingCellDelegate-Protocol.h"
#import "WAContactEditingHeaderViewDelegate-Protocol.h"
#import "WAContactMultiValueEditingCellDelegate-Protocol.h"

@class NSArray, NSIndexPath, NSString, WAContact, WAContactEditingHeaderView;
@protocol WAContactEditViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAContactEditViewController : WATableViewController <UITableViewDelegate, WAContactEditingHeaderViewDelegate, WAAddressBookLabelPickerDelegate, WAAddressBookCountryPickerDelegate, WAAddressBookPropertyPickerDelegate, WAContactMultiValueEditingCellDelegate, WAContactAddressEditingCellDelegate>
{
    NSArray *_properties;
    long long _addFieldSectionIndex;
    long long _deleteContactSectionIndex;
    NSIndexPath *_indexPathForEditingCell;
    double _labelSectionWidthMain;
    double _labelSectionWidthOthers;
    _Bool _contactModified;
    _Bool _presentedModally;
    id <WAContactEditViewControllerDelegate> _delegate;
    WAContact *_originalContact;
    WAContact *_editingContact;
    WAContactEditingHeaderView *_tableHeader;
}

+ (id)controllerForSavingVCardContact:(id)arg1 intoContact:(id)arg2;
+ (id)controllerForContact:(id)arg1 isModified:(_Bool)arg2;
+ (id)controllerForContact:(id)arg1;
@property(retain, nonatomic) WAContactEditingHeaderView *tableHeader; // @synthesize tableHeader=_tableHeader;
@property(readonly, copy, nonatomic) WAContact *editingContact; // @synthesize editingContact=_editingContact;
@property(readonly, nonatomic) WAContact *originalContact; // @synthesize originalContact=_originalContact;
@property(nonatomic) __weak id <WAContactEditViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)keyboardWillShow:(id)arg1;
- (void)scrollToEditingTableViewCellAnimated:(_Bool)arg1;
- (void)adjustContentInsetForKeyboardHeight:(double)arg1;
- (void)presentActionSheet:(id)arg1;
- (void)contactNoteCellNeedsResize:(id)arg1;
- (void)addressBookCountryPickerDidCancel:(id)arg1;
- (void)addressBookCountryPicker:(id)arg1 didSelectCountryCode:(id)arg2;
- (void)presentCountryPickerForAddressEditingCell:(id)arg1;
- (void)addressBookLabelPickerDidFinish:(id)arg1;
- (void)addressBookLabelPickerDidCancel:(id)arg1;
- (void)handleLabelButtonActionInContactMultiValueEditingCell:(id)arg1;
- (void)contactPropertyEditingCellValueChanged:(id)arg1;
- (_Bool)contactPropertyEditingCellShouldReturn:(id)arg1;
- (void)contactPropertyEditingCellDidEndEditing:(id)arg1;
- (_Bool)contactPropertyEditingCellShouldEndEditing:(id)arg1;
- (void)contactPropertyEditingCellDidBeginEditing:(id)arg1;
- (_Bool)contactPropertyEditingCellShouldBeginEditing:(id)arg1;
- (void)handleCellSelectedForTableView:(id)arg1 atIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)validateChanges;
- (void)doneAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)viewDidLoad;
- (void)contactEditingHeaderValueChanged:(id)arg1;
- (_Bool)contactEditingHeaderViewShouldReturn:(id)arg1;
- (void)addressBookPropertyPickerDidCancel:(id)arg1;
- (void)addressBookPropertyPicker:(id)arg1 didFinishWithProperty:(id)arg2;
- (void)addContactPropertyField;
- (void)reloadHeaderView;
- (void)deleteContact;
- (void)reallyDeleteContact;
- (void)calculateLabelSectionWidth;
- (id)contactPropertyForTableIndexPath:(id)arg1;
- (id)contactPropertyForTableSection:(long long)arg1;
- (id)tableIndexPathForContactProperty:(id)arg1;
- (void)addNewValueToMultiValueProperty:(id)arg1;
- (void)rebuildContactData;
- (void)setContact:(id)arg1;
- (void)dismissAnimated:(_Bool)arg1;
- (void)presentFromViewController:(id)arg1 animated:(_Bool)arg2 modally:(_Bool)arg3;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

