//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface WADeprecation : NSObject
{
}

+ (void)showDeprecatedAlertViewWithMessage:(id)arg1 fromViewController:(id)arg2;
+ (_Bool)presentNagScreenIfNecessaryFromViewController:(id)arg1;
+ (void)updateNagLastShownTime:(id)arg1;
+ (_Bool)shouldShowNagScreen;
+ (_Bool)isDeprecatedPhone;

@end

