//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAGIFBatchToken.h"

__attribute__((visibility("hidden")))
@interface WAGIPHYBatchToken : WAGIFBatchToken
{
    long long _value;
    unsigned long long _batchSize;
}

+ (id)firstBatch;
- (_Bool)isFirstBatch;
- (id)stringValue;
- (id)initWithInteger:(long long)arg1 batchSize:(unsigned long long)arg2;

@end

