//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSIndexPath, NSString, UICollectionView, UICollectionViewLayout, UIColor, UIView;

@protocol WAGimmickPickerViewConfiguring <NSObject, NSCopying>
- (long long)numberOfItemsInPagingCollectionViewSection:(long long)arg1;
- (long long)numberOfSectionsInPagingCollectionView;
- (NSIndexPath *)currentCategory;
- (_Bool)userScrolledToCategory:(NSIndexPath *)arg1;
- (void)registerReuseIdentifersForCollectionView:(UICollectionView *)arg1;
- (void)collectionView:(UICollectionView *)arg1 didLongPressAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)shouldShowRightButtonUpdateIndicator;
- (long long)categorySections;
- (UIView *)currentContentBackgroundViewForCategory:(NSIndexPath *)arg1;
- (UICollectionViewLayout *)contentCollectionViewLayoutForCollectionView:(UICollectionView *)arg1;
- (UICollectionViewLayout *)categoryCollectionViewLayoutForCollectionView:(UICollectionView *)arg1;
- (UIColor *)GIFButtonTintColor;
- (UIColor *)stickerButtonTintColor;
- (NSString *)accessibilityLabelForLeftButton;
- (NSString *)accessibilityLabelForRightButton;
- (_Bool)shouldShowLeftButton;
- (_Bool)shouldShowRightButton;
@end

