//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPictureContainerViewController.h"

#import "UITableViewDelegate-Protocol.h"
#import "WAGroupDescriptionTableViewCellDelegate-Protocol.h"
#import "WAGroupParticipantsControllerContentUpdatesDelegate-Protocol.h"
#import "WAGroupParticipantsControllerDelegate-Protocol.h"
#import "WAGroupSubjectEditControllerDelegate-Protocol.h"
#import "WAParticipantPickerViewControllerDelegate-Protocol.h"
#import "WATextInputViewControllerDelegate-Protocol.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, UIBarButtonItem, WAGroupParticipantsController, WAMediaManager, WATableRow, WATableSection, _WAGroupCreationFooterView, _WAParticipantsSectionHeaderView;

__attribute__((visibility("hidden")))
@interface WAGroupInfoViewController : WAPictureContainerViewController <WAGroupParticipantsControllerContentUpdatesDelegate, WAParticipantPickerViewControllerDelegate, WAGroupDescriptionTableViewCellDelegate, WAGroupParticipantsControllerDelegate, WAGroupSubjectEditControllerDelegate, WATextInputViewControllerDelegate, UITableViewDelegate>
{
    long long _beginUpdatesCount;
    WAMediaManager *_mediaManager;
    UIBarButtonItem *_barButtonShare;
    NSMutableArray *_sections;
    NSArray *_preUpdateSections;
    WATableSection *_sectionGroupSubject;
    WATableRow *_rowGroupSubject;
    _Bool _updatingGroupSubject;
    WATableRow *_rowGroupDescription;
    _Bool _updatingGroupDescription;
    _Bool _canAnimateTableViewChanges;
    WATableSection *_sectionLiveLocation;
    WATableRow *_rowLiveLocation;
    NSArray *_liveLocationSenders;
    _Bool _currentUserIsSharingLocation;
    WATableSection *_sectionMedia;
    WATableRow *_rowMediaLinksDocs;
    WATableRow *_rowStarredMessages;
    WATableRow *_rowChatHistory;
    WATableRow *_rowChatSearch;
    long long _numberOfStarredMessages;
    WATableSection *_sectionSettings;
    WATableRow *_rowMute;
    WATableRow *_rowNotificationTone;
    WATableRow *_rowSaveIncoming;
    WATableRow *_rowEncryptionStatus;
    WATableRow *_rowAdminSettings;
    WATableSection *_sectionParticipants;
    _WAParticipantsSectionHeaderView *_participantsSectionHeaderView;
    WATableRow *_rowAddParticipants;
    WATableRow *_rowGroupInviteLink;
    double _participantsSectionRowHeight;
    WATableSection *_sectionChatActions;
    WATableRow *_rowExportChat;
    WATableRow *_rowClearChat;
    WATableSection *_sectionDestructiveActions;
    _WAGroupCreationFooterView *_groupCreationView;
    WATableRow *_rowExitDeleteGroup;
    _Bool _presentWithGroupDescriptionExpanded;
    _Bool _tableViewSetupInProgress;
    _Bool _chatContainsMessages;
    _Bool _canShowReadonlyGroupWarning;
    struct WAGroupInfoUIStates _uiStates;
    WAGroupParticipantsController *_participantsController;
    NSString *_superAdminJID;
    unsigned long long _numberOfAdmins;
    NSDictionary *_statusV2Messages;
}

@property(copy, nonatomic) NSDictionary *statusV2Messages; // @synthesize statusV2Messages=_statusV2Messages;
@property(nonatomic) _Bool canShowReadonlyGroupWarning; // @synthesize canShowReadonlyGroupWarning=_canShowReadonlyGroupWarning;
@property(nonatomic) unsigned long long numberOfAdmins; // @synthesize numberOfAdmins=_numberOfAdmins;
@property(nonatomic) _Bool chatContainsMessages; // @synthesize chatContainsMessages=_chatContainsMessages;
@property(copy, nonatomic) NSString *superAdminJID; // @synthesize superAdminJID=_superAdminJID;
@property(nonatomic) struct WAGroupInfoUIStates uiStates; // @synthesize uiStates=_uiStates;
@property(nonatomic) _Bool tableViewSetupInProgress; // @synthesize tableViewSetupInProgress=_tableViewSetupInProgress;
@property(retain, nonatomic) WAGroupParticipantsController *participantsController; // @synthesize participantsController=_participantsController;
@property(nonatomic) _Bool presentWithGroupDescriptionExpanded; // @synthesize presentWithGroupDescriptionExpanded=_presentWithGroupDescriptionExpanded;
- (void).cxx_destruct;
- (void)groupDescriptionTableViewCellDidChangeHeight:(id)arg1;
- (void)updateDescriptionCellHeight:(_Bool)arg1;
- (void)contactsStorageDidUpdateContacts:(id)arg1;
- (void)chatStorageDidUpdateChatSessions:(id)arg1;
- (void)transactionDidProcessMessages:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)rowAtIndexPath:(id)arg1;
- (void)setupTableView;
- (_Bool)shouldShowAdminSettings;
- (id)addSection;
- (void)addIcon:(id)arg1 toTableViewCell:(id)arg2;
- (void)participantPickerDidCancel:(id)arg1;
- (void)participantPicker:(id)arg1 didSelectContacts:(id)arg2;
- (void)participantPicker:(id)arg1 didSelectContactWithoutDismiss:(id)arg2;
- (void)addGroupParticipants;
- (void)presentMaxGroupCapacityReachedAlert;
- (void)removeGroupParticipant:(id)arg1 fromViewController:(id)arg2;
- (void)demoteGroupAdmin:(id)arg1;
- (void)promoteGroupParticipant:(id)arg1;
- (void)presentUnknownContactScreenForGroupParticipant:(id)arg1;
- (void)videoCallGroupParticipant:(id)arg1;
- (void)voiceCallGroupParticipant:(id)arg1;
- (void)messageGroupParticipant:(id)arg1;
- (void)viewInfoForGroupParticipant:(id)arg1;
- (void)controller:(id)arg1 didRequestSelectGroupParticipant:(id)arg2 state:(id)arg3;
- (id)controller:(id)arg1 didRequestCellForParticipant:(id)arg2 dequeuedForIndex:(long long)arg3 state:(id)arg4;
- (id)controllerDidRequestPendingAccessoryView:(id)arg1;
- (id)pendingAccessoryView;
@property(readonly, nonatomic, getter=isTableUpdatingContent) _Bool tableUpdatingContent;
- (void)controllerDidChangeContent:(id)arg1;
- (id)controllerDidRequestUpdatedSupplementaryTopRows:(id)arg1;
- (void)controllerDidDeleteObjectsAtIndexes:(id)arg1;
- (void)controllerDidUpdateObjectsAtIndexes:(id)arg1;
- (void)controllerDidInsertObjectsAtIndexes:(id)arg1;
- (void)controllerWillChangeContent:(id)arg1 animated:(_Bool)arg2;
- (void)didChangeContent;
- (void)didDeleteObjectsAtIndexes:(id)arg1 inSection:(id)arg2;
- (void)didUpdateObjectsAtIndexes:(id)arg1 inSection:(id)arg2;
- (void)didInsertObjectsAtIndexes:(id)arg1 inSection:(id)arg2;
- (void)willChangeContentAnimated:(_Bool)arg1;
- (id)indexPathsForRows:(id)arg1 inSection:(id)arg2 beforeUpdates:(_Bool)arg3;
- (void)animateTableViewCellHeightChangesAndPerformBlock:(CDUnknownBlockType)arg1;
- (void)deleteRow:(id)arg1 fromSection:(id)arg2;
- (void)insertRow:(id)arg1 atIndex:(long long)arg2 inSection:(id)arg3;
- (void)deleteSection:(id)arg1;
- (void)insertSection:(id)arg1 belowSection:(id)arg2;
- (void)safeTableViewEndUpdates;
- (void)safeTableViewBeginUpdates;
- (void)handleTapOnParticipantsSectionRowAtIndexPath:(id)arg1;
- (void)handleTapOnParticipant:(id)arg1 state:(id)arg2 inViewController:(id)arg3;
- (_Bool)canRetryAddForState:(id)arg1;
- (id)messageForParticipant:(id)arg1 withErrorState:(id)arg2 shortValue:(_Bool)arg3;
- (id)messageForDemoteParticipantFailure:(id)arg1 withErrorCode:(long long)arg2 shortVersion:(_Bool)arg3;
- (id)messageForPromoteParticipantFailure:(id)arg1 withErrorCode:(long long)arg2 shortVersion:(_Bool)arg3;
- (id)messageForRemoveParticipantFailure:(id)arg1 withErrorCode:(long long)arg2 shortVersion:(_Bool)arg3;
- (id)messageForAddParticipantFailure:(id)arg1 withErrorCode:(long long)arg2 shortVersion:(_Bool)arg3;
- (id)cellForParticipantsSectionRowAtIndexPath:(id)arg1;
- (id)visibleParticipantCellForJID:(id)arg1;
- (_Bool)isIndexPathForParticipantRow:(id)arg1;
- (void)popToNearestChatListViewController;
- (void)reportGroupAndExit:(_Bool)arg1;
- (void)reportGroup;
- (void)textInputControllerDidCancel:(id)arg1;
- (void)textInputController:(id)arg1 didFinishWithText:(id)arg2;
- (void)updateGroupDescriptionToText:(id)arg1;
- (void)updateGroupDescriptionRowAppearance;
- (void)openGroupDescriptionEditor;
- (void)updateGroupSubjectRowAppearance;
- (void)subjectEditViewControllerDidCancel:(id)arg1;
- (void)subjectEditViewController:(id)arg1 didFinishWithText:(id)arg2;
- (void)openGroupSubjectEditor;
- (void)showLockedGroupAlert;
- (id)loadAndCacheStatusV2MessageForJID:(id)arg1;
- (void)reloadStatusV2MessagesForAllParticipants;
- (void)editProfilePicture;
- (void)showOrHideReadonlyGroupWarningAsNeeded;
- (void)updateNavigationBar;
- (void)updateOnParticipantsCountChange;
- (void)updateExitDeleteGroupRowAppearance;
- (void)exitOrDeleteGroup;
- (void)presentExitGroupInternetConnectionAlert;
- (void)updateTableViewSectionsAndCellsAnimated:(_Bool)arg1;
- (void)insertSectionsIfNecessary;
- (void)removeSectionsIfNecessary;
- (void)updateTableViewCellsForOldStates:(struct WAGroupInfoUIStates)arg1;
- (struct WAGroupInfoUIStates)updateUIState;
- (id)formattedGroupCreationInfoString;
- (void)recomputeNumberofAdminsInGroup;
- (void)searchParticipantsAction:(id)arg1;
- (id)presentedParticipantPickerSearchViewController;
- (void)showGroupInviteLinkScreen;
- (void)shareGroupAction:(id)arg1;
- (void)setLiveLocationSectionVisible:(_Bool)arg1;
- (void)locationSharingEndDateChanged:(id)arg1;
- (void)locationSharingParticipantsChanged:(id)arg1;
- (void)viewLocations;
@property(readonly, nonatomic) _Bool showLiveLocation;
- (void)updateLiveLocationIndication;
- (void)updateLiveLocationSendersIfNecessary;
- (void)updateAppearanceOfChatHistoryActionCells;
- (void)clearChat;
- (void)exportChat;
- (void)showAdminSettings;
- (void)showIdentityVerificationScreenForGroupMember:(id)arg1;
- (void)presentMessagesSecuredWithEncryptionAlert;
- (void)promptToChangeSaveIncomingMediaSettings;
- (void)updateSaveIncomingMediaSettingIndication;
- (void)updateNotificationToneIndication;
- (void)promptToSelectCustomNotificationTone;
- (void)updateMuteIndication;
- (void)updateMuteTimeoutWithDate:(id)arg1;
- (void)messageNotificationCenterDidUpdateMuteConfig:(id)arg1;
- (void)promptToMuteOrUnmuteGroup;
- (void)jumpToInChatSearch;
- (void)viewChatHistory;
- (void)updateStarredMessagesCountIndication;
- (void)loadNumberOfStarredMessagesIfNecessary;
- (void)invalidateNumberOfStarredMessages;
- (void)viewStarredMessages;
- (void)updateMediaCountIndication;
- (void)viewAllMedia;
- (void)loadMediaManagedIfNeeded;
@property(readonly, nonatomic, getter=isEditableGroup) _Bool editableGroup;
@property(readonly, nonatomic, getter=isGroupAdmin) _Bool groupAdmin;
@property(readonly, nonatomic, getter=isReadonlyGroup) _Bool readonlyGroup;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)wa_fontSizeDidChange;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithGroupChatSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

