//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

__attribute__((visibility("hidden")))
@interface WAItemViewEvent : NSObject <NSCopying>
{
    _Bool _replied;
    int _unread;
    int _mediaType;
    int _viewCount;
    double _loadTime;
    double _viewTime;
    double _presentationTime;
}

@property(nonatomic) int viewCount; // @synthesize viewCount=_viewCount;
@property(nonatomic) int mediaType; // @synthesize mediaType=_mediaType;
@property(nonatomic) _Bool replied; // @synthesize replied=_replied;
@property(nonatomic) double presentationTime; // @synthesize presentationTime=_presentationTime;
@property(nonatomic) double viewTime; // @synthesize viewTime=_viewTime;
@property(nonatomic) double loadTime; // @synthesize loadTime=_loadTime;
@property(nonatomic) int unread; // @synthesize unread=_unread;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

