//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;
@protocol WALayoutBoundsManagerDelegate;

__attribute__((visibility("hidden")))
@interface WALayoutBoundsManager : NSObject
{
    double _bottomInset;
    id <WALayoutBoundsManagerDelegate> _delegate;
    UIView *_view;
    struct CGRect _bounds;
    struct UIEdgeInsets _margins;
}

+ (id)sharedManager;
@property(nonatomic) struct UIEdgeInsets margins; // @synthesize margins=_margins;
@property(nonatomic) struct CGRect bounds; // @synthesize bounds=_bounds;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
@property(nonatomic) __weak id <WALayoutBoundsManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)chatBarBottomInsetChanged:(id)arg1;
- (struct CGRect)layoutBounds;
- (void)dealloc;
- (id)init;

@end

