//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

#import "WALocationSender-Protocol.h"
#import "WAUnmangedCopyable-Protocol.h"

@class NSData, NSDate, NSNumber, NSString;
@protocol WAServerDate;

__attribute__((visibility("hidden")))
@interface WALocationSender : NSManagedObject <WALocationSender, WAUnmangedCopyable>
{
}

+ (id)fetchRequest;
- (id)unmanagedCopy;

// Remaining properties
@property(copy, nonatomic) NSString *chat; // @dynamic chat;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(copy, nonatomic) NSDate<WAServerDate> *endDate; // @dynamic endDate;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSData *locationMessage; // @dynamic locationMessage;
@property(copy, nonatomic) NSString *messageUniqueKey; // @dynamic messageUniqueKey;
@property(copy, nonatomic) NSString *participant; // @dynamic participant;
@property(copy, nonatomic) NSNumber *sequenceNumber; // @dynamic sequenceNumber;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSDate<WAServerDate> *timestamp; // @dynamic timestamp;

@end

