//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewLayoutAttributes.h>

__attribute__((visibility("hidden")))
@interface WAMediaBrowserLayoutAttributes : UICollectionViewLayoutAttributes
{
    _Bool _pendingDeletion;
    struct CGRect _visibleBounds;
}

@property(nonatomic) struct CGRect visibleBounds; // @synthesize visibleBounds=_visibleBounds;
@property(nonatomic, getter=isPendingDeletion) _Bool pendingDeletion; // @synthesize pendingDeletion=_pendingDeletion;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

