//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMessageContainerSliceView.h"

@class WAMessageEmojiSlice, _WAMessageEmojiView;

__attribute__((visibility("hidden")))
@interface WAMessageEmojiSliceView : WAMessageContainerSliceView
{
    _WAMessageEmojiView *_emojiView;
}

- (void).cxx_destruct;
- (void)reapplyAnimationIfNeeded;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)didMoveToWindow;
- (void)layoutSubviews;
- (void)reloadSliceAfterChange:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, nonatomic) WAMessageEmojiSlice *slice; // @dynamic slice;

@end

