//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WATableViewController.h>

@class WADoneWithSpinnerBarButtonItem;
@protocol WAMediaPickerDataSource;

__attribute__((visibility("hidden")))
@interface WAMediaPickerBaseViewController : WATableViewController
{
    _Bool _showDoneButton;
    id <WAMediaPickerDataSource> _mediaPickerDataSource;
    WADoneWithSpinnerBarButtonItem *_doneButton;
}

@property(readonly, nonatomic) WADoneWithSpinnerBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(nonatomic) _Bool showDoneButton; // @synthesize showDoneButton=_showDoneButton;
@property(nonatomic) __weak id <WAMediaPickerDataSource> mediaPickerDataSource; // @synthesize mediaPickerDataSource=_mediaPickerDataSource;
- (void).cxx_destruct;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (id)toolbarItems;
- (_Bool)scrollEnabled;
- (void)done:(id)arg1;
- (void)updateDoneButton;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)mediaPickerLibraryControllerDidUpdateAssetsGroups:(id)arg1;
- (void)mediaPickerLibraryControllerDidFinishLoadingLibrary:(id)arg1;
- (void)mediaPickerLibraryControllerWillBeginLoadingLibrary:(id)arg1;
- (id)initWithStyle:(long long)arg1;

@end

