//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMessageContainerSlice.h"

__attribute__((visibility("hidden")))
@interface WAMessageMediaSlice : WAMessageContainerSlice
{
    _Bool _hasCaption;
    struct CGSize _aspectRatio;
}

+ (Class)viewClass;
@property(nonatomic) struct CGSize aspectRatio; // @synthesize aspectRatio=_aspectRatio;
- (void)internalFitToWidth:(double)arg1;
- (_Bool)showsMedia;
- (id)initWithMessages:(id)arg1 metrics:(CDStruct_8ee84fd7)arg2;

@end

