//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIToolbar.h>

#import "WAMediaBrowserThumbnailBarDelegate-Protocol.h"

@class NSIndexPath, NSString, UIBarButtonItem, WAMediaBrowserThumbnailBar, WAMediaManager, WAStarBarButtonItem;
@protocol WAMediaBrowserToolbarDelegate;

__attribute__((visibility("hidden")))
@interface WAMediaBrowserToolbar : UIToolbar <WAMediaBrowserThumbnailBarDelegate>
{
    UIBarButtonItem *_trashButton;
    UIBarButtonItem *_actionButton;
    UIBarButtonItem *_pauseButton;
    UIBarButtonItem *_playButton;
    UIBarButtonItem *_flexibleSpaceItem;
    WAStarBarButtonItem *_starButton;
    WAStarBarButtonItem *_unstarButton;
    WAMediaBrowserThumbnailBar *_thumbnailBar;
    struct CGSize _prevSize;
    _Bool _starred;
    long long _playbackState;
}

@property(nonatomic, getter=isStarred) _Bool starred; // @synthesize starred=_starred;
@property(nonatomic) long long playbackState; // @synthesize playbackState=_playbackState;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isScrubbing) _Bool scrubbing;
@property(readonly, nonatomic) double scrollVelocity;
- (void)setHighlightedIndexPath:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) NSIndexPath *highlightedIndexPath;
@property(readonly, nonatomic, getter=isThumbnailBarHidden) _Bool thumbnailBarHidden;
@property(readonly, nonatomic) WAMediaManager *mediaManager;
- (void)mediaBrowserThumbnailBarDidEndScrubbing:(id)arg1;
- (void)mediaBrowserThumbnailBarDidBeginScrubbing:(id)arg1;
- (void)mediaBrowserThumbnailBar:(id)arg1 didScrollToIndexPath:(id)arg2;
- (void)unstarButtonTapped:(id)arg1;
- (void)starButtonTapped:(id)arg1;
- (void)playButtonTapped:(id)arg1;
- (void)pauseButtonTapped:(id)arg1;
- (void)actionButtonTapped:(id)arg1;
- (void)trashButtonTapped:(id)arg1;
- (void)updateItems;
- (void)relayoutButtons;
- (void)layoutSubviews;
- (void)updateConstraints;
- (double)toolbarHeightForLayoutWidth:(double)arg1;
- (double)preferredHeightForLayoutWidth:(double)arg1;
- (id)initWithMediaManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <WAMediaBrowserToolbarDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

