//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WAMMSMediaUploadOperation.h>

#import "WASimpleOperation-Protocol.h"

@class NSString;

@interface WAMMSMediaUploadOperation (WAMediaUploader) <WASimpleOperation>
- (void)start;
- (unsigned long long)priority;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

