//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, WAMediaPickerStats, WAMultiSendMediaPickerController;

@protocol WAMultiSendMediaPickerControllerDelegate <NSObject>
- (void)multiSendMediaPickerControllerDidCancel:(WAMultiSendMediaPickerController *)arg1;
- (void)multiSendMediaPickerController:(WAMultiSendMediaPickerController *)arg1 didSelectItems:(NSArray *)arg2 pickerStatistics:(WAMediaPickerStats *)arg3;

@optional
- (void)multiSendMediaPickerControllerGIFDidFailBecauseOfNetworkError:(void (^)(void))arg1;
@end

