//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAArrayUpdatesIndexSets.h"

__attribute__((visibility("hidden")))
@interface WAMutableArrayUpdatesIndexSets : WAArrayUpdatesIndexSets
{
}

- (void)addIndexesFromSets:(id)arg1;
- (void)removeUpdatedIndexes:(id)arg1;
- (void)addUpdatedIndexes:(id)arg1;
- (void)removeRemovedIndexes:(id)arg1;
- (void)addRemovedIndexes:(id)arg1;
- (void)removeInsertedIndexes:(id)arg1;
- (void)addInsertedIndexes:(id)arg1;

@end

