//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WANotificationWindow;

@protocol WANotificationWindowDelegate <NSObject>
- (void)notificationWindow:(WANotificationWindow *)arg1 userDidSubmitText:(NSString *)arg2;
- (void)notificationWindowDidCancel:(WANotificationWindow *)arg1;
- (void)statusErrorNotificationWindowTapped:(WANotificationWindow *)arg1;
- (void)messageNotificationWindowTapped:(WANotificationWindow *)arg1;
@end

