//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPaymentStorage.h"

__attribute__((visibility("hidden")))
@interface WAPaymentUPIStorage : WAPaymentStorage
{
}

- (void)removeAllUpiHandles;
- (void)removeUpiHandleForJid:(id)arg1 save:(_Bool)arg2;
- (id)addOrUpdateUPIHandleForJid:(id)arg1 withBlock:(CDUnknownBlockType)arg2 save:(_Bool)arg3;
- (id)upiHandleForJid:(id)arg1;

@end

