//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WAStaticTableViewController.h>

#import "WAPaymentCoordinatorDelegate-Protocol.h"
#import "WAPaymentDeclineIncomingCollectLoadingViewControllerType-Protocol.h"
#import "WAPaymentTransactionCellDelegate-Protocol.h"

@class NSString, WAActivityLabel, WAPaymentCoordinator, WATableRow, WATableSection, WAViewControllerConnectionObserver;

__attribute__((visibility("hidden")))
@interface WAPaymentsViewController : WAStaticTableViewController <WAPaymentCoordinatorDelegate, WAPaymentTransactionCellDelegate, WAPaymentDeclineIncomingCollectLoadingViewControllerType>
{
    WATableSection *_sectionPendingCollectRequestHistory;
    WATableSection *_sectionPaymentHistory;
    WATableSection *_sectionPaymentAccounts;
    WATableSection *_sectionPaymentActions;
    WATableSection *_sectionSupport;
    WATableSection *_sectionDeveloper;
    WATableRow *_rowQRCode;
    WATableRow *_rowNewPayment;
    WATableRow *_rowAddPaymentAccount;
    WAPaymentCoordinator *_coordinator;
    WAActivityLabel *_titleActivityLabel;
    WAViewControllerConnectionObserver *_connectionObserver;
}

- (void).cxx_destruct;
- (void)paymentCoordinatorDidEndLoading:(id)arg1;
- (_Bool)paymentCoordinatorDidBeginLoading:(id)arg1;
- (void)paymentCoordinatorDidUserCancel:(id)arg1;
- (void)paymentCoordinatorDidFail:(id)arg1 error:(id)arg2;
- (void)paymentCoordinatorDidComplete:(id)arg1 result:(id)arg2;
- (void)processCollectRequestRejectRequest:(id)arg1;
- (void)updateIncomingCollectRequestLoadingState:(_Bool)arg1 forUniqueId:(id)arg2;
- (void)didCancelOrErrorDeclineTransaction:(id)arg1;
- (void)didStartDecliningTransaction:(id)arg1;
- (void)paymentTransactionCell:(id)arg1 didCancelOutgoingCollectRequestTransaction:(id)arg2;
- (void)paymentTransactionCell:(id)arg1 didDeclineIncomingCollectRequestTransaction:(id)arg2;
- (void)paymentTransactionCell:(id)arg1 didAcceptIncomingCollectRequestTransaction:(id)arg2;
- (void)addSupportSection;
- (void)addPaymentActionsSection;
- (void)updateQRCodeRow;
- (void)addPaymentAccount;
- (void)showDetailsForUPIBankAccount:(id)arg1;
- (void)reloadPaymentAccounts;
- (void)showTransactionDetails:(id)arg1;
- (id)transactionRowForTransaction:(id)arg1;
- (void)showPendingCollectRequestHistory;
- (void)reloadPendingCollectRequestHistorySection;
- (void)showTransactionHistory;
- (void)reloadPaymentHistory;
- (void)showSupportPage;
- (void)startPaymentWithConfiguration:(id)arg1;
- (void)sendPayment;
- (void)paymentTransactionDeleted:(id)arg1;
- (void)paymentTransactionUpdated:(id)arg1;
- (void)paymentTransactionAdded:(id)arg1;
- (void)paymentAccountSetUpStateChanged:(id)arg1;
- (void)paymentAccountUpdated:(id)arg1;
- (void)processExternalPaymentConfigurationIfNeeded:(id)arg1;
- (void)resetLoadingIndicatorsInRows;
- (void)startLoadingForRow:(id)arg1;
- (id)addShowMoreActionRowInSection:(id)arg1 title:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)addRow:(id)arg1 toSection:(id)arg2;
- (void)dealloc;
- (void)resetTableView;
- (void)updateNavigationTitle;
- (void)setUpTableView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

