//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "WAPopupActionMenuSupport-Protocol.h"

@class NSArray, NSString, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface WAPaymentUPIBankTableViewCell : UITableViewCell <WAPopupActionMenuSupport>
{
    NSArray *_customConstraints;
    UIView *_bottomSeparator;
    UIView *_labelContainer;
    NSString *_bankIconURLString;
    SEL _secondaryTitleCustomCopySelector;
    NSString *_bankOrAccountID;
    UILabel *_bankNameLabel;
    UILabel *_accountNameLabel;
    UIImageView *_bankLogoImageView;
}

+ (struct UIEdgeInsets)preferredSeparatorInset;
@property(readonly, nonatomic) UIImageView *bankLogoImageView; // @synthesize bankLogoImageView=_bankLogoImageView;
@property(readonly, nonatomic) UILabel *accountNameLabel; // @synthesize accountNameLabel=_accountNameLabel;
@property(readonly, nonatomic) UILabel *bankNameLabel; // @synthesize bankNameLabel=_bankNameLabel;
@property(copy, nonatomic) NSString *bankOrAccountID; // @synthesize bankOrAccountID=_bankOrAccountID;
- (void).cxx_destruct;
- (void)copySecondaryTitleToPasteboard;
- (void)bankAccountDetails_copyUPIID:(id)arg1;
- (void)performAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)shouldShowPopupActionMenu;
- (void)setHighlightedPrimaryTextSubstring:(id)arg1;
- (void)updateCellWithPrimaryTitle:(id)arg1 secondaryTitle:(id)arg2 secondaryTitleCustomCopySelector:(SEL)arg3 bankIconURLString:(id)arg4;
@property(nonatomic) _Bool customBottomSeparatorVisible;
- (void)layoutSubviews;
- (void)setupConstraints;
- (void)prepareForReuse;
- (void)reloadFonts;
- (void)fontSizeDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1 showBankLogoImage:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

