//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAParticipantControllerItem.h"

@class WAGroupMember;

__attribute__((visibility("hidden")))
@interface WAParticipantControllerItemParticipant : WAParticipantControllerItem
{
}

- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithGroupParticipant:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) WAGroupMember *participant; // @dynamic participant;

@end

