//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WAPaymentCurrencySettings : NSObject
{
    // Error parsing type: , name: code
    // Error parsing type: , name: symbol
    // Error parsing type: , name: decimalSeparator
    // Error parsing type: , name: isPrefixSymbol.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic) _Bool isPrefixSymbol;
- (id)initWithCurrencyCode:(id)arg1;
- (id)initWithTransaction:(id)arg1;
@property(nonatomic, readonly) NSString *decimalSeparator; // @synthesize decimalSeparator;
@property(nonatomic, readonly) NSString *symbol; // @synthesize symbol;
@property(nonatomic, readonly) NSString *code; // @synthesize code;

@end

