//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIViewController, WAChatStorage, WAPaymentConfiguration, WAPaymentManager, WAPaymentSettings;
@protocol WAPaymentCoordinatorDelegate, WAViewControllerExtensions;

__attribute__((visibility("hidden")))
@interface WAPaymentCoordinator : NSObject
{
    WAChatStorage *_chatStorage;
    NSString *_flowId;
    WAPaymentManager *_paymentManager;
    WAPaymentSettings *_paymentSettings;
    UIViewController *_currentViewController;
    id <WAPaymentCoordinatorDelegate> _delegate;
    unsigned long long _flow;
    WAPaymentConfiguration *_paymentConfiguration;
    UIViewController<WAViewControllerExtensions> *_rootViewController;
}

@property(readonly, nonatomic) UIViewController<WAViewControllerExtensions> *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(readonly, nonatomic) WAPaymentSettings *paymentSettings; // @synthesize paymentSettings=_paymentSettings;
@property(readonly, nonatomic) WAPaymentManager *paymentManager; // @synthesize paymentManager=_paymentManager;
@property(readonly, nonatomic) NSString *flowId; // @synthesize flowId=_flowId;
@property(retain, nonatomic) UIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(readonly, nonatomic) WAChatStorage *chatStorage; // @synthesize chatStorage=_chatStorage;
@property(retain, nonatomic) WAPaymentConfiguration *paymentConfiguration; // @synthesize paymentConfiguration=_paymentConfiguration;
@property(readonly, nonatomic) unsigned long long flow; // @synthesize flow=_flow;
@property(readonly, nonatomic) __weak id <WAPaymentCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)exitFlowWithCompletion:(CDUnknownBlockType)arg1;
- (void)exitFlowAndReportCompletionWithResult:(id)arg1;
- (void)exitFlowAndReportCompletionWithTransaction:(id)arg1;
- (void)exitFlowAndReportError:(id)arg1;
- (void)exitFlowAndReportUserCancel;
@property(readonly, nonatomic) NSString *flowNameForLogging;
@property(readonly, nonatomic) NSString *flowIdForLogging;
- (void)resetStateBeforeRestarting;
- (void)resetState;
- (void)restartFlow;
- (void)upgradeFlowTo:(unsigned long long)arg1;
- (_Bool)startFlowToHandleURL:(id)arg1 context:(id)arg2;
- (void)startCountrySpecificFlow;
- (_Bool)startPaymentFlowForAccount:(id)arg1 paymentConfiguration:(id)arg2;
- (void)startShortRegistrationFlow;
- (void)startRegistrationFlow;
- (id)initWithPaymentManager:(id)arg1 paymentSettings:(id)arg2 chatStorage:(id)arg3 rootViewController:(id)arg4 delegate:(id)arg5;

@end

