//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPaymentManager.h"

@class WAPaymentUPINameDirectory, WAPaymentUPIPSPConfiguration, WAPaymentUPIStorage, WARepeatingBlockTask;

__attribute__((visibility("hidden")))
@interface WAPaymentUPIManager : WAPaymentManager
{
    WAPaymentUPIPSPConfiguration *_pspConfiguration;
    WARepeatingBlockTask *_taskToSyncHandles;
    WARepeatingBlockTask *_taskToSyncBlockedHandles;
    WAPaymentUPINameDirectory *_paymentUPINameDirectory;
}

+ (void)resetUPITokenAndListKeysState;
+ (void)saveUPIToken:(id)arg1;
+ (id)UPIToken;
+ (void)saveUPIListKeys:(id)arg1;
+ (id)UPIListKeys;
+ (void)saveUPIHandle:(id)arg1;
+ (id)UPIHandle;
+ (_Bool)hasUserDefaultsValueExpiredForDateKey:(id)arg1 expirationInterval:(double)arg2;
+ (void)resetReceivedIntentFromJIDs;
+ (void)resetSentIntentToJIDs;
- (void).cxx_destruct;
- (void)cancelSyncBlockedHandlesTask;
- (void)scheduleSyncBlockedHandlesTask;
- (id)syncBlockedHandlesTask;
- (void)cancelSyncHandlesTask;
- (void)scheduleSyncHandlesTask;
- (id)syncHandlesTask;
- (void)persistBlockedUPIHandlesCache:(id)arg1;
- (void)cacheUnblockedUPIHandleState:(id)arg1;
- (void)cacheBlockedUPIHandleState:(id)arg1;
- (id)cachedBlockedUPIHandles;
- (void)resetUPIPSPConfiguration;
- (void)activatePSPConfiguration:(id)arg1;
@property(readonly, nonatomic) WAPaymentUPIPSPConfiguration *activePSPConfiguration;
- (void)updateToP2PCollectRequestWithId:(id)arg1 status:(long long)arg2;
- (void)updateUPIMpinSetState:(_Bool)arg1 account:(id)arg2;
- (void)updateUPIMpinSetState:(_Bool)arg1 accountId:(id)arg2;
- (void)syncUPIHandlesFromXMPPResponse:(id)arg1;
- (void)removeAllUpiHandles;
- (void)removeUpiHandleForJid:(id)arg1 saveMOC:(_Bool)arg2;
- (id)addOrUpdateUPIHandleFromXMPPResponse:(id)arg1 saveMOC:(_Bool)arg2;
- (id)upiHandleForJid:(id)arg1;
- (id)defaultUPIPaymentAccount;
- (id)upiAccounts;
- (id)upiAccountWithId:(id)arg1;
- (id)upiAccountForAccount:(id)arg1;
- (id)prepareCoordinatorWithViewController:(id)arg1 delegate:(id)arg2;
- (void)cancelBackgroundTasksToSyncDatabase;
- (void)scheduleBackgroundTasksToSyncDatabase;
- (_Bool)hasPaymentAccount;
- (void)fullyResetStateAndResetTOS:(_Bool)arg1;
- (id)preparedPaymentStorage;
@property(readonly, nonatomic) WAPaymentUPIStorage *paymentStorage;
- (id)paymentNameDirectory;
- (id)sendUPIUserSetupNotificationForJID:(id)arg1;
- (id)sendUPIIntentToSendNotificationForJID:(id)arg1;
- (void)sendUPIUserSetupNotifications;
- (void)processIncomingUserSetUpNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)processIncomingIntentToSendNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)registerXMPPNotificationHandler;
- (void)removeReceivedIntentFromJID:(id)arg1;
- (void)storeReceivedIntentFromJID:(id)arg1;
- (id)receivedIntentFromJIDs;
- (void)removeSentIntentToJID:(id)arg1;
- (void)storeSentIntentToJID:(id)arg1;
- (id)sentIntentToJIDs;
- (void)paymentStorageDidCreateDatabase:(id)arg1;
- (void)registerHandlersForPersistentRequestManager:(id)arg1;
- (id)requestUPIUnblockHandle:(id)arg1;
- (id)requestUPISyncHandles;
- (id)requestUPISetMPINForCredentialId:(id)arg1 deviceId:(id)arg2 transactionId:(id)arg3 otp:(id)arg4 mpin:(id)arg5 atmPin:(id)arg6 lastDigits:(id)arg7 expiryMonth:(id)arg8 expiryYear:(id)arg9 defaultDebit:(_Bool)arg10 defaultCredit:(_Bool)arg11 bankCode:(id)arg12 provider:(id)arg13;
- (id)requestUPISendPaymentForHandle:(id)arg1 usingAccount:(id)arg2 amount_1000:(long long)arg3 currency:(id)arg4 deviceId:(id)arg5 encryptedMpin:(id)arg6 clTransactionId:(id)arg7 merchantCode:(id)arg8 refId:(id)arg9 refUrl:(id)arg10 note:(id)arg11 receiverName:(id)arg12;
- (id)requestUPIRegisterHandleForAccountNumber:(id)arg1 bankInfo:(id)arg2 deviceId:(id)arg3 defaultDebit:(_Bool)arg4 defaultCredit:(_Bool)arg5 bankCode:(id)arg6 provider:(id)arg7;
- (id)requestUPIListKeys;
- (id)requestUPIGetVPAName:(id)arg1 deviceId:(id)arg2;
- (id)requestUPIGetTokenForDeviceId:(id)arg1 tokenType:(id)arg2 challenge:(id)arg3 provider:(id)arg4;
- (id)requestUPIGetHandleForJID:(id)arg1 provider:(id)arg2;
- (id)requestUPIGetBlockedHandles;
- (id)requestUPIGetBanksOfVersion:(id)arg1;
- (id)requestUPIGetAccountsForDeviceId:(id)arg1 bankCode:(id)arg2 provider:(id)arg3;
- (id)requestUPIGenerateOTPForDeviceId:(id)arg1 bankInfo:(id)arg2 bankCode:(id)arg3 provider:(id)arg4;
- (id)requestUPICollectRequestSendToAccount:(id)arg1 amount_1000:(long long)arg2 currency:(id)arg3 deviceId:(id)arg4 senderHandle:(id)arg5 clTransactionId:(id)arg6 note:(id)arg7;
- (id)requestUPICollectRequestRejectWithTransactionId:(id)arg1 deviceId:(id)arg2;
- (id)currentUPIRejectRequestForTransactionId:(id)arg1;
- (id)requestUPICollectRequestAcceptUsingAccount:(id)arg1 transactionId:(id)arg2 deviceId:(id)arg3 encryptedMpin:(id)arg4;
- (id)requestUPICheckMPINForCredentialId:(id)arg1 deviceId:(id)arg2 transactionId:(id)arg3 mpin:(id)arg4 receiverJID:(id)arg5 receiverHandle:(id)arg6 senderHandle:(id)arg7 amount:(id)arg8 bankCode:(id)arg9 provider:(id)arg10;
- (id)requestUPIChangeMPINForCredentialId:(id)arg1 deviceId:(id)arg2 transactionId:(id)arg3 oldMpin:(id)arg4 newMpin:(id)arg5 bankCode:(id)arg6 provider:(id)arg7;
- (id)requestUPIBlockHandle:(id)arg1;
- (id)requestUPIBindDeviceWithId:(id)arg1 verificationData:(id)arg2 bankCode:(id)arg3 provider:(id)arg4 smsPhoneNumber:(id)arg5 smsTime:(double)arg6;
- (id)requestUPIBatchOfVersion:(id)arg1;
- (void)accountDidSetup:(id)arg1;
- (void)syncMethodsFromResponse:(id)arg1;
- (void)reallyDeclineIncomingCollectRequest:(id)arg1 fromViewController:(id)arg2;
- (void)declineIncomingCollectRequestForTransaction:(id)arg1 fromViewController:(id)arg2;
- (_Bool)shouldShowLoadingIndicatorForTransaction:(id)arg1;

@end

