//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WANotificationScheduler.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WAPlainNotificationScheduler : WANotificationScheduler
{
    NSMutableDictionary *_postedLocalNotifications;
}

+ (void)storeNotification:(id)arg1;
+ (void)resetCachedNotifications;
- (void).cxx_destruct;
- (void)messageIDsOfDisplayedNotificationsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)cancelAllLocalNotificationsWithIdentifierPrefix:(id)arg1;
- (void)cancelLocalNotificationWithIdentifier:(id)arg1;
- (void)schedule:(id)arg1;
- (id)init;

@end

