//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAAsynchronousBackupOperation.h"

@class NSString, WACloudInteractionOperation, WARestore;

__attribute__((visibility("hidden")))
@interface WAPrepareRestoreOperation : WAAsynchronousBackupOperation
{
    WARestore *_restore;
    NSString *_localRestorePath;
    NSString *_permanentMediaPath;
    NSString *_permanentStickersPath;
    NSString *_userDefaultsPath;
    WACloudInteractionOperation *_download;
}

+ (id)createExtractOperationForName:(id)arg1 fromDownload:(id)arg2 toPath:(id)arg3 containsStickers:(_Bool)arg4;
@property(retain, nonatomic) WACloudInteractionOperation *download; // @synthesize download=_download;
- (void).cxx_destruct;
- (id)createExtractOperationsForFiles:(id)arg1 fromDownload:(id)arg2 toPath:(id)arg3;
- (id)createUnTAROperations;
- (id)createCopyOperation:(id)arg1;
- (id)createDatabaseOperations;
- (id)createDatabaseOperationForPath:(id)arg1;
- (id)createDatabaseDecryptionOperationForPath:(id)arg1;
- (id)createDatabaseCopyOperationForPath:(id)arg1;
- (void)loadUserDefaultsFromDictionary:(id)arg1;
- (void)loadUserDefaults;
- (void)performTaskWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithRestore:(id)arg1;
- (id)initWithDependenciesRequired:(_Bool)arg1;

@end

