//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPictureContainerViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@protocol WAProductCatalogViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAProductCatalogViewController : WAPictureContainerViewController <UITableViewDataSource, UITableViewDelegate>
{
    // Error parsing type: , name: productCatalog
    // Error parsing type: , name: header
    // Error parsing type: , name: activityIndicator
    // Error parsing type: , name: constraintSwitcher
    // Error parsing type: , name: storeName
    // Error parsing type: , name: delegate
    // Error parsing type: , name: haveAddedProfilePictureViewConstraint
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithChatSession:(id)arg1 forJID:(id)arg2;
- (void)productCatalog:(id)arg1 didFailToFetchProductsWithError:(id)arg2;
- (void)productCatalog:(id)arg1 didFetchProductsInRange:(struct _NSRange)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)profilePictureViewSuperviewDidChange;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)updateFramesForPortrait;
- (void)updateFramesForLandscapeWithPictureWidth:(double)arg1 rtlLayout:(_Bool)arg2 size:(struct CGSize)arg3;
@property(nonatomic, readonly) double defaultProfilePictureVisibleHeight;
- (void)traitCollectionDidChange:(id)arg1;
- (void)loadView;
- (id)initWithProductCatalog:(id)arg1 title:(id)arg2 subtitle:(id)arg3 summary:(id)arg4 jid:(id)arg5;
@property(nonatomic) __weak id <WAProductCatalogViewControllerDelegate> delegate; // @synthesize delegate;

@end

