//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WANetworkUsageManager.h>

@class NSURL;

__attribute__((visibility("hidden")))
@interface WAPrimaryNetworkUsageManager : WANetworkUsageManager
{
    NSURL *_fileURL;
}

- (void).cxx_destruct;
- (void)migrateFromUserDefaults:(id)arg1;
- (void)migrateFromDictionary:(id)arg1;
- (_Bool)mergeFromKeyValueStore:(id)arg1;
- (void)internalSave:(id)arg1;
- (id)internalCreate;
- (id)internalLoad;
- (id)initWithSynchronizeInterval:(double)arg1 fileURL:(id)arg2;

@end

