//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/WAViewController.h>

@class UIImage, UIImageView, UIView, WAAutoPlayVideoPlayerView, WACircularProgressView, WAMediaPickerAsset, WAMultiSendMediaItem;

__attribute__((visibility("hidden")))
@interface WAQuickMediaPreviewViewController : WAViewController
{
    _Bool _viewLoaded;
    WACircularProgressView *_progressView;
    UIView *_progressBackgroundView;
    _Bool _selectedItemNeedsUpdate;
    WAMediaPickerAsset *_originalAsset;
    WAMultiSendMediaItem *_selectedItem;
    UIImage *_thumbnailImage;
    id _userInfo;
    UIImageView *_imageView;
    WAAutoPlayVideoPlayerView *_playerView;
}

@property(nonatomic) __weak WAAutoPlayVideoPlayerView *playerView; // @synthesize playerView=_playerView;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;
@property(retain, nonatomic) WAMultiSendMediaItem *selectedItem; // @synthesize selectedItem=_selectedItem;
@property(retain, nonatomic) WAMediaPickerAsset *originalAsset; // @synthesize originalAsset=_originalAsset;
- (void).cxx_destruct;
- (void)multiSendMediaItemDidUpdateContent:(id)arg1;
- (void)multiSendGIFDidUpdateProgress:(id)arg1;
- (id)wa_previewActionItems;
- (void)viewDidLayoutSubviews;
- (void)updateSelectedItem;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;

@end

