//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSError, NSString, WAMessage, WARegularMediaDownloadManager;

@protocol WARegularMediaDownloadManagerDelegate
- (void)regularMediaDownloader:(WARegularMediaDownloadManager *)arg1 didUpdateProgressOfMessage:(WAMessage *)arg2;
- (void)processPendingAutodownloadsForRegularMediaDownloader:(WARegularMediaDownloadManager *)arg1;
- (void)regularMediaDownloader:(WARegularMediaDownloadManager *)arg1 didFinishDownloadingMediaInMessage:(WAMessage *)arg2 toRelativePath:(NSString *)arg3;
- (void)regularMediaDownloader:(WARegularMediaDownloadManager *)arg1 didFailToDownloadMediaInMessage:(WAMessage *)arg2 presentAlert:(_Bool)arg3 error:(NSError *)arg4;
@end

