//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WARichNotification.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface WARichMessageNotification : WARichNotification
{
    NSDictionary *_userInfo;
}

- (void).cxx_destruct;
- (id)generateAttachments;
- (_Bool)hasImageAttachments;
- (id)summaryArgument;
- (id)userInfo;
- (id)unprocessedBody;
- (id)title;
- (id)preprocessNotificationText:(id)arg1;

@end

