//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSIndexPath, NSString, UITableViewCell, UIView, WASearchController;

@protocol WASearchControllerDelegate <NSObject>
- (void)searchController:(WASearchController *)arg1 willDisplayFooterView:(UIView *)arg2 forSection:(long long)arg3;
- (void)searchController:(WASearchController *)arg1 willDisplayCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (double)searchController:(WASearchController *)arg1 heightForFooterInSection:(long long)arg2;
- (double)searchController:(WASearchController *)arg1 heightForHeaderInSection:(long long)arg2;
- (void)searchController:(WASearchController *)arg1 willDisplayHeaderView:(UIView *)arg2 forSection:(long long)arg3;
- (void)searchController:(WASearchController *)arg1 didEndEditingRowAtIndexPath:(NSIndexPath *)arg2;
- (void)searchController:(WASearchController *)arg1 willBeginEditingRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)searchController:(WASearchController *)arg1 editingStyleForRowAtIndexPath:(NSIndexPath *)arg2;
- (void)searchController:(WASearchController *)arg1 accessoryButtonTappedForRowWithIndexPath:(NSIndexPath *)arg2;
- (void)searchController:(WASearchController *)arg1 didSelectRowAtIndexPath:(NSIndexPath *)arg2;
- (NSString *)searchController:(WASearchController *)arg1 titleForHeaderInSection:(long long)arg2;
- (void)searchController:(WASearchController *)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (_Bool)searchController:(WASearchController *)arg1 canEditRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)numberOfSectionsInSearchController:(WASearchController *)arg1;
- (UITableViewCell *)searchController:(WASearchController *)arg1 cellForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)searchController:(WASearchController *)arg1 numberOfRowsInSection:(long long)arg2;
- (void)searchControllerDidEndSearch:(WASearchController *)arg1;
- (void)searchControllerWillEndSearch:(WASearchController *)arg1;
- (void)searchControllerDidBeginSearch:(WASearchController *)arg1;
- (void)searchControllerWillBeginSearch:(WASearchController *)arg1;
- (void)searchController:(WASearchController *)arg1 updateResultsForSearchString:(NSString *)arg2;

@optional
- (NSArray *)searchController:(WASearchController *)arg1 editActionsForRowAtIndexPath:(NSIndexPath *)arg2;
- (double)searchController:(WASearchController *)arg1 heightForRowAtIndexPath:(NSIndexPath *)arg2;
@end

