//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabaseQueue, WASearchEngine;

__attribute__((visibility("hidden")))
@interface WASearchEngineObjectIndexer : NSObject
{
    WASearchEngine *_searchEngine;
    FMDatabaseQueue *_databaseQueue;
    long long _docIDOffset;
}

- (void).cxx_destruct;
- (_Bool)indexObjects:(id)arg1;
- (long long)internalDocIDFor:(long long)arg1;
- (long long)externalDocIDFor:(long long)arg1;
- (id)initWithSearchEngine:(id)arg1 databaseQueue:(id)arg2 docIDOffset:(long long)arg3;

@end

