//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIActivityIndicatorView, UIImageView;

__attribute__((visibility("hidden")))
@interface WAStickerContentCell : UICollectionViewCell
{
    UIImageView *_imageView;
    UIImageView *_downloadImageView;
    UIActivityIndicatorView *_activityIndicator;
}

@property(nonatomic) __weak UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) __weak UIImageView *downloadImageView; // @synthesize downloadImageView=_downloadImageView;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;

@end

