//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString, WAStatusAdActor, WAStatusAdCreative, WAStatusAdObjective;
@protocol WAServerDate;

__attribute__((visibility("hidden")))
@interface WAStatusAd : NSObject
{
    NSString *_trackingNumber;
    NSDate<WAServerDate> *_expirationDate;
    WAStatusAdActor *_adActor;
    WAStatusAdCreative *_adCreative;
    WAStatusAdObjective *_adObjective;
    long long _viewCount;
}

+ (_Bool)supportsSecureCoding;
+ (id)statusAdFromXMPPStatusAd:(id)arg1;
@property(nonatomic) long long viewCount; // @synthesize viewCount=_viewCount;
@property(retain, nonatomic) WAStatusAdObjective *adObjective; // @synthesize adObjective=_adObjective;
@property(retain, nonatomic) WAStatusAdCreative *adCreative; // @synthesize adCreative=_adCreative;
@property(retain, nonatomic) WAStatusAdActor *adActor; // @synthesize adActor=_adActor;
@property(retain, nonatomic) NSDate<WAServerDate> *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(copy, nonatomic) NSString *trackingNumber; // @synthesize trackingNumber=_trackingNumber;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isReadyToDisplay;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

