//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WANotificationSnippet.h"

@class UILabel, WAStatusThumbnailView;

__attribute__((visibility("hidden")))
@interface WAStatusErrorSnippet : WANotificationSnippet
{
    WAStatusThumbnailView *_statusThumbnail;
    UILabel *_titleLabel;
    UILabel *_descriptionLabel;
}

@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) WAStatusThumbnailView *statusThumbnail; // @synthesize statusThumbnail=_statusThumbnail;
- (void).cxx_destruct;
- (void)resizeToWidth:(double)arg1;
- (void)configureForMessage:(id)arg1;
- (id)initWithMessage:(id)arg1;

@end

