//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WAStreamingMediaLoaderManagerQueue : NSObject
{
    NSMutableArray *_pendingDownloadQueue;
    NSMutableDictionary *_pendingDownloadInfoForKey;
}

- (void).cxx_destruct;
- (id)removeDownloadsWithMode:(unsigned long long)arg1;
- (id)removeDownloadModes:(unsigned long long)arg1 forKey:(id)arg2;
- (id)removeDownloadForKey:(id)arg1;
- (_Bool)containsDownloadWithKey:(id)arg1;
- (_Bool)containsFullDownloadWithKey:(id)arg1;
- (id)queueDownloadWithMessageInfo:(id)arg1 mode:(unsigned long long)arg2;
- (id)dequeNextDownload;
@property(readonly, nonatomic) unsigned long long count;
- (id)init;

@end

