//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, WAStatusItem;

__attribute__((visibility("hidden")))
@interface WAStatusViewerSection : NSObject
{
    _Bool _containsDeleteItems;
    unsigned long long _currentIndex;
    unsigned long long _unreadCount;
    NSArray *_statusItems;
}

@property(copy, nonatomic) NSArray *statusItems; // @synthesize statusItems=_statusItems;
@property(nonatomic) _Bool containsDeleteItems; // @synthesize containsDeleteItems=_containsDeleteItems;
@property(nonatomic) unsigned long long unreadCount; // @synthesize unreadCount=_unreadCount;
@property(nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
- (void).cxx_destruct;
- (void)loadIfNeeded;
- (void)removeDeletedStatusItemsIfNeededMovingToNext:(_Bool)arg1;
- (void)removeDeletedStatusItemsIfNeeded;
@property(readonly, nonatomic) WAStatusItem *nextStatusItem;
@property(readonly, nonatomic) WAStatusItem *currentStatusItem;
- (_Bool)decrementIndex;
- (_Bool)incrementIndex;
@property(readonly, nonatomic) unsigned long long count;
- (_Bool)isReplyEnabled;
- (_Bool)isCurrentSectionActorSelf;
- (_Bool)isCurrentStatusItemUnread;
- (id)initWithUnreadCount:(unsigned long long)arg1;

@end

