//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAStatusMessageItemView.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WAStatusLinkPreviewViewDelegate-Protocol.h"

@class NSString, UIGestureRecognizer, UIView, WAStatusLinkPreviewView, WAStatusTextView;

__attribute__((visibility("hidden")))
@interface WAStatusTextItemView : WAStatusMessageItemView <UIGestureRecognizerDelegate, WAStatusLinkPreviewViewDelegate>
{
    WAStatusTextView *_statusTextView;
    WAStatusLinkPreviewView *_linkPreviewView;
    UIView *_dimmingView;
    unsigned long long _selectedURLIndex;
    _Bool _linkPreviewShown;
    UIGestureRecognizer *_textTapGestureRecognizer;
    UIGestureRecognizer *_dimmingTapGestureRecognizer;
}

- (void).cxx_destruct;
- (void)statusLinkPreviewDidCancelMediaDownload:(id)arg1;
- (void)statusLinkPreviewDidRequestMediaDownload:(id)arg1;
- (void)statusLinkPreviewDidUpdateLink:(id)arg1;
- (void)statusLinkPreviewDidTapClose:(id)arg1;
- (void)statusLinkPreviewDidTapRemoveLink:(id)arg1;
- (void)statusLinkPreviewDidTapRemovePreview:(id)arg1;
- (void)statusLinkPreviewDidtapOpenLink:(id)arg1;
- (struct CGRect)linkTextRect;
- (void)showLinkPreview:(id)arg1;
- (void)hideLinkPreview;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)textTapped:(id)arg1;
- (void)dimmingTapped:(id)arg1;
- (void)checkAndOpenURL:(id)arg1 forMessage:(id)arg2;
- (struct CGSize)maxLinkPreviewSize;
- (void)didUpdateItem;
- (_Bool)isHandlingPanGesture;
- (double)presentationTime;
- (void)prepareForReuse;
- (void)didSetItem;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

