//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UIButton, UILabel, WAPaymentTransaction;
@protocol WATransactionDetailsHeaderViewDelegate;

__attribute__((visibility("hidden")))
@interface WATransactionDetailsHeaderView : UIView
{
    UILabel *_amountLabel;
    UIView *_buttonsContainerView;
    UIButton *_declineButton;
    UIButton *_acceptButton;
    UIActivityIndicatorView *_loadingIndicator;
    double _horizontalMargins;
    double _amountLabelVerticalSpacing;
    double _buttonContainerHeight;
    WAPaymentTransaction *_transaction;
    id <WATransactionDetailsHeaderViewDelegate> _delegate;
}

@property(nonatomic) __weak id <WATransactionDetailsHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)declineButtonTapped:(id)arg1;
- (void)acceptButtonTapped:(id)arg1;
- (void)updateForLoadingState:(_Bool)arg1;
- (void)setUpWithTransaction:(id)arg1;
- (double)preferredHeightForWidth:(double)arg1;
- (void)addConstraints;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

