//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Core/XMPPConnection.h>

@class WAFieldStatsEventChatConnectionAttribution, WAMessageHandler;

__attribute__((visibility("hidden")))
@interface XMPPConnectionMain : XMPPConnection
{
    WAFieldStatsEventChatConnectionAttribution *_chatConnectionAttribution;
}

+ (id)stringFromSpamReportOrigin:(unsigned long long)arg1;
+ (void)registerNotificationHandlerForType:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (void)reallyRegisterHandlersForPersistentRequestManager:(id)arg1;
- (void)processIncomingCustomStanza:(id)arg1;
- (void)delayedReceiptsUpdate;
- (void)processIncomingAck:(id)arg1;
- (void)processIncomingNotification:(id)arg1;
- (void)processIncomingChatState:(id)arg1;
- (void)processIncomingPresence:(id)arg1;
- (void)processIncomingMessageStanza:(id)arg1;
- (void)processIncomingIQ:(id)arg1;
- (void)performOnOfflineComplete;
- (void)performOnStreamOpen;
- (void)sendCallReceiptOrAck:(id)arg1;
- (void)sendCallStanza:(id)arg1;
- (void)endCallStanzaTimeout:(id)arg1;
- (void)startCallStanzaTimeout:(id)arg1;
- (void)sendServerErrorReceiptForMessage:(id)arg1;
- (void)sendRetryReceiptForMessage:(id)arg1 retryCount:(unsigned char)arg2;
- (void)sendReadReceiptsForMessagesIfNeeded:(id)arg1;
- (void)sendPlayedReceiptForMessage:(id)arg1;
- (void)sendAckForMessageStanza:(id)arg1 withErrorCode:(long long)arg2;
- (void)sendDeliveryReceiptsForMessageStanzas:(id)arg1;
- (void)sendDeliveryReceiptsForChatMessages:(id)arg1;
- (void)resendUnsentCallStanzas;
- (void)respondWithNotificationToServerErrorReceiptForMessage:(id)arg1 toParticipant:(id)arg2;
- (void)sendNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)processMessageStatusChangeRequests:(id)arg1;
- (void)cleanDirtyBits:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reportVoipPushDelay:(double)arg1;
- (void)sendGlobalPushConfig:(id)arg1 customSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)resetPresenceStateOnStreamClose;
- (void)updatePresence;
- (void)sendPushName:(id)arg1 webClientRequestID:(id)arg2;
- (void)sendPushName:(id)arg1;
- (void)sendPresenceWithNickname:(id)arg1;
- (void)resetCachedLastSeen;
- (id)lastSeenTimestampForJID:(id)arg1;
- (unsigned long long)latestChatStateForGroupWithJID:(id)arg1 returningParticipantJID:(out id *)arg2;
- (unsigned long long)chatStateForContactWithJID:(id)arg1;
- (void)checkIncomingChatStateForJID:(id)arg1 participantJID:(id)arg2;
- (void)setIncomingChatState:(unsigned long long)arg1 forJID:(id)arg2 participantJID:(id)arg3;
- (void)updateLastSentChatState:(unsigned long long)arg1 forJID:(id)arg2;
- (void)reportChatState:(unsigned long long)arg1 forJID:(id)arg2;
- (void)presenceSubscribeToJIDIfNecessary:(id)arg1;
- (void)resetAllChatStatesAndClearSubscriptions:(_Bool)arg1;
- (void)removeClientDataForJID:(id)arg1;
- (id)addClientDataForJID:(id)arg1;
- (id)clientDataForJID:(id)arg1;
- (_Bool)isOnline:(id)arg1;
- (void)sendChangeAuthPublicKey:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)sendRecoveryToken:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)queryServerPropertiesWithCompletion:(CDUnknownBlockType)arg1;
- (void)requestBroadcastListsWithCompletion:(CDUnknownBlockType)arg1;
- (void)deleteBroadcastListFromServer:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)unsubscribeFromLocationUpdatesFromContactJID:(id)arg1 webClientRequestID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)subscribeToLocationUpdatesFromContactJID:(id)arg1 reportParticipants:(_Bool)arg2 includeMessageInParticipantInfo:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)stopLocationSharingWithContact:(id)arg1 sequenceNumber:(long long)arg2 webClientRequestID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)stopLocationSharingWithContact:(id)arg1 webClientRequestID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)reportLocation:(id)arg1;
- (void)getProfilePictureForJID:(id)arg1 withInviteCode:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)joinGroupUsingInviteCode:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestInfoForGroupWithInviteCode:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)regenerateInviteCodeForGroupWithJID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestInviteCodeForGroupWithJID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestParticipatingGroupsWithRequestType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)deleteGroupWithJID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)leaveGroupWithJID:(id)arg1 webClientRequestID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)requestInfoForGroupWithJID:(id)arg1 requestType:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateAdminsInGroupWithJID:(id)arg1 promoteJIDs:(id)arg2 demoteJIDs:(id)arg3 webClientRequestID:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)addParticipants:(id)arg1 toGroupWithJID:(id)arg2 webClientRequestID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)removeParticipants:(id)arg1 fromGroupWithJID:(id)arg2 webClientRequestID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setAnnouncementOnly:(_Bool)arg1 forGroupWithJID:(id)arg2 webClientRequestID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setLocked:(_Bool)arg1 forGroupWithJID:(id)arg2 webClientRequestID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setDescription:(id)arg1 forGroupWithJID:(id)arg2 descriptionID:(id)arg3 previousID:(id)arg4 webClientRequestID:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)setSubject:(id)arg1 forGroupWithJID:(id)arg2 webClientRequestID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)createGroupWithSubject:(id)arg1 description:(id)arg2 descriptionID:(id)arg3 participantJIDs:(id)arg4 key:(id)arg5 announcementOnly:(_Bool)arg6 locked:(_Bool)arg7 webClientRequestID:(id)arg8 completion:(CDUnknownBlockType)arg9;
- (void)getProfilePictureForJID:(id)arg1 type:(unsigned long long)arg2 identifier:(id)arg3 retryOnNetworkFailure:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)setProfilePictureForJID:(id)arg1 pictureData:(id)arg2 webClientRequestID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)getStatusForJIDs:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setStatus:(id)arg1 fromWebClientRequestID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setPrivacySettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)queryPrivacySettingsWithCompletion:(CDUnknownBlockType)arg1;
- (void)removeTwoFactorAuthenticationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)checkIfUserHasTwoFactorAuthenticationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)setTwoFactorAuthenticationCode:(id)arg1 email:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)changeNumberWithUsername:(id)arg1 notify:(_Bool)arg2 notifyJIDs:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)normalizePhoneNumber:(id)arg1 countryCode:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)deleteAccountWithFeedback:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reportSpamCall:(id)arg1 calleeJID:(id)arg2 callerJID:(id)arg3 creatorJID:(id)arg4 isVideo:(_Bool)arg5 isGroupCall:(_Bool)arg6 durationInMilliseconds:(int)arg7 terminatorJID:(id)arg8 terminationReason:(id)arg9;
- (void)reportSpamJID:(id)arg1 origin:(unsigned long long)arg2 webClientRequestID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)reportSpamMessages:(id)arg1 inChatSession:(id)arg2 origin:(unsigned long long)arg3 webClientRequestID:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)sendBlockedContactsList:(id)arg1 webClientRequestID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getBlockedContactsListWithCompletion:(CDUnknownBlockType)arg1;
- (id)chatConnectionAttribution;
- (void)setConnectionAttribution:(id)arg1;
@property(readonly, nonatomic) WAMessageHandler *incomingMessageHandler;
- (void)unsetBackgroundMaxConnectionAttemptOverrideWithKey:(id)arg1;
- (void)setBackgroundMaxConnectionAttemptOverrideWithKey:(id)arg1;
- (void)requestStatusAdPolicyWithPolicyID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestStatusAdWithPolicyID:(id)arg1 totalAds:(unsigned long long)arg2 limited:(_Bool)arg3 idfa:(id)arg4 fbid:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)requestStatusAdWithPolicyID:(id)arg1 totalAds:(unsigned long long)arg2 limited:(_Bool)arg3 idfa:(id)arg4 completion:(CDUnknownBlockType)arg5;

@end

