//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface XMPPWebClientIQFactory : NSObject
{
}

+ (id)sendNotificationsForMessages:(id)arg1 messageCount:(unsigned long long)arg2 unreadChats:(unsigned long long)arg3 forWebSession:(id)arg4;
+ (id)callQueryResponseWithCode:(long long)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)callOfferQueryResponseWithCode:(long long)arg1 callOffer:(id)arg2 requestID:(id)arg3 forWebSession:(id)arg4;
+ (id)relayCallOffer:(id)arg1 forWebSession:(id)arg2;
+ (id)vnameQueryResponseWithVerifiedNameInfo:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)updateLocationFromSenderJID:(id)arg1 elapsed:(long long)arg2 message:(id)arg3 forWebSession:(id)arg4;
+ (id)locationQueryResponseWithParticipants:(id)arg1 duration:(long long)arg2 requestID:(id)arg3 forWebSession:(id)arg4;
+ (id)statusQueryResponseWithChatStates:(id)arg1 checksum:(id)arg2 requestID:(id)arg3 forWebSession:(id)arg4;
+ (id)updateFrequentChatsForAnyType:(id)arg1 imageType:(id)arg2 videoType:(id)arg3 forWebSession:(id)arg4;
+ (id)urlQueryResponseWithTitle:(id)arg1 description:(id)arg2 canonicalURL:(id)arg3 matchedText:(id)arg4 thumbnail:(id)arg5 requestID:(id)arg6 forWebSession:(id)arg7;
+ (id)updateIdentityWithUserJID:(id)arg1 fingerprint:(id)arg2 forWebSession:(id)arg3;
+ (id)identityQueryResponseWithUserJID:(id)arg1 fingerprint:(id)arg2 requestID:(id)arg3 forWebSession:(id)arg4;
+ (id)messageInfoQueryResponseWithMessage:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)groupQueryResponseWithChatSession:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)previewQueryResponseWithImage:(id)arg1 pictureID:(id)arg2 requestID:(id)arg3 forWebSession:(id)arg4;
+ (id)receiptQueryResponseWithReceipts:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)resumeQueryResponseWithChatStates:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)markAsStarred:(_Bool)arg1 messages:(id)arg2 inChatWithJID:(id)arg3 forWebSession:(id)arg4;
+ (id)changeNumberInChatWithJID:(id)arg1 oldJID:(id)arg2 newJID:(id)arg3 forWebSession:(id)arg4;
+ (id)deleteMessagesInChatWithJID:(id)arg1 ofKind:(id)arg2 beforeDate:(id)arg3 includeStarredMessages:(_Bool)arg4 updatedModifyTag:(id)arg5 forWebSession:(id)arg6;
+ (id)deleteMessages:(id)arg1 inChatWithJID:(id)arg2 updatedModifyTag:(id)arg3 forWebSession:(id)arg4;
+ (id)deleteChatWithJID:(id)arg1 forWebSession:(id)arg2;
+ (id)updatePinnedState:(_Bool)arg1 chatJID:(id)arg2 pinDate:(id)arg3 forWebSession:(id)arg4;
+ (id)updateMuteDate:(id)arg1 chatJID:(id)arg2 forWebSession:(id)arg3;
+ (id)updateArchivedState:(_Bool)arg1 chatJID:(id)arg2 forWebSession:(id)arg3;
+ (id)updateParticipantJIDs:(id)arg1 inBroadcastListWithJID:(id)arg2 forWebSession:(id)arg3;
+ (id)updateContactsWithJIDEntities:(id)arg1 removeMissingJIDs:(_Bool)arg2 forWebSession:(id)arg3;
+ (id)updateWebModifyTag:(id)arg1 chatJID:(id)arg2 forWebSession:(id)arg3;
+ (id)markAsSeenStatusWithMessageID:(id)arg1 forWebSession:(id)arg2;
+ (id)markAsNotSpamChatWithJID:(id)arg1 forWebSession:(id)arg2;
+ (id)markAsRead:(_Bool)arg1 chatJID:(id)arg2 forWebSession:(id)arg3;
+ (id)updateBatteryStateForWebSession:(id)arg1;
+ (id)updateMessageStatusForMessage:(id)arg1 forWebSession:(id)arg2;
+ (id)mediaQueryResponseWithCode:(int)arg1 mediaURL:(id)arg2 mediaKey:(id)arg3 requestID:(id)arg4 forWebSession:(id)arg5;
+ (id)addLastMessages:(id)arg1 isResume:(_Bool)arg2 isLastBatch:(_Bool)arg3 forWebSession:(id)arg4;
+ (id)addUnreadContextWithMessages:(id)arg1 firstUnreadID:(id)arg2 isResume:(_Bool)arg3 isLastBatch:(_Bool)arg4 forWebSession:(id)arg5;
+ (id)addMessages:(id)arg1 isAddingAfter:(_Bool)arg2 isLastBatch:(_Bool)arg3 forWebSession:(id)arg4;
+ (id)addMessage:(id)arg1 isAnUpdate:(_Bool)arg2 invisible:(_Bool)arg3 statusChecksum:(id)arg4 forWebSession:(id)arg5;
+ (id)messageQueryResponseWithType:(id)arg1 messages:(id)arg2 attributes:(id)arg3 metricsType:(id)arg4 requestID:(id)arg5 forWebSession:(id)arg6;
+ (id)statusQueryResponseWithMessages:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)vcardQueryResponseWithMessages:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)starredQueryResponseWithMessages:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)searchQueryResponseWithMessages:(id)arg1 hasMoreResults:(_Bool)arg2 requestID:(id)arg3 forWebSession:(id)arg4;
+ (id)mediaMessageQueryResponseWithMessages:(id)arg1 mediaCount:(unsigned long long)arg2 urlCount:(unsigned long long)arg3 documentCount:(unsigned long long)arg4 requestID:(id)arg5 forWebSession:(id)arg6;
+ (id)mediaMessageQueryResponseWithMessages:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)messageQueryResponseWithMessages:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3;
+ (id)contactsQueryResponseWithJIDEntities:(id)arg1 isDuplicate:(_Bool)arg2 isPreemptive:(_Bool)arg3 requestID:(id)arg4 forWebSession:(id)arg5;
+ (id)chatQueryResponseWithChatStates:(id)arg1 isDuplicate:(_Bool)arg2 isPreemptive:(_Bool)arg3 statusChecksum:(id)arg4 requestID:(id)arg5 forWebSession:(id)arg6;
+ (id)actionQueryResponseWithResultCodes:(id)arg1 replaced:(_Bool)arg2 requestID:(id)arg3 forWebSession:(id)arg4;
+ (id)syncQueryResponseAccepted:(_Bool)arg1 requestID:(id)arg2 forWebReference:(id)arg3;
+ (id)responseWithResultCode:(long long)arg1 requestID:(id)arg2;
+ (id)serverChallenge:(id)arg1 forWebReference:(id)arg2;
+ (id)loginTerminateWithReason:(unsigned long long)arg1;
+ (id)loginRejectWithReason:(unsigned long long)arg1 forWebReference:(id)arg2;
+ (id)loginAcceptWithClientToken:(id)arg1 password:(id)arg2 persistent:(_Bool)arg3 resume:(_Bool)arg4 forWebReference:(id)arg5;

@end

