//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface XMPPProductCatalog : NSObject
{
    // Error parsing type: , name: productDescriptors
    // Error parsing type: , name: cursor
    // Error parsing type: , name: hasNextPage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithProductElements:(id)arg1 hasNextPage:(_Bool)arg2 endCursor:(id)arg3;

@end

