//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface YouTubePlayerView : UIView
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: sourceURL
    // Error parsing type: , name: state
    // Error parsing type: , name: status
    // Error parsing type: , name: duration
    // Error parsing type: , name: currentTime
    // Error parsing type: , name: webView
    // Error parsing type: , name: lastLayoutSize
    // Error parsing type: , name: quality
    // Error parsing type: , name: didRequestPause
    // Error parsing type: , name: isScrubbing
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
@property(nonatomic, readonly) struct UIEdgeInsets safeAreaInsets;
- (id)initWithCoder:(id)arg1;

@end

