//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

__attribute__((visibility("hidden")))
@interface _TtC4CoreP33_B99B44ED18B512287BDE639115CBB25E16ProcessAssertion : SwiftObject
{
    // Error parsing type: , name: name
    // Error parsing type: , name: identifier
    // Error parsing type: , name: expirationHandler
    // Error parsing type: , name: semaphore
}

@end

