//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSTextCheckingResult.h>

__attribute__((visibility("hidden")))
@interface _WAMentionCheckingResult : NSTextCheckingResult
{
    struct _NSRange _wa_range;
}

- (struct _NSRange)range;
- (unsigned long long)resultType;
- (id)initWithRange:(struct _NSRange)arg1 jid:(id)arg2;

@end

