//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableData, WAMediaKey;

__attribute__((visibility("hidden")))
@interface _WAMediaSidecarGenerator : NSObject
{
    WAMediaKey *_mediaKey;
    unsigned long long _sidecarChunkLength;
    _Bool _complete;
    CDStruct_43cfb2c2 _sidecarHmacCtx;
    unsigned long long _sidecarChunkOffset;
    NSMutableData *_sidecarResultBuffer;
    NSMutableData *_sidecarLookbackBuffer;
    NSData *_sidecar;
}

@property(readonly, nonatomic) NSData *sidecar; // @synthesize sidecar=_sidecar;
- (void).cxx_destruct;
- (void)finalize;
- (void)updateWithBytesIn:(const void *)arg1 bytesLength:(unsigned long long)arg2;
@property(readonly, nonatomic) NSData *currentLastChunkHMAC;
- (id)initWithMediaKey:(id)arg1 iv:(id)arg2 sidecarChunkLength:(unsigned long long)arg3;

@end

