//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAContactTableViewCell.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface _WAMyStatusTableViewCell : WAContactTableViewCell
{
    UIButton *_moreButton;
}

@property(readonly, nonatomic) UIButton *moreButton; // @synthesize moreButton=_moreButton;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

