//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFoundation/AVAssetResourceLoadingDataRequest.h>

@interface AVAssetResourceLoadingDataRequest (WAStreamingMediaLoaderTaskManager)
- (id)wa_descriptionWithFileSize:(unsigned int)arg1;
- (long long)wa_requestedEndOffsetWithFileSize:(unsigned int)arg1;
@property(readonly, nonatomic) _Bool wa_requestsAllDataToEndOfResource;
@end

