//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDateComponents.h>

@interface NSDateComponents (Rounding)
+ (id)wa_dateComponentsRoundedToDaysHoursOrMinutes:(double)arg1;
+ (id)wa_dateComponentsRoundedToDays:(double)arg1;
+ (id)wa_dateComponentsRoundedToHours:(double)arg1;
+ (id)wa_dateComponentsRoundedToMinutes:(double)arg1;
@end

