//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSLocale.h>

@interface NSLocale (WhatsAppExtras)
+ (id)wa_nounSeparator;
+ (_Bool)wa_isUsing24HrTimeFormat;
+ (long long)wa_textAlignment;
+ (_Bool)wa_isInterfaceRTL;
+ (id)wa_localeCode;
+ (id)wa_languageVariant;
+ (id)wa_preferredLanguageCodes;
+ (id)wa_keyboardLanguagesAvailable;
+ (id)wa_languageCode;
+ (id)wa_oldStyleFullLanguageCode;
+ (id)wa_fullLanguageCode;
@end

