//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableAttributedString.h>

@interface NSMutableAttributedString (Attachments)
- (void)wa_insertAttachmentsUsingFont:(id)arg1 withControlCharacters:(_Bool)arg2;
- (void)wa_resizeAttachmentsToMatchFont:(id)arg1;
- (void)wa_stripAttachments;
- (void)wa_insertAttachentWithAttachmentNamed:(id)arg1 location:(long long)arg2 font:(id)arg3 addControlCharacters:(_Bool)arg4 insertNameIfNoAttachement:(_Bool)arg5;
@end

