//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface PaymentAccountDecodedMetadata : NSObject
{
    // Error parsing type: , name: encodedData
    // Error parsing type: , name: usedForPayment
    // Error parsing type: , name: accountName
    // Error parsing type: , name: accountNumber
    // Error parsing type: , name: accountRefId
    // Error parsing type: , name: bankCode
    // Error parsing type: , name: bankPhoneNumber
    // Error parsing type: , name: bankRefId
    // Error parsing type: , name: ifsc
    // Error parsing type: , name: mmid
    // Error parsing type: , name: typeValue
    // Error parsing type: , name: atmPinLength
    // Error parsing type: , name: bankInfo
    // Error parsing type: , name: handle
    // Error parsing type: , name: mpinLength
    // Error parsing type: , name: mpinSet
    // Error parsing type: , name: otpLength
    // Error parsing type: , name: pinFormatVersion
    // Error parsing type: , name: provider
}

- (CDUnknownBlockType).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

