//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDecimalNumber, NSLocale, NSString;

__attribute__((visibility("hidden")))
@interface UPIPaymentsSettingsData : NSObject
{
}

- (id)init;
@property(nonatomic, readonly) BOOL amountPrecision;
@property(nonatomic, readonly) NSDecimalNumber *maximumAmount;
@property(nonatomic, readonly) NSDecimalNumber *minimumAmount;
@property(nonatomic, readonly) int defaultPayoutMethodType;
@property(nonatomic, readonly) int defaultPaymentMethodType;
@property(nonatomic, readonly) NSString *currencyDecimalSeprator;
@property(nonatomic, readonly) NSString *currencySymbol;
@property(nonatomic, readonly) NSLocale *localeForCurrency;
@property(nonatomic, readonly) NSString *currencyCode;
@property(nonatomic, readonly) NSString *countryCode;

@end

