//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WATableViewController.h"

#import "WAStatusEditControllerDelegate-Protocol.h"

@class UITableViewCell;
@protocol WAAboutListEditViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAAboutListEditViewController : WATableViewController <WAStatusEditControllerDelegate>
{
    UITableViewCell *_sizingCell;
    id <WAAboutListEditViewControllerDelegate> _delegate;
}

@property(readonly, nonatomic) __weak id <WAAboutListEditViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)statusEditController:(id)arg1 didSaveStatus:(id)arg2;
- (void)statusEditControllerDidCancel:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forAboutText:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)doneAction:(id)arg1;
- (void)deleteAllAction:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

