//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "WASheetSizeProviding-Protocol.h"

@class NSArray, NSLayoutConstraint, NSMutableArray, NSString, UIButton, UIImage, UIPanGestureRecognizer, UISelectionFeedbackGenerator, UIStackView, UIWindow, WACachedCopyMutableArray;

__attribute__((visibility("hidden")))
@interface WAActionSheetController : WAViewController <UIScrollViewDelegate, WASheetSizeProviding>
{
    UIStackView *_stackView;
    WACachedCopyMutableArray *_actions;
    UIWindow *_applicationWindow;
    UIPanGestureRecognizer *_panGesture;
    UIButton *_highlightedButton;
    UISelectionFeedbackGenerator *_selectionFeedbackGenerator;
    NSMutableArray *_buttonContainers;
    NSString *_message;
    UIImage *_image;
    NSLayoutConstraint *_stackViewWidth;
}

+ (id)actionSheetControllerWithTitle:(id)arg1 message:(id)arg2;
+ (id)actionSheetControllerWithTitle:(id)arg1 image:(id)arg2;
+ (id)actionSheetControllerWithTitle:(id)arg1;
@property(retain, nonatomic) NSLayoutConstraint *stackViewWidth; // @synthesize stackViewWidth=_stackViewWidth;
@property(retain, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(copy, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (double)sheetHeight;
@property(readonly, copy, nonatomic) NSArray *actions;
- (void)addAction:(id)arg1;
- (void)configureButtons;
- (id)titleView;
- (id)addNewGroupingView;
- (id)buttonForActionSheetAction:(id)arg1;
- (void)actionButtonTapped:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)handleTapOnBackground:(id)arg1;
- (void)enableScrollIfNeededInScrollView:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)awakeFromNib;
- (void)presentFromViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

