//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAContentStamp.h"

@class WAVectorGraphic;

__attribute__((visibility("hidden")))
@interface WAAnalogClockStamp : WAContentStamp
{
    WAVectorGraphic *_background;
    WAVectorGraphic *_minuteHand;
    WAVectorGraphic *_hourHand;
}

+ (id)hourHandVectorGraphicName;
+ (id)minuteHandVectorGraphicName;
+ (id)backgroundVectorGraphicName;
@property(readonly, nonatomic) WAVectorGraphic *hourHand; // @synthesize hourHand=_hourHand;
@property(readonly, nonatomic) WAVectorGraphic *minuteHand; // @synthesize minuteHand=_minuteHand;
@property(readonly, nonatomic) WAVectorGraphic *background; // @synthesize background=_background;
- (void).cxx_destruct;
- (Class)textureRecipeClass;
- (double)minimumInitialHeight;
- (id)initWithCoder:(id)arg1;
- (struct CGSize)aspectRatio;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)uniqueIdentifier;
- (id)initWithPreviousContentStamp:(id)arg1;

@end

