//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface WAAssetsLibraryManager : NSObject
{
}

+ (void)writeImageAtURL:(id)arg1 fileExtension:(id)arg2 toAssetCollection:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)writeImage:(id)arg1 toAssetCollection:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)writeVideoFromURL:(id)arg1 toAssetCollection:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (id)assetURLWithPHAssetIdentifier:(id)arg1 extension:(id)arg2;
+ (id)assetCollectionForSaving;
+ (id)whatsappAssetCollection;
+ (id)phAssetWithURL:(id)arg1;
+ (void)showUnusableVideoAlertViewFromViewController:(id)arg1;
+ (void)showUnusablePhotoAlertViewFromViewController:(id)arg1;
+ (void)showFailedToSaveMediaAlertViewFromViewController:(id)arg1;
+ (void)showNoPhotoLibraryAccessAlertViewFromViewController:(id)arg1;
+ (id)resizedImageForSending:(id)arg1;
+ (void)saveImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)saveImageInMediaInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)reallySaveMediaAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)saveMediaAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (_Bool)shouldSaveMediaAtPathAsVideo:(id)arg1;
+ (void)processNextSaveTaskInQueue;
+ (void)beginProcessingSaveQueueIfNeeded;
+ (void)enqueueSavingMediaToCameraRollAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)enqueueSavingGIFToCameraRollAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)storePathsOfEnqueuedMediaItems;
+ (void)endDeferringSavingMediaToCameraRoll;
+ (void)beginDeferringSavingMediaToCameraRoll;
+ (void)loadImageForAssetURL:(id)arg1 size:(struct CGSize)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)loadBestEditedImageForAssetURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)creationDateForAssetURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)loadSendableImageAndHighResolutionForAssetURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)loadFullScreenImageForAssetURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)fetchAllAssetsGroupsForMediaTypes:(unsigned long long)arg1 groupType:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)checkPhotosPermissionWithCompletionHandler:(CDUnknownBlockType)arg1;
+ (void)assetsGroupForURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)assetForURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)phAssetWithIdentifier:(id)arg1;
+ (id)assetsFilterForMediaType:(unsigned long long)arg1;
+ (_Bool)isAuthorizationGranted;
+ (id)sharedAssetsLibrary;
+ (void)recoverUnsavedMediaIfNeeded;
+ (id)saveMediaToCameraRollQueue;
+ (void)initialize;

@end

