//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableData, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface WAAssetManagerFetchTask : NSObject
{
    _Bool _allowsCellularAccess;
    NSString *_assetIdentifier;
    NSURL *_url;
    unsigned long long _attemptCount;
    NSMutableData *_receivedData;
}

@property(readonly, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
@property(readonly, nonatomic) _Bool allowsCellularAccess; // @synthesize allowsCellularAccess=_allowsCellularAccess;
@property(readonly, nonatomic) unsigned long long attemptCount; // @synthesize attemptCount=_attemptCount;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) NSString *assetIdentifier; // @synthesize assetIdentifier=_assetIdentifier;
- (void).cxx_destruct;
- (id)initWithAssetIdentifier:(id)arg1 url:(id)arg2 attemptCount:(unsigned long long)arg3 allowsCellularAccess:(_Bool)arg4;

@end

