//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSData, NSDate;

__attribute__((visibility("hidden")))
@interface WAAxolotlSession : NSManagedObject
{
}


// Remaining properties
@property(nonatomic) long long recipientId; // @dynamic recipientId;
@property(copy, nonatomic) NSData *sessionData; // @dynamic sessionData;
@property(retain, nonatomic) NSDate *timestamp; // @dynamic timestamp;
@end

