//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UILabel, UIView, WAAnimatedGearsView;

__attribute__((visibility("hidden")))
@interface WABackupInfoTableCell : UITableViewCell
{
    UIView *_containerView;
    _Bool _containerViewLayoutRequired;
    UILabel *_topLineLabel;
    UILabel *_middleLineLabel;
    UILabel *_bottomLineLabel;
    WAAnimatedGearsView *_gearsView;
    UILabel *_labelHelperText;
}

@property(readonly, nonatomic) UILabel *labelHelperText; // @synthesize labelHelperText=_labelHelperText;
@property(readonly, nonatomic) WAAnimatedGearsView *gearsView; // @synthesize gearsView=_gearsView;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct UIEdgeInsets customLayoutMargins;
@property(readonly, nonatomic) double preferredHeight;
- (_Bool)setForcedLayoutWidth:(double)arg1;
- (void)updateFonts;
- (void)layoutSubviews;
@property(copy, nonatomic) NSString *bottomLineText;
@property(copy, nonatomic) NSString *middleLineText;
@property(copy, nonatomic) NSString *topLineText;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

