//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WABizVerifiedNameInfo : NSObject
{
    NSString *_jid;
    NSString *_localizedName;
    long long _verificationLevel;
    unsigned long long _certificateSerial;
    NSString *_certificateIssuer;
}

@property(readonly, copy, nonatomic) NSString *certificateIssuer; // @synthesize certificateIssuer=_certificateIssuer;
@property(readonly, nonatomic) unsigned long long certificateSerial; // @synthesize certificateSerial=_certificateSerial;
@property(readonly, nonatomic) long long verificationLevel; // @synthesize verificationLevel=_verificationLevel;
@property(readonly, copy, nonatomic) NSString *localizedName; // @synthesize localizedName=_localizedName;
@property(readonly, copy, nonatomic) NSString *jid; // @synthesize jid=_jid;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isEnterprise) _Bool enterprise;
@property(readonly, nonatomic, getter=isSMB) _Bool smb;
- (id)initWithEntry:(id)arg1 language:(id)arg2 locale:(id)arg3;
- (id)initWithJID:(id)arg1 localizedName:(id)arg2 verificationLevel:(long long)arg3 certificateSerial:(unsigned long long)arg4 certificateIssuer:(id)arg5;

@end

