//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WABizInfoTableViewCell.h"

@class NSArray, NSLayoutConstraint, UIView, WABizHoursView;

__attribute__((visibility("hidden")))
@interface WABizHoursTableViewCell : WABizInfoTableViewCell
{
    UIView *_containerView;
    WABizHoursView *_todayView;
    WABizHoursView *_day1View;
    WABizHoursView *_day2View;
    WABizHoursView *_day3View;
    WABizHoursView *_day4View;
    WABizHoursView *_day5View;
    WABizHoursView *_day6View;
    NSArray *_otherDayViews;
    double _labelVerticalSpacing;
    NSLayoutConstraint *_expandableBottomConstraint;
}

+ (_Bool)needsDescriptionTextLabel;
- (void).cxx_destruct;
- (void)updateConstraintsForCurrentExpandedState;
- (_Bool)needsExpandableToggle;
- (void)bizHours_installConstraints;
- (void)setUpAllDays;
- (id)initWithBizHours:(id)arg1;

@end

