//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WACallerInfoTableViewCellDelegate-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, UITableView;
@protocol WACallParticipantsViewDelegate;

__attribute__((visibility("hidden")))
@interface WACallParticipantsView : UIView <UITableViewDataSource, UITableViewDelegate, WACallerInfoTableViewCellDelegate>
{
    UITableView *_tableView;
    NSArray *_currentParticipantsInfo;
    NSMutableDictionary *_currentProfilePictures;
    id <WACallParticipantsViewDelegate> _delegate;
}

@property(nonatomic) __weak id <WACallParticipantsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateProfilePictureInfo:(id)arg1;
- (void)setProfilePicturesInfo:(id)arg1;
- (void)reloadTableViewWithPeerParticipantsInfo:(id)arg1;
- (void)callerInfoTableViewCellPressedOnCancel:(id)arg1;
- (id)imageForJID:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)layoutSubviews;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

