//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WACallVideoOverlayViewDelegate-Protocol.h"

@class UIImage, UIImageView, WACallVideoOverlayView, WACallViewParticipantInfo;
@protocol WACallSingleVideoViewDelegate, WACallSingleVideoViewLayout;

__attribute__((visibility("hidden")))
@interface WACallSingleVideoView : UIView <WACallVideoOverlayViewDelegate>
{
    UIImageView *_backgroundImageView;
    UIView *_blurredView;
    WACallVideoOverlayView *_overlayView;
    struct CGRect _lastAlertBubbleFittingBounds;
    long long _overlayUpdateCount;
    _Bool _hideOverlay;
    _Bool _hideOverlayContainer;
    _Bool _resizing;
    UIView *_videoSubview;
    double _videoSubviewAspectRatio;
    id <WACallSingleVideoViewDelegate> _delegate;
    WACallViewParticipantInfo *_participantInfo;
    id <WACallSingleVideoViewLayout> _layout;
}

@property(nonatomic) _Bool resizing; // @synthesize resizing=_resizing;
@property(nonatomic) _Bool hideOverlayContainer; // @synthesize hideOverlayContainer=_hideOverlayContainer;
@property(nonatomic) _Bool hideOverlay; // @synthesize hideOverlay=_hideOverlay;
@property(retain, nonatomic) id <WACallSingleVideoViewLayout> layout; // @synthesize layout=_layout;
@property(retain, nonatomic) WACallViewParticipantInfo *participantInfo; // @synthesize participantInfo=_participantInfo;
@property(nonatomic) __weak id <WACallSingleVideoViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double videoSubviewAspectRatio; // @synthesize videoSubviewAspectRatio=_videoSubviewAspectRatio;
@property(retain, nonatomic) UIView *videoSubview; // @synthesize videoSubview=_videoSubview;
- (void).cxx_destruct;
- (void)callVideoOverlayPressedActionButton:(id)arg1;
- (void)updateOverlayViewAnimated:(_Bool)arg1;
- (long long)callOverlayMuteSide;
@property(retain, nonatomic) UIImage *profilePictureImage;
- (void)rotateViews:(double)arg1;
- (void)updatedBoundsSize;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

