//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UIVisualEffectView;

__attribute__((visibility("hidden")))
@interface WACardHeaderBlurViewWithShadow : UIView
{
    UIVisualEffectView *_effectView;
    UIImageView *_shadowImageView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)init;

@end

