//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WACacheManager : NSObject
{
    NSString *_directoryFilePath;
    NSString *_pathExtension;
}

+ (void)removeAllItems;
+ (void)removeItemsForChatJID:(id)arg1;
+ (void)removeItemsForMedia:(id)arg1 chatJID:(id)arg2;
+ (id)allCacheManagers;
+ (id)galleryMediaCache;
+ (id)chatMediaCache;
- (void).cxx_destruct;
- (void)internalRemoveAllItems;
- (void)internalRemoveItemsForChatJID:(id)arg1;
- (void)removeItemForMedia:(id)arg1 chatJID:(id)arg2;
- (id)fileURLForLocation:(id)arg1 live:(_Bool)arg2 chatJID:(id)arg3;
- (id)fileURLForMedia:(id)arg1 chatJID:(id)arg2;
- (id)fileURLForName:(id)arg1 chatJID:(id)arg2;
- (id)initWithFileURL:(id)arg1 pathExtension:(id)arg2;

@end

