//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAChatSessionPersistentNotificationView;

@protocol WAChatSessionPersistentNotificationViewDelegate <NSObject>
- (void)chatSessionPersistentNotificationControllerNeedsUpdatedHeight:(WAChatSessionPersistentNotificationView *)arg1;
- (void)chatSessionPersistentNotificationViewWasTapped:(WAChatSessionPersistentNotificationView *)arg1;
- (void)chatSessionPersistentNotificationViewDidDismiss:(WAChatSessionPersistentNotificationView *)arg1;
@end

