//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, WAChatDataStore;

__attribute__((visibility("hidden")))
@interface WAChatDataStoreCoordinator : NSObject
{
    NSMutableDictionary *_dataStoreMap;
    _Bool _areAllDataStoresReady;
    NSArray *_dataStores;
}

@property(nonatomic) _Bool areAllDataStoresReady; // @synthesize areAllDataStoresReady=_areAllDataStoresReady;
@property(readonly, nonatomic) NSArray *dataStores; // @synthesize dataStores=_dataStores;
- (void).cxx_destruct;
- (id)managedObjectWithURIRepresentation:(id)arg1;
- (id)dataStoreOwningManagedObject:(id)arg1;
- (id)executeFetchRequestOnAllDataStores:(id)arg1;
- (void)didChangeDataStoreReadiness;
- (_Bool)internalAreAllDataStoresReady;
- (void)chatDataStoreDidAddStore:(id)arg1;
- (void)chatDataStoreWillDropStore:(id)arg1;
- (void)dealloc;
- (id)initWithChatDataStores:(id)arg1;
- (_Bool)addChildMessagesIfNeededForParentMessage:(id)arg1;
- (void)storeModifiedMessage:(id)arg1 notify:(_Bool)arg2;
- (void)didUpdateMessage:(id)arg1;
- (void)saveAllDataStoresAfterDelay;
- (void)saveAllDataStores;
- (id)dataStoreForChatSessionJID:(id)arg1;
@property(readonly, nonatomic) WAChatDataStore *dataStoreForBlackListItems;
- (id)chatSessionForJID:(id)arg1;
- (id)messagesWithStanzaIDs:(id)arg1 isFromMe:(_Bool)arg2 prefetchedKeyPaths:(id)arg3;
- (id)allPendingMessages;
- (id)messageWithStanzaID:(id)arg1 author:(id)arg2 inChatSessionWithJID:(id)arg3;
- (id)messageWithStanzaID:(id)arg1 isFromMe:(_Bool)arg2 inChatSessionWithJID:(id)arg3;

@end

