//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDate, WAChatDataStore, WAChatSession, WAMessage, WAMessageID;

@protocol WAChatDataStoreDelegate <NSObject>
- (void)chatDataStoreDidDeleteAllChatSessions:(WAChatDataStore *)arg1;
- (void)chatDataStoreDidClearAllChatSessions:(WAChatDataStore *)arg1;
- (void)chatDataStore:(WAChatDataStore *)arg1 didBulkDeleteMessagesInChatSession:(WAChatSession *)arg2 beforeDate:(NSDate *)arg3 ofTypes:(NSArray *)arg4 shouldDeleteStarred:(_Bool)arg5;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldNotifyWebClientOfNumberChangedFromChatSession:(WAChatSession *)arg2 toChatSession:(WAChatSession *)arg3;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldNotifyWebClientOfNameChangeInChatSessions:(NSArray *)arg2;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldNotifyWebClientOfModifyTagUpdateOfChatSession:(WAChatSession *)arg2;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldNotifyWebClientOfStarred:(_Bool)arg2 messages:(NSArray *)arg3 inChatSession:(WAChatSession *)arg4;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldNotifyWebClientOfAllChatSessionsArchived:(_Bool)arg2;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldNotifyWebClientOfUpdatedPinnedStateOfChatSession:(WAChatSession *)arg2;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldNotifyWebClientOfDeletedMessages:(NSArray *)arg2 inChatSession:(WAChatSession *)arg3;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldNotifyWebClientOfClearedChatSession:(WAChatSession *)arg2;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldNotifyWebClientOfDeletedChatSession:(WAChatSession *)arg2;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldMarkStatusAsSeenInWebClient:(WAMessageID *)arg2;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldShowUploadErrorForMessage:(WAMessage *)arg2;
- (void)chatDataStore:(WAChatDataStore *)arg1 shouldForwardAddedMessageToWebClient:(WAMessage *)arg2;
@end

