//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "UITextFieldDelegate-Protocol.h"
#import "WAChangeNumberNotificationControllerDelegate-Protocol.h"
#import "WAPhoneNumberTextFieldDelegate-Protocol.h"

@class NSArray, NSString, UILabel, UITableView, UITextField, UIView, WAChangeNumberNotificationController, WACountryInfo, WAOverlayView, WAPhoneNumberTextField;
@protocol WAChangeNumberInputControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAChangeNumberInputController : WAViewController <UITextFieldDelegate, WAPhoneNumberTextFieldDelegate, WAChangeNumberNotificationControllerDelegate>
{
    WACountryInfo *_selectedCountry1;
    WACountryInfo *_selectedCountry2;
    NSString *_oldPhoneNumber;
    NSString *_newPhoneNumber;
    WAOverlayView *_overlayView;
    _Bool _countryCodeWarningShown;
    double _keyboardHeight;
    NSArray *_notificationContacts;
    WAChangeNumberNotificationController *_changeNumberNotificationController;
    UITableView *_tableViewInput;
    UIView *_viewInput1;
    UIView *_viewInputFieldsContainer1;
    UILabel *_labelPhoneInput1;
    UIView *_viewCCodeContainer1;
    UILabel *_labelPlusSign1;
    UILabel *_labelCCode1;
    UITextField *_textFieldCode1;
    UIView *_viewPhoneNumberContainer1;
    WAPhoneNumberTextField *_textFieldPhone1;
    UIView *_viewInput2;
    UIView *_viewInputFieldsContainer2;
    UILabel *_labelPhoneInput2;
    UIView *_viewCCodeContainer2;
    UILabel *_labelPlusSign2;
    UILabel *_labelCCode2;
    UITextField *_textFieldCode2;
    UIView *_viewPhoneNumberContainer2;
    WAPhoneNumberTextField *_textFieldPhone2;
    id <WAChangeNumberInputControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <WAChangeNumberInputControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WAPhoneNumberTextField *textFieldPhone2; // @synthesize textFieldPhone2=_textFieldPhone2;
@property(retain, nonatomic) UIView *viewPhoneNumberContainer2; // @synthesize viewPhoneNumberContainer2=_viewPhoneNumberContainer2;
@property(retain, nonatomic) UITextField *textFieldCode2; // @synthesize textFieldCode2=_textFieldCode2;
@property(retain, nonatomic) UILabel *labelCCode2; // @synthesize labelCCode2=_labelCCode2;
@property(retain, nonatomic) UILabel *labelPlusSign2; // @synthesize labelPlusSign2=_labelPlusSign2;
@property(retain, nonatomic) UIView *viewCCodeContainer2; // @synthesize viewCCodeContainer2=_viewCCodeContainer2;
@property(retain, nonatomic) UILabel *labelPhoneInput2; // @synthesize labelPhoneInput2=_labelPhoneInput2;
@property(retain, nonatomic) UIView *viewInputFieldsContainer2; // @synthesize viewInputFieldsContainer2=_viewInputFieldsContainer2;
@property(retain, nonatomic) UIView *viewInput2; // @synthesize viewInput2=_viewInput2;
@property(retain, nonatomic) WAPhoneNumberTextField *textFieldPhone1; // @synthesize textFieldPhone1=_textFieldPhone1;
@property(retain, nonatomic) UIView *viewPhoneNumberContainer1; // @synthesize viewPhoneNumberContainer1=_viewPhoneNumberContainer1;
@property(retain, nonatomic) UITextField *textFieldCode1; // @synthesize textFieldCode1=_textFieldCode1;
@property(retain, nonatomic) UILabel *labelCCode1; // @synthesize labelCCode1=_labelCCode1;
@property(retain, nonatomic) UILabel *labelPlusSign1; // @synthesize labelPlusSign1=_labelPlusSign1;
@property(retain, nonatomic) UIView *viewCCodeContainer1; // @synthesize viewCCodeContainer1=_viewCCodeContainer1;
@property(retain, nonatomic) UILabel *labelPhoneInput1; // @synthesize labelPhoneInput1=_labelPhoneInput1;
@property(retain, nonatomic) UIView *viewInputFieldsContainer1; // @synthesize viewInputFieldsContainer1=_viewInputFieldsContainer1;
@property(retain, nonatomic) UIView *viewInput1; // @synthesize viewInput1=_viewInput1;
@property(retain, nonatomic) UITableView *tableViewInput; // @synthesize tableViewInput=_tableViewInput;
- (void).cxx_destruct;
- (void)deviceCheckFailedWithError:(id)arg1;
- (void)deviceCheckFinishedWithResult:(id)arg1;
- (void)phoneNumberTextFieldDidChange:(id)arg1;
- (void)phoneNumberTextFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)changeNumberNotificationControllerDidFinish:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)code2ChangedAction:(id)arg1;
- (void)code1ChangedAction:(id)arg1;
- (void)nextAction:(id)arg1;
- (void)presentChangeNumberNetworkRequiredAlert;
- (void)presentChangeNumberFormatWarningAlert;
- (void)cancelAction:(id)arg1;
- (_Bool)needToShowPhoneNumberFormatWarning;
- (void)saveCurrentUserParametersAndLockVerificationState;
- (void)proceedToAuthCodeRequest;
- (void)proceedToTwoFactorInputWithResponse:(id)arg1;
- (void)showAppStoreAlert:(id)arg1;
- (void)showContactSupportAlert:(id)arg1 withContext:(id)arg2;
- (void)performSameDeviceCheck;
- (void)presentPhoneNumberDoesntMatchAlert;
- (void)presentCouldntConnectToServiceAlert;
- (void)validateOldPhoneNumber;
- (void)resizeInputViews;
- (void)formatCode2Field;
- (void)formatCode1Field;
- (void)validateUserInput;
- (void)showOverlay:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

