//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAChatStorageManagedObject.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface WAChatPushConfig : WAChatStorageManagedObject
{
}


// Remaining properties
@property(nonatomic) short alerts; // @dynamic alerts;
@property(copy, nonatomic) NSString *jid; // @dynamic jid;
@property(retain, nonatomic) NSDate *mutedUntil; // @dynamic mutedUntil;
@property(copy, nonatomic) NSString *ringtone; // @dynamic ringtone;
@property(copy, nonatomic) NSString *sound; // @dynamic sound;
@end

