//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WACloudMediaDownloadRequest.h"

__attribute__((visibility("hidden")))
@interface WACloudImageDownloadRequest : WACloudMediaDownloadRequest
{
}

- (int)internalRequestFullDataWithCompletionHandler:(CDUnknownBlockType)arg1;
- (int)internalRequestResizedImageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)newImageRequestOptions;
- (int)reallyRequestAssetFromPhotosLibraryWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)unload;
- (id)highResolutionImage;

@end

