//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;
@protocol WAServerDate;

__attribute__((visibility("hidden")))
@interface WACompanionCallInfo : NSObject
{
    _Bool _startedByMe;
    int _callState;
    NSString *_callID;
    NSString *_peerJID;
    NSDate<WAServerDate> *_startDate;
}

+ (id)retrieveCallInfo;
+ (void)storeCallInfo:(id)arg1;
+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) int callState; // @synthesize callState=_callState;
@property(readonly, nonatomic) NSDate<WAServerDate> *startDate; // @synthesize startDate=_startDate;
@property(readonly, nonatomic, getter=wasStartedByMe) _Bool startedByMe; // @synthesize startedByMe=_startedByMe;
@property(readonly, nonatomic) NSString *peerJID; // @synthesize peerJID=_peerJID;
@property(readonly, nonatomic) NSString *callID; // @synthesize callID=_callID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithCallID:(id)arg1 peerJID:(id)arg2 startedByMe:(_Bool)arg3 startDate:(id)arg4 callState:(int)arg5;

@end

