//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAContactPropertyCell.h"

#import "WAContactPropertyTextFieldDelegate-Protocol.h"

@class NSString, WAContactPropertyTextField;
@protocol WAContactPropertyEditingCellDelegate;

__attribute__((visibility("hidden")))
@interface WAContactPropertyEditingCell : WAContactPropertyCell <WAContactPropertyTextFieldDelegate>
{
    WAContactPropertyTextField *_textField;
}

@property(retain, nonatomic) WAContactPropertyTextField *textField; // @synthesize textField=_textField;
- (void).cxx_destruct;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (_Bool)isFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (void)contactPropertyTextFieldValueChanged:(id)arg1;
- (_Bool)contactPropertyTextFieldShouldReturn:(id)arg1;
- (void)contactPropertyTextFieldDidEndEditing:(id)arg1;
- (_Bool)contactPropertyTextFieldShouldEndEditing:(id)arg1;
- (void)contactPropertyTextFieldDidBeginEditing:(id)arg1;
- (_Bool)contactPropertyTextFieldShouldBeginEditing:(id)arg1;
- (void)reconfigure;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <WAContactPropertyEditingCellDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

