//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIBlurEffect.h>

@class NSNumber;

__attribute__((visibility("hidden")))
@interface WAConfigurableBlurEffect : UIBlurEffect
{
}

+ (id)effectWithStyle:(long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)effectSettings;
@property(retain, nonatomic) NSNumber *wa_grayscaleTintLevelOverride;
@property(retain, nonatomic) NSNumber *wa_blurRadiusOverride;

@end

