//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WAContactPropertyTextFieldDelegate-Protocol.h"

@class NSMutableArray, NSString, UIFont, WAContact;
@protocol WAContactEditingHeaderViewDelegate;

__attribute__((visibility("hidden")))
@interface WAContactEditingHeaderView : UIView <WAContactPropertyTextFieldDelegate>
{
    unsigned int _nameFormat;
    id <WAContactEditingHeaderViewDelegate> _delegate;
    WAContact *_contact;
    UIFont *_textFieldFont;
    NSMutableArray *_textFields;
}

+ (void)initialize;
@property(nonatomic) unsigned int nameFormat; // @synthesize nameFormat=_nameFormat;
@property(retain, nonatomic) NSMutableArray *textFields; // @synthesize textFields=_textFields;
@property(retain, nonatomic) UIFont *textFieldFont; // @synthesize textFieldFont=_textFieldFont;
@property(retain, nonatomic) WAContact *contact; // @synthesize contact=_contact;
@property(nonatomic) __weak id <WAContactEditingHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (_Bool)isFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (void)contactPropertyTextFieldValueChanged:(id)arg1;
- (_Bool)contactPropertyTextFieldShouldReturn:(id)arg1;
- (id)unusedContactHeaderProperties;
- (id)allContactHeaderProperties;
- (void)reloadContactData;
- (id)addTextFieldForProperty:(id)arg1 withValue:(id)arg2;
- (id)addTextFieldForProperty:(id)arg1 withValue:(id)arg2 sortAndActivate:(_Bool)arg3;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

