//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIView, WAContactProperty;

__attribute__((visibility("hidden")))
@interface WAContactPropertyCell : UITableViewCell
{
    _Bool _isActionButton;
    UIView *_topSeparator;
    UIView *_bottomSeparator;
    id _delegate;
    WAContactProperty *_contactProperty;
}

+ (double)rowHeight;
+ (double)rowHeightForContactProperty:(id)arg1;
+ (id)cellForWAContactProperty:(id)arg1 withReuseIdentifier:(id)arg2;
+ (Class)cellClassForWAContactProperty:(id)arg1;
@property(retain, nonatomic) WAContactProperty *contactProperty; // @synthesize contactProperty=_contactProperty;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)configureAsDeleteContactRow;
- (void)configureAsAddValueRowForContactPropertyType:(long long)arg1;
- (void)reconfigure;
- (void)refreshTextColor;
- (void)tintColorDidChange;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

