//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMediaCopyMessageHelper.h"

__attribute__((visibility("hidden")))
@interface WADocumentMessageHelper : WAMediaCopyMessageHelper
{
}

+ (id)footerAttributedTextWithFont:(id)arg1 forMessage:(id)arg2;
+ (id)stringRepresentationForChatForMessage:(id)arg1;
+ (id)stringComponentsForExportForMessage:(id)arg1 withSenderName:(_Bool)arg2;
+ (id)fullImageFromURL:(id)arg1 ofType:(id)arg2;
+ (struct CGSize)preferredXMPPThumbnailSizeWithSourceImageSize:(struct CGSize)arg1;
+ (_Bool)needsImageLoader;
+ (id)formattedStringWithVoiceOverSummaryForMessage:(id)arg1;
- (id)activityItemSubjectText;
- (_Bool)exportMediaActivityItemToURL:(id)arg1;
- (id)mediaActivityItemPlaceholderWithInternalReference:(_Bool *)arg1;
- (_Bool)requiresNetworkFetchForLargeImageWithInfo:(id)arg1;
- (id)smallImageForMessageImageLoaderWithInfo:(id)arg1;
- (_Bool)shouldCacheLargeTransformedImage:(id)arg1 fromOriginalImage:(id)arg2 info:(id)arg3;
- (id)newImageLoaderInfo;

@end

