//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "_WADraggableInputContainerViewDelegate-Protocol.h"

@class NSArray, NSLayoutConstraint, NSString, UIResponder, _WADraggableInputContainerView;
@protocol WADraggableInputViewDelegate;

__attribute__((visibility("hidden")))
@interface WADraggableInputView : UIView <_WADraggableInputContainerViewDelegate>
{
    _WADraggableInputContainerView *_containerView;
    double _previousHeight;
    _Bool _ignoreKeyboardNotifications;
    NSLayoutConstraint *_topConstraintOS7;
    NSLayoutConstraint *_leftConstraintOS7;
    NSLayoutConstraint *_rightConstraintOS7;
    double _animationDurationForHeightUpdate;
    _Bool _inputViewResponderIsBecomingFirstResponder;
    _Bool _updateHeightScheduled;
    id <WADraggableInputViewDelegate> _delegate;
    double _bottomInset;
    unsigned long long _keyboardState;
}

@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(readonly, nonatomic) unsigned long long keyboardState; // @synthesize keyboardState=_keyboardState;
@property(readonly, nonatomic) double bottomInset; // @synthesize bottomInset=_bottomInset;
@property(nonatomic) __weak id <WADraggableInputViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)didMoveToSuperview;
- (void)willMoveToSuperview:(id)arg1;
- (void)keyboardDidHide:(id)arg1;
- (void)willHideKeyboardWithAnimationDuration:(double)arg1 animationCurve:(long long)arg2;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)willShowKeyboardWithAnimationDuration:(double)arg1 animationCurve:(long long)arg2;
- (void)keyboardWillShow:(id)arg1;
- (void)updateBottomInsetFromKeyboardFrame:(struct CGRect)arg1;
- (id)inputViewResponderToBecomeFirstResponder;
- (void)showKeyboardFromViewController:(id)arg1;
- (void)hideKeyboard;
@property(readonly, nonatomic, getter=isKeyboardVisible) _Bool keyboardVisible;
@property(readonly, nonatomic) UIResponder *currentFirstResponder;
@property(readonly, nonatomic) NSArray *inputViewResponders;
- (void)updateHeight;
- (void)invalidateLayout;
- (void)setNeedsUpdateHeightWithAnimationDuration:(double)arg1;
- (void)setNeedsUpdateHeight;
@property(readonly, nonatomic) double currentLayoutWidth;
- (double)preferredHeightForLayoutWidth:(double)arg1;
- (double)currentLayoutWidthForDraggableInputContainerView:(id)arg1;
- (double)draggableInputContainerView:(id)arg1 preferredHeightForLayoutWidth:(double)arg2;
- (void)didMoveToParentViewController:(id)arg1 inViewController:(id)arg2;
- (void)resignFirstResponderOnDisappearInViewController:(id)arg1;
- (void)willDisappearInViewController:(id)arg1;
- (void)didAppearInViewController:(id)arg1;
- (void)willAppearInViewController:(id)arg1;
- (_Bool)canViewControllerBecomeFirstResponder:(id)arg1;
- (void)setInitialWidth:(double)arg1;
- (void)willMoveToWindow:(id)arg1;
@property(readonly, nonatomic) struct CGRect containerViewLayoutBounds;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

