//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

__attribute__((visibility("hidden")))
@interface WAECPublicKey : NSObject
{
    NSData *_key;
}

+ (id)generatePublicKeyFromPrivateKey:(id)arg1;
@property(readonly, nonatomic) NSData *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (_Bool)validateSignature:(id)arg1 withMessage:(id)arg2;
- (id)initWithData:(id)arg1;
- (id)initWithBytes:(const char *)arg1 length:(unsigned long long)arg2;

@end

