//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPaintBrushContent.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WAEmojiStamp : WAPaintBrushContent
{
    _Bool _flipped;
    NSString *_text;
}

+ (id)cellIdentifier;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic, getter=isFlipped) _Bool flipped; // @synthesize flipped=_flipped;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (Class)textureRecipeClass;
- (Class)rendererClass;
- (struct CGSize)aspectRatio;
- (struct CGSize)sizeInPicker;
- (id)emojiStampByFlippingHorizontally;
- (id)preferredEmojiVariantForString:(id)arg1;
- (id)copyOfPreferredVariant;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithString:(id)arg1 flipped:(_Bool)arg2;
- (id)uniqueIdentifier;

@end

