//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

#import "WALinkLabelDelegate-Protocol.h"

@class NSString, WATableRow, WATableSection, _WAGDPRReportFooterView, _WAGDPRReportHeaderView;

__attribute__((visibility("hidden")))
@interface WAGDPRReportViewController : WAStaticTableViewController <WALinkLabelDelegate>
{
    WATableSection *_sectionReportActions;
    WATableRow *_rowActionButton;
    WATableRow *_rowDeleteReport;
    _WAGDPRReportHeaderView *_headerView;
    _WAGDPRReportFooterView *_footerView;
}

+ (_Bool)usesManagedTableViewHeaderFooter;
- (void).cxx_destruct;
- (void)reallyDeleteReport;
- (void)deleteReport;
- (void)shareReport;
- (void)requestReport;
- (void)reportAction;
- (void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
- (void)gdprReportDownloadFailed:(id)arg1;
- (void)gdprReportStateChanged:(id)arg1;
- (void)updateUI;
- (id)newAutoLayoutAwareTableViewFooter;
- (id)newAutoLayoutAwareTableViewHeader;
- (void)setUpTableView;
- (void)wa_fontSizeDidChange;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

