//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, UIButton, UIImageView, UILabel, WAInvertedTextMaskedLabel;
@protocol WAGIFToggleViewDelegate;

__attribute__((visibility("hidden")))
@interface WAGIFToggleView : UIView
{
    UIImageView *_videoImageView;
    UILabel *_GIFLabel;
    UIView *_leftView;
    CAShapeLayer *_fillLayer;
    UIView *_leftMaskedView;
    WAInvertedTextMaskedLabel *_rightView;
    UIButton *_toggleButton;
    _Bool _touched;
    _Bool _GIF;
    id <WAGIFToggleViewDelegate> _delegate;
}

@property(nonatomic, getter=isGIF) _Bool GIF; // @synthesize GIF=_GIF;
@property(nonatomic) __weak id <WAGIFToggleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)accessibilityActivate;
- (id)accessibilityHint;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)toggleIsGIF;
- (void)updateUIAnimated:(_Bool)arg1;
- (void)layoutSubviews;
- (void)configureGIFLabel:(id)arg1 color:(id)arg2;
- (id)text;
- (id)font;
- (id)initWithFrame:(struct CGRect)arg1;

@end

