//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAAutoMigratingStorage.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WALocationStorage : WAAutoMigratingStorage
{
    NSMutableDictionary *_senderCache;
}

- (void).cxx_destruct;
- (id)outstandingStopLocationSharingRequests;
- (void)removeStopSharingLocationRequestInChat:(id)arg1;
- (_Bool)stopSharingLocationRequestIDIsValid:(id)arg1;
- (id)setStopLocationSharingRequestOutstandingInChat:(id)arg1 retryUntil:(id)arg2;
- (void)removeExpiredChats:(id)arg1;
- (id)chatToParticipantsMapForParticipants:(id)arg1;
- (void)requestAllChatsWithRecipients:(CDUnknownBlockType)arg1;
- (id)allChatsWithRecipients;
- (id)locationRecipientsChats;
- (id)allLocationRecipients;
- (void)removeLocationRecipientJIDs:(id)arg1;
- (id)removeLocationRecipientJIDs:(id)arg1 inChat:(id)arg2;
- (void)addLocationRecipientsWithJIDs:(id)arg1 inChat:(id)arg2 messageID:(id)arg3 finalLocationExpirationDate:(id)arg4;
- (void)asyncCheckFinalLiveLocationRecipientEligibilityForMessage:(id)arg1 inChat:(id)arg2 jidToCheck:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)removeFinalLocationRecipientsInChat:(id)arg1 message:(id)arg2;
- (void)removeFinalLocationRecipientJIDs:(id)arg1;
- (void)removeFinalLocationRecords:(id)arg1;
- (void)removeExpiredFinalLocationRecords;
- (void)asyncEarliestFinalLiveLocationExpirationDate:(CDUnknownBlockType)arg1;
- (void)removeFinalLocationRecipientJIDs:(id)arg1 inChat:(id)arg2;
- (void)addFinalLocationRecipientsWithJIDs:(id)arg1 inChat:(id)arg2 messageID:(id)arg3 expirationDate:(id)arg4;
- (void)eraseExpiredCachedLocations;
- (void)asyncRemoveLocationSenderJIDs:(id)arg1 inChat:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeAllSendersInChat:(id)arg1;
- (void)setLocationMessage:(id)arg1 timestamp:(id)arg2 forParticipant:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)endDateForParticipant:(id)arg1 inChat:(id)arg2;
- (void)asyncLocationSendersInChat:(id)arg1 allowCachedResults:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)locationSendersInChat:(id)arg1 allowCachedResults:(_Bool)arg2;
- (void)asyncDisableSharingInChat:(id)arg1 forParticipant:(id)arg2 sequenceNumber:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setEndDate:(id)arg1 lastUpdate:(id)arg2 messageUniqueKey:(id)arg3 sequenceNumber:(long long)arg4 forParticipant:(id)arg5 inChat:(id)arg6 completion:(CDUnknownBlockType)arg7;
- (void)deleteDatabase;
- (void)updateCacheWithSenders:(id)arg1 forChat:(id)arg2;
- (id)lookUpOrRemoveCacheEntryWithKey:(id)arg1;
- (id)removeLocationSenderJIDs:(id)arg1 inChat:(id)arg2;
- (id)mutableLocationSendersWithJIDs:(id)arg1 inChat:(id)arg2;
- (id)mutableLocationSendersWithParticipant:(id)arg1 chat:(id)arg2;
- (id)mutableLocationRecipientsWithJIDs:(id)arg1 inChat:(id)arg2;
- (id)locationRecipientsWithJIDs:(id)arg1 inChat:(id)arg2;
- (id)fetchRequestWithClass:(Class)arg1 predicate:(id)arg2;
- (id)selectReadOnlyFromLocationSendersWhere:(id)arg1;
- (id)selectMutableFromLocationSendersWhere:(id)arg1;
- (id)selectDistinct:(id)arg1 objectsOfClass:(Class)arg2 predicate:(id)arg3;
- (id)selectDistinct:(id)arg1 fromLocationRecipientsWhere:(id)arg2;
- (id)selectReadOnlyFromLocationRecipientsWhere:(id)arg1;
- (id)selectDistinct:(id)arg1 fromFinalLocationRecipientsWhere:(id)arg2;
- (id)selectReadOnlyFromFinalLocationRecipientsWhere:(id)arg1;
- (id)selectMutableFromFinalLocationRecipientsWhere:(id)arg1;
- (id)selectMutableFromLocationRecipientsWhere:(id)arg1;
- (id)selectReadOnlyFromStopLocationSharingRequestWhere:(id)arg1;
- (id)selectMutableFromStopLocationSharingRequestWhere:(id)arg1;
- (id)selectReadOnlyObjectsOfClass:(Class)arg1 withPredicate:(id)arg2;
- (id)selectMutableObjectsOfClass:(Class)arg1 withPredicate:(id)arg2;
- (void)save;
- (void)handleDatabaseContext:(id)arg1 queryError:(id)arg2;
- (id)managedObjectContext;
- (id)initWithModel:(id)arg1 storeURL:(id)arg2 logIdentifier:(id)arg3 maximumBackgroundContextCount:(unsigned long long)arg4 blacklistBackup:(_Bool)arg5;
- (id)init;

@end

