//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAContentStamp.h"

@class NSString, UIColor, WAVectorGraphic;

__attribute__((visibility("hidden")))
@interface WALocationStamp : WAContentStamp
{
    WAVectorGraphic *_backgroundPDF;
    NSString *_name;
    NSString *_subtitle;
    id _icon;
    UIColor *_iconColor;
    double _iconAlpha;
    struct CLLocationCoordinate2D _coordinate;
}

@property(readonly, nonatomic) struct CLLocationCoordinate2D coordinate; // @synthesize coordinate=_coordinate;
@property(readonly, nonatomic) double iconAlpha; // @synthesize iconAlpha=_iconAlpha;
@property(readonly, nonatomic) UIColor *iconColor; // @synthesize iconColor=_iconColor;
@property(readonly, nonatomic) id icon; // @synthesize icon=_icon;
@property(readonly, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
@property(readonly, nonatomic) double fontWeight;
- (Class)rendererClass;
- (double)minimumInitialHeight;
-     // Error parsing type: v84@0:8@16@24f32{?=[3]}36, name: addMetadataToDictionary:fromSample:uncroppedAspectRatio:viewportTransform:
- (struct UIEdgeInsets)capInsetsForImageOfHeight:(double)arg1;
- (struct UIEdgeInsets)insetsForImageOfHeight:(double)arg1;
@property(readonly, nonatomic) double naturalHeight;
- (id)backgroundImageWithHeight:(double)arg1;
- (void)copyRefinementFrom:(id)arg1;
- (void)refineWithCompletion:(CDUnknownBlockType)arg1;
- (id)uniqueIdentifier;
- (id)initWithCoder:(id)arg1;
- (id)initWithPreviousContentStamp:(id)arg1;

@end

