//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

__attribute__((visibility("hidden")))
@interface WALogAttachmentPair : NSObject
{
    NSURL *_attachmentURL;
    NSURL *_logFileURL;
}

@property(readonly, nonatomic) NSURL *logFileURL; // @synthesize logFileURL=_logFileURL;
- (void).cxx_destruct;
- (id)compressedPostDataWithLogName:(id)arg1;
- (void)removeAttachment;
- (_Bool)hasAttachment;
- (unsigned long long)size;
- (id)initWithLogFileURL:(id)arg1 attachmentURL:(id)arg2;

@end

