//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface WAMainThreadWatchDog : NSObject
{
}

+ (void)startObservingMainRunLoop;
+ (void)processMainThreadCallStackAddresses:(id)arg1 symbols:(id)arg2;
+ (void)pokeMainThread;
+ (void)reportCriticalEventForSeverity:(unsigned long long)arg1;
+ (void)update;
+ (unsigned long long)severityForDelay:(long long)arg1;
+ (void)stopMonitoring;
+ (void)startMonitoring;
+ (float)sampleRateForSeverity:(unsigned long long)arg1;
+ (void)prepare;

@end

