//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

__attribute__((visibility("hidden")))
@interface WAMessageReceiptInfoTransformer : NSValueTransformer
{
}

+ (_Bool)allowsReverseTransformation;
+ (Class)transformedValueClass;
- (id)reverseTransformedValue:(id)arg1;
- (id)reverseTransformedReceipts:(id)arg1;
- (_Bool)isArchivedObject:(id)arg1;
- (id)transformedValue:(id)arg1;
- (id)transformedReceiptsValue:(id)arg1;

@end

