//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface WamEventIphoneMultiSendShowing : WamEvent
{
    NSNumber *_iphone_multi_send_showing_origin_number;
    NSNumber *_iphone_multi_send_shown_type_number;
    double _iphone_multi_send_shown_t;
    double _iphone_multi_send_showing_prev_image_count;
    double _iphone_multi_send_showing_current_image_count;
}

@property(nonatomic) double iphone_multi_send_showing_current_image_count; // @synthesize iphone_multi_send_showing_current_image_count=_iphone_multi_send_showing_current_image_count;
@property(nonatomic) double iphone_multi_send_showing_prev_image_count; // @synthesize iphone_multi_send_showing_prev_image_count=_iphone_multi_send_showing_prev_image_count;
@property(nonatomic) double iphone_multi_send_shown_t_milliseconds; // @synthesize iphone_multi_send_shown_t_milliseconds=_iphone_multi_send_shown_t;
- (void).cxx_destruct;
@property(nonatomic) double iphone_multi_send_shown_t_seconds;
@property(nonatomic) long long iphone_multi_send_shown_type;
- (_Bool)is_iphone_multi_send_shown_type_set;
@property(nonatomic) long long iphone_multi_send_showing_origin;
- (_Bool)is_iphone_multi_send_showing_origin_set;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

