//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface WamEventICloudMediaRestore : WamEvent
{
    NSNumber *_icloud_media_restore_result_number;
    double _icloud_media_restore_age;
    double _icloud_media_restore_size;
}

@property(nonatomic) double icloud_media_restore_size; // @synthesize icloud_media_restore_size=_icloud_media_restore_size;
@property(nonatomic) double icloud_media_restore_age; // @synthesize icloud_media_restore_age=_icloud_media_restore_age;
- (void).cxx_destruct;
@property(nonatomic) long long icloud_media_restore_result;
- (_Bool)is_icloud_media_restore_result_set;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

