//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMediaBrowserZoomableMediaCell.h"

#import "WALoopingVideoPlayerViewDelegate-Protocol.h"

@class NSString, UIImageView, WAInteractiveAnnotationView, WALoopingVideoPlayerView;

__attribute__((visibility("hidden")))
@interface WAMediaBrowserAutoPlayVideoCell : WAMediaBrowserZoomableMediaCell <WALoopingVideoPlayerViewDelegate>
{
    WALoopingVideoPlayerView *_playerView;
    UIImageView *_posterImageView;
    WAInteractiveAnnotationView *_annotationsView;
}

- (void).cxx_destruct;
- (void)loopingVideoPlayerViewDidLoad:(id)arg1;
- (void)addOrUpdateAnnotationsView;
- (_Bool)shouldConsiderTouchForTaps:(struct CGPoint)arg1;
- (void)setAccessibilityLabelForContent:(id)arg1;
- (void)copy:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)didChangeMessage;
- (void)layoutSubviewsInCell;
- (void)didChangeMessageAtStage:(long long)arg1;
- (id)viewForZooming;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

