//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSManagedObjectContext, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WAMessageDeletionContext : NSObject
{
    NSManagedObjectContext *_context;
    NSMutableArray *_batches;
}

+ (void)removeEmptyDirectories:(id)arg1 relativeTo:(id)arg2;
+ (void)removeItemsAtRelativePaths:(id)arg1;
- (void).cxx_destruct;
- (void)evaluate;
- (void)addBatch:(id)arg1;
- (id)initWithManagedObjectContext:(id)arg1;

@end

