//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMessageTextWithImageSlice.h"

__attribute__((visibility("hidden")))
@interface WAMessageGroupInviteSlice : WAMessageTextWithImageSlice
{
}

+ (_Bool)imageAlongTrailingEdge;
+ (long long)maximumNumberOfLines;
+ (long long)minimumNumberOfLines;
+ (Class)viewClass;
- (id)attributedTextWithMessage:(id)arg1 textAlignment:(out long long *)arg2;
- (struct CGSize)thumbnailSize;

@end

