//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface WamEventIphoneImageExport : WamEvent
{
    NSNumber *_iphone_image_export_algorithm_number;
    double _iphone_export_whole_flow_t;
    double _iphone_export_algorithm_t;
    double _iphone_image_quality;
    double _iphone_image_width_for_export;
    double _iphone_image_height_for_export;
    double _iphone_is_high_res_image;
    double _iphone_image_size;
}

@property(nonatomic) double iphone_image_size; // @synthesize iphone_image_size=_iphone_image_size;
@property(nonatomic) double iphone_is_high_res_image; // @synthesize iphone_is_high_res_image=_iphone_is_high_res_image;
@property(nonatomic) double iphone_image_height_for_export; // @synthesize iphone_image_height_for_export=_iphone_image_height_for_export;
@property(nonatomic) double iphone_image_width_for_export; // @synthesize iphone_image_width_for_export=_iphone_image_width_for_export;
@property(nonatomic) double iphone_image_quality; // @synthesize iphone_image_quality=_iphone_image_quality;
@property(nonatomic) double iphone_export_algorithm_t_milliseconds; // @synthesize iphone_export_algorithm_t_milliseconds=_iphone_export_algorithm_t;
@property(nonatomic) double iphone_export_whole_flow_t_milliseconds; // @synthesize iphone_export_whole_flow_t_milliseconds=_iphone_export_whole_flow_t;
- (void).cxx_destruct;
@property(nonatomic) double iphone_export_algorithm_t_seconds;
@property(nonatomic) double iphone_export_whole_flow_t_seconds;
@property(nonatomic) long long iphone_image_export_algorithm;
- (_Bool)is_iphone_image_export_algorithm_set;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

