//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

__attribute__((visibility("hidden")))
@interface WamEventGreetingMessage : WamEvent
{
    double _greeting_message_turned_off;
    double _greeting_message_turned_on;
    double _greeting_message_contents_changed;
    double _greeting_message_contents_using_default;
}

@property(nonatomic) double greeting_message_contents_using_default; // @synthesize greeting_message_contents_using_default=_greeting_message_contents_using_default;
@property(nonatomic) double greeting_message_contents_changed; // @synthesize greeting_message_contents_changed=_greeting_message_contents_changed;
@property(nonatomic) double greeting_message_turned_on; // @synthesize greeting_message_turned_on=_greeting_message_turned_on;
@property(nonatomic) double greeting_message_turned_off; // @synthesize greeting_message_turned_off=_greeting_message_turned_off;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

