//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface WamEventCatalogView : WamEvent
{
    NSNumber *_catalog_view_action_number;
    NSString *_catalog_session_id;
    double _catalog_index;
}

@property(nonatomic) double catalog_index; // @synthesize catalog_index=_catalog_index;
@property(copy, nonatomic) NSString *catalog_session_id; // @synthesize catalog_session_id=_catalog_session_id;
- (void).cxx_destruct;
@property(nonatomic) long long catalog_view_action;
- (_Bool)is_catalog_view_action_set;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

