//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAChatMessagesViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WADetailsTableSizeObserver-Protocol.h"
#import "WANavigationControllerPopFromAnimating-Protocol.h"

@class NSString, UIScrollView, UITableView, UIView, WABaseMessageDetailsTableDelegate, WAMessage;
@protocol UITableViewDelegate><UITableViewDataSource><WAMessageDetailsTableUpdateDelegate;

__attribute__((visibility("hidden")))
@interface WAMessageInfoViewController : WAChatMessagesViewController <UIGestureRecognizerDelegate, WADetailsTableSizeObserver, WANavigationControllerPopFromAnimating>
{
    UIView *_bottomBorderView;
    UIScrollView *_containerScrollView;
    _Bool _needsSetInitialPosition;
    _Bool _detailsTableUpdateScheduled;
    WAMessage *_message;
    UITableView *_detailsTableView;
    WABaseMessageDetailsTableDelegate<UITableViewDelegate><UITableViewDataSource><WAMessageDetailsTableUpdateDelegate> *_detailsTableDelegate;
}

+ (_Bool)automaticallyAdjustsTableViewContentInsets;
+ (_Bool)isEditModeSupported;
+ (_Bool)isMessageActive:(id)arg1;
@property(retain, nonatomic) WABaseMessageDetailsTableDelegate<UITableViewDelegate><UITableViewDataSource><WAMessageDetailsTableUpdateDelegate> *detailsTableDelegate; // @synthesize detailsTableDelegate=_detailsTableDelegate;
@property(retain, nonatomic) UITableView *detailsTableView; // @synthesize detailsTableView=_detailsTableView;
@property(readonly, nonatomic) WAMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (unsigned long long)presentationContextForBubbleTableViewCell:(id)arg1;
- (_Bool)usesScreenEdgePanGestureRecognizerForCustomPopTransition;
- (id)preferredPopFromInteractionController;
- (id)popFromAnimationIdentifier;
- (id)mediaManagerForMediaInMessage:(id)arg1;
- (void)popViewController;
- (void)didRevokeMessages:(id)arg1;
- (void)didDeleteMessagesInChatSession:(id)arg1;
- (void)handleMessageDeliveryStatusChangedNotification:(id)arg1;
- (void)didUpdateMessage:(id)arg1;
- (void)fadeOutDateBubblesWithAnimation:(_Bool)arg1;
- (void)reloadMessagesControllerAtMessage:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateViewPositions;
- (void)setNeedsSizeUpdate;
- (void)performDetailsTableUpdate;
- (void)updateDetailsTable;
- (void)reloadTableViewAfterExpandingMessageBubble;
- (void)reloadAfterFontSizeDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (id)uniqueIdentifier;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithMessage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

