//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

__attribute__((visibility("hidden")))
@interface WamEventPseudoHttpSession : WamEvent
{
    double _pseudo_http_send_overhead_t;
    double _pseudo_http_receive_overhead_t;
    double _pseudo_http_total_bytes_sent;
    double _pseudo_http_total_bytes_received;
    double _pseudo_http_header_bytes_sent;
    double _pseudo_http_header_bytes_received;
}

@property(nonatomic) double pseudo_http_header_bytes_received; // @synthesize pseudo_http_header_bytes_received=_pseudo_http_header_bytes_received;
@property(nonatomic) double pseudo_http_header_bytes_sent; // @synthesize pseudo_http_header_bytes_sent=_pseudo_http_header_bytes_sent;
@property(nonatomic) double pseudo_http_total_bytes_received; // @synthesize pseudo_http_total_bytes_received=_pseudo_http_total_bytes_received;
@property(nonatomic) double pseudo_http_total_bytes_sent; // @synthesize pseudo_http_total_bytes_sent=_pseudo_http_total_bytes_sent;
@property(nonatomic) double pseudo_http_receive_overhead_t_milliseconds; // @synthesize pseudo_http_receive_overhead_t_milliseconds=_pseudo_http_receive_overhead_t;
@property(nonatomic) double pseudo_http_send_overhead_t_milliseconds; // @synthesize pseudo_http_send_overhead_t_milliseconds=_pseudo_http_send_overhead_t;
@property(nonatomic) double pseudo_http_receive_overhead_t_seconds;
@property(nonatomic) double pseudo_http_send_overhead_t_seconds;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

