//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface WamEventStatusReply : WamEvent
{
    NSNumber *_status_reply_result_number;
    double _status_session_id;
}

@property(nonatomic) double status_session_id; // @synthesize status_session_id=_status_session_id;
- (void).cxx_destruct;
@property(nonatomic) long long status_reply_result;
- (_Bool)is_status_reply_result_set;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

