//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

__attribute__((visibility("hidden")))
@interface WamEventUserActivitySessionEnd : WamEvent
{
    double _user_activity_start_time;
    double _user_activity_session_length;
}

@property(nonatomic) double user_activity_session_length; // @synthesize user_activity_session_length=_user_activity_session_length;
@property(nonatomic) double user_activity_start_time; // @synthesize user_activity_start_time=_user_activity_start_time;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

