//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

__attribute__((visibility("hidden")))
@interface WamEventIphoneBadgeStats : WamEvent
{
    double _iphone_badge_stats_loss;
    double _iphone_badge_stats_algorithm_version;
    double _iphone_badge_stats_algorithm_voip;
}

@property(nonatomic) double iphone_badge_stats_algorithm_voip; // @synthesize iphone_badge_stats_algorithm_voip=_iphone_badge_stats_algorithm_voip;
@property(nonatomic) double iphone_badge_stats_algorithm_version; // @synthesize iphone_badge_stats_algorithm_version=_iphone_badge_stats_algorithm_version;
@property(nonatomic) double iphone_badge_stats_loss; // @synthesize iphone_badge_stats_loss=_iphone_badge_stats_loss;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

