//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface WamEventAppLaunch : WamEvent
{
    NSNumber *_app_launch_type_t_number;
    double _app_launch_t;
    double _app_launch_cpu_t;
    double _app_launch_main_pre_t;
    double _app_launch_main_run_t;
    double _iphone_auto_ui_unload;
}

@property(nonatomic) double iphone_auto_ui_unload; // @synthesize iphone_auto_ui_unload=_iphone_auto_ui_unload;
@property(nonatomic) double app_launch_main_run_t_milliseconds; // @synthesize app_launch_main_run_t_milliseconds=_app_launch_main_run_t;
@property(nonatomic) double app_launch_main_pre_t_milliseconds; // @synthesize app_launch_main_pre_t_milliseconds=_app_launch_main_pre_t;
@property(nonatomic) double app_launch_cpu_t_milliseconds; // @synthesize app_launch_cpu_t_milliseconds=_app_launch_cpu_t;
@property(nonatomic) double app_launch_t_milliseconds; // @synthesize app_launch_t_milliseconds=_app_launch_t;
- (void).cxx_destruct;
@property(nonatomic) long long app_launch_type_t;
- (_Bool)is_app_launch_type_t_set;
@property(nonatomic) double app_launch_main_run_t_seconds;
@property(nonatomic) double app_launch_main_pre_t_seconds;
@property(nonatomic) double app_launch_cpu_t_seconds;
@property(nonatomic) double app_launch_t_seconds;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

