//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMessageContainerSlice.h"

@class NSLayoutManager, NSTextContainer, NSTextStorage, WAMessagePaymentStatusSliceRenderer;

__attribute__((visibility("hidden")))
@interface WAMessagePaymentSlice : WAMessageContainerSlice
{
    NSTextStorage *_textStorage;
    NSTextContainer *_textContainer;
    NSLayoutManager *_layoutManager;
    struct CGRect _textRect;
    WAMessagePaymentStatusSliceRenderer *_statusRenderer;
    _Bool _fromMe;
}

+ (Class)viewClass;
@property(readonly, nonatomic, getter=isFromMe) _Bool fromMe; // @synthesize fromMe=_fromMe;
- (void).cxx_destruct;
- (id)attributedTextWithMessage:(id)arg1;
- (void)drawInCurrentContext;
- (void)internalFitToWidth:(double)arg1;
- (id)initWithMessages:(id)arg1 metrics:(CDStruct_8ee84fd7)arg2;

@end

