//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface WamEventLiveLocationSharingSession : WamEvent
{
    NSNumber *_live_location_sharing_session_ended_reason_number;
    double _live_location_sharing_session_t;
}

@property(nonatomic) double live_location_sharing_session_t_milliseconds; // @synthesize live_location_sharing_session_t_milliseconds=_live_location_sharing_session_t;
- (void).cxx_destruct;
@property(nonatomic) long long live_location_sharing_session_ended_reason;
- (_Bool)is_live_location_sharing_session_ended_reason_set;
@property(nonatomic) double live_location_sharing_session_t_seconds;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

