//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDataDelegate-Protocol.h"
#import "NSURLSessionTaskDelegate-Protocol.h"

@class NSError, NSString, NSURL, NSURLSession, NSURLSessionTask, WAMMSDownloadFileTaskMetrics;

__attribute__((visibility("hidden")))
@interface WAMMSDownloadFileTaskV3 : NSObject <NSURLSessionTaskDelegate, NSURLSessionDataDelegate>
{
    NSURLSession *_session;
    NSURL *_mms3DownloadURL;
    NSString *_destinationFilePath;
    _Bool _cellularAllowed;
    NSString *_loggingIdentifier;
    NSURLSessionTask *_sessionTask;
    CDUnknownBlockType _completion;
    CDUnknownBlockType _progressHandler;
    long long _entityLength;
    long long _downloadedSize;
    struct __sFILE *_fileOutputStream;
    NSError *_error;
    WAMMSDownloadFileTaskMetrics *_downloadMetrics;
    double _firstDataDelegateCallbackTime;
}

+ (id)queue;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (id)createURLSessionTaskWithBaseRequest:(id)arg1;
- (void)finishWithResponse:(id)arg1 error:(id)arg2;
- (void)cancel;
- (void)resume;
- (id)initWithMMS3DownloadURL:(id)arg1 cellularAllowed:(_Bool)arg2 destinationFilePath:(id)arg3 progressHandler:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

