//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WASimpleOperation-Protocol.h"

@class NSData, NSError, NSString, WAMMSBaseTask, WAMMSBaseTaskResumePolicy, WAMMSMediaTransferOperationAsset, WAMMSMediaUploadOperationMetrics, WAMMSMediaUploadOperationRequest, WAMMSTaskDescription, WAMMSTaskSession, WAMediaCipher, WAMediaKey, WamEventMediaUpload, WamEventMediaUpload2;
@protocol OS_dispatch_queue, WAMMSMediaUploadOperationDelegate;

__attribute__((visibility("hidden")))
@interface WAMMSMediaUploadOperation : NSObject <WASimpleOperation>
{
    WAMMSMediaUploadOperationRequest *_request;
    unsigned long long _currentRetryCount;
    WAMMSTaskSession *_taskSession;
    NSObject<OS_dispatch_queue> *_queue;
    id <WAMMSMediaUploadOperationDelegate> _delegate;
    WAMMSBaseTask *_currentTask;
    unsigned long long _uploadType;
    _Bool _finishedStreaming;
    NSError *_error;
    _Bool _isTerminalError;
    // Error parsing type: AI, name: _currentPhase
    WAMediaCipher *_finalizedMediaCipherForAsset;
    WAMMSBaseTaskResumePolicy *_resumePolicyToUse;
    WAMMSTaskDescription *_commonMMSTaskDescription;
    WAMMSMediaTransferOperationAsset *_currentAsset;
    WAMediaKey *_mediaKey;
    NSData *_encHash;
    _Bool _usedFakeStreamingEncHash;
    unsigned long long _uploadOffset;
    _Bool _attemptedChatdResumeCheck;
    _Bool _skippedUpload;
    // Error parsing type: Ai, name: _progressPercentage
    NSString *_downloadURL;
    NSString *_directPath;
    _Bool _forceNewMediaKey;
    WamEventMediaUpload *_uploadEvent;
    WamEventMediaUpload2 *_uploadEvent2;
    WAMMSMediaUploadOperationMetrics *_metrics;
    double _startTime;
    NSError *_uploadError;
    NSData *_fakeStreamingEncHash;
}

+ (id)uploadEventWithUploadType:(unsigned long long)arg1 request:(id)arg2;
+ (id)uploadEventWithUploadType2:(unsigned long long)arg1 request:(id)arg2;
@property(copy) NSData *fakeStreamingEncHash; // @synthesize fakeStreamingEncHash=_fakeStreamingEncHash;
@property(retain) NSError *uploadError; // @synthesize uploadError=_uploadError;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool optimistic;
- (unsigned long long)currentRetryCount;
- (double)startTime;
- (id)metrics;
- (id)uploadEvent2;
- (id)uploadEvent;
- (void)computeEncHashWithAsset:(id)arg1 mediaKey:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setAndRunCompletionPhaseWithError:(id)arg1 httpResponse:(id)arg2;
- (void)performCompletionPhase;
- (void)performFinalizePhase;
- (void)performFileUploadPhase;
- (void)performResumeCheck;
- (void)performPreflightPhase;
- (void)runPhase;
@property(readonly, nonatomic) unsigned long long taskType;
@property(readonly, nonatomic) _Bool streaming;
@property unsigned long long currentPhase;
- (void)optimisticUploadTakeover;
- (void)finishStreaming;
- (void)queued;
- (void)cancel;
- (void)resume;
@property(readonly) double progressPercentage;
@property(readonly) WAMMSMediaUploadOperationRequest *request;
- (id)initWithUploadRequest:(id)arg1 mmsSession:(id)arg2 queue:(id)arg3 uploadType:(unsigned long long)arg4 delegate:(id)arg5;
- (id)initWithUploadRequest:(id)arg1 mmsSession:(id)arg2 queue:(id)arg3 delegate:(id)arg4;
- (void)start;
- (unsigned long long)priority;
- (void)fieldstatCompletionPhaseWithError:(id)arg1;
- (id)createFinalizePhaseRetryEventWithResult:(id)arg1 uploadEventResult:(long long)arg2 error:(id)arg3;
- (void)fieldstatFileUploadPhaseCommonFieldsWithResult:(id)arg1 uploadEvent:(id)arg2;
- (void)fieldstatFileUploadPhaseFailureWithResult:(id)arg1;
- (void)fieldstatFileUploadPhaseSuccessWithResult:(id)arg1 complete:(_Bool)arg2;
- (id)createFileUploadPhaseRetryEventWithResult:(id)arg1 uploadEventResult:(long long)arg2 error:(id)arg3;
- (void)fieldstatResumeCheckPhaseSuccessWithResult:(id)arg1;
- (void)fieldstatResumeCheckPhaseFailureWithResult:(id)arg1;
- (id)createResumeCheckPhaseRetryEventWithResult:(id)arg1 uploadEventResult:(long long)arg2 error:(id)arg3;
- (void)fieldstatPreflightPhaseWithAsset:(id)arg1 transcoded:(_Bool)arg2;
- (void)fieldstatCommonDebugFieldsForFailedEvent:(id)arg1 result:(id)arg2 error:(id)arg3 hostIP:(id)arg4;
- (void)fieldstatCompletionFieldsForEvent:(id)arg1 uploadEventResult:(long long)arg2;
- (void)fieldstatCompletionPhaseWithError2:(id)arg1;
- (void)fieldstatCommonFinalizeFieldsForEvent:(id)arg1 result:(id)arg2;
- (void)fieldstatFinalizePhaseSuccessWithResult2:(id)arg1;
- (void)fieldstatFinalizePhaseFailureWithResult2:(id)arg1 error:(id)arg2;
- (id)createFinalizePhaseRetryEventWithResult2:(id)arg1 uploadEventResult:(long long)arg2 error:(id)arg3;
- (void)fieldstatCommonFileUploadFieldsForEvent:(id)arg1 result:(id)arg2;
- (void)fieldstatFileUploadPhaseSuccessWithResult2:(id)arg1 complete:(_Bool)arg2;
- (void)fieldstatFileUploadPhaseFailureWithResult2:(id)arg1 error:(id)arg2;
- (id)createFileUploadPhaseRetryEventWithResult2:(id)arg1 uploadEventResult:(long long)arg2 error:(id)arg3;
- (void)fieldstatCommonResumeCheckFieldsForEvent:(id)arg1 result:(id)arg2;
- (void)fieldstatResumeCheckPhaseSuccessWithResult2:(id)arg1;
- (void)fieldstatResumeCheckPhaseFailureWithResult2:(id)arg1 error:(id)arg2;
- (id)createResumeCheckPhaseRetryEventWithResult2:(id)arg1 uploadEventResult:(long long)arg2 error:(id)arg3;
- (void)fieldstatPreflightPhaseWithUploadType2:(unsigned long long)arg1 asset:(id)arg2 transcoded:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

