//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WAMMSAsyncResumeCheckResult : NSObject
{
    NSString *_directPath;
    NSString *_downloadURL;
}

@property(copy, nonatomic) NSString *downloadURL; // @synthesize downloadURL=_downloadURL;
@property(copy, nonatomic) NSString *directPath; // @synthesize directPath=_directPath;
- (void).cxx_destruct;

@end

