//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMultiSendImageWriter.h"

__attribute__((visibility("hidden")))
@interface WAMultiSendPNGImageWriter : WAMultiSendImageWriter
{
}

+ (id)encodeImage:(id)arg1 quality:(id)arg2 firstScanLength:(unsigned long long *)arg3;

@end

