//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMultiSendMediaItem.h"

#import "WAGIFTranscoderProgressDelegate-Protocol.h"

@class NSData, NSString, NSURL, NSURLSessionDataTask, UIImage, WAGIFTranscoder;

__attribute__((visibility("hidden")))
@interface WAMultiSendPlaceholder : WAMultiSendMediaItem <WAGIFTranscoderProgressDelegate>
{
    UIImage *_placeholderImage;
    WAGIFTranscoder *_transcoder;
    NSURL *_downloadedContentURL;
    NSURLSessionDataTask *_downloadTask;
    struct CGSize _aspectRatio;
    _Bool _failedToDownload;
    _Bool _failedToTranscode;
    CDUnknownBlockType _exportCompletionHandler;
    CDUnknownBlockType _internalExportProgressHandler;
    _Bool _isSavedToCameraRoll;
    _Bool _shouldSaveToCameraRollOnCompletion;
    _Bool _cancled;
    long long _retriesLeft;
    _Bool _failedToDownloadBecauseOfNetworkProblem;
    NSURL *_videoPreviewURL;
    NSData *_GIFData;
    unsigned long long _type;
}

@property(readonly, nonatomic) _Bool failedToDownloadBecauseOfNetworkProblem; // @synthesize failedToDownloadBecauseOfNetworkProblem=_failedToDownloadBecauseOfNetworkProblem;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, nonatomic) NSData *GIFData; // @synthesize GIFData=_GIFData;
@property(readonly, nonatomic) NSURL *videoPreviewURL; // @synthesize videoPreviewURL=_videoPreviewURL;
- (void).cxx_destruct;
- (void)reallyExportWithProgressHandler:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)GIFTranscoderDidFailTranscode:(id)arg1;
- (void)GIFTranscoder:(id)arg1 didCompletedWithFilePath:(id)arg2;
- (void)GIFTranscoderDidUpdateProgress:(id)arg1;
- (void)removeAudioTracksFromFile:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)accessibilityLabel;
- (void)saveToCameraRollAsynchronouslyIfNeeded;
- (void)notifyFail;
- (void)notifySuccess;
@property(readonly, nonatomic) _Bool showIndefiniteProgress;
@property(readonly, nonatomic) struct CGSize aspectRatio;
@property(readonly, nonatomic) _Bool exportFailed;
- (float)exportProgress;
@property(readonly, nonatomic) float transcodeProgress;
- (void)cancelCurrentExport;
- (void)setNeedsExport;
- (id)generateOriginalImageForPreview;
- (_Bool)isEditable;
- (_Bool)isExportedPlaceholder;
- (_Bool)isPlaceholder;
- (_Bool)isGIF;
- (void)setIsGIF;
- (void)transcodeGIFData;
- (void)didDownloadVideo;
- (void)downloadOfAsset:(id)arg1 url:(id)arg2 startTime:(double)arg3 didCompleteWithData:(id)arg4 response:(id)arg5 error:(id)arg6;
- (_Bool)shouldRetryDownloadOnError:(id)arg1;
- (void)downloadURL:(id)arg1 gifAsset:(id)arg2;
- (void)dealloc;
- (id)initWithGIFData:(id)arg1 gifProvider:(id)arg2 assetIdentifier:(id)arg3 automaticGIFExport:(_Bool)arg4 quality:(id)arg5;
- (id)initWithUndownloadedURL:(id)arg1 contentURL:(id)arg2 previewURL:(id)arg3 gifAsset:(id)arg4 gifProvider:(id)arg5 thumbnail:(id)arg6 aspectRatio:(struct CGSize)arg7 quality:(id)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

