//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CIFilter, NSArray, NSDate, NSDictionary, NSNumber, NSString, NSURL, UIColor, UIImage, WAGIFAsset, WAMediaFilterRenderer, WAMultiSendMediaItemQuality, WAPageableItemView, WAPaintCanvas, WAPaintCanvasDevice, WARichText;
@protocol OS_dispatch_group;

__attribute__((visibility("hidden")))
@interface WAMultiSendMediaItem : NSObject
{
    float _exportProgress;
    NSURL *_exportedContentURL;
    NSURL *_referenceURL;
    NSDictionary *_metadata;
    _Bool _exportInProgress;
    _Bool _exportCancelled;
    UIImage *_thumbnail;
    UIColor *_accentColor;
    _Bool _needsExport;
    long long _renderID;
    NSObject<OS_dispatch_group> *_renderDispatchGroup;
    NSObject<OS_dispatch_group> *_exportDispatchGroup;
    _Bool _isSavedToCameraRoll;
    WAPaintCanvas *_paintCanvas;
    _Bool _needsSetUpPaintCanvas;
    UIImage *_originalImageForPreview;
    UIImage *_filteredOriginalImageForPreview;
    _Bool _originalGIF;
    _Bool _isWebPreviewMedia;
    _Bool _renderingInProgress;
    _Bool _removeFileUponDeallocation;
    _Bool _renderingEnabled;
    _Bool _needsRender;
    _Bool _exportAutomatically;
    _Bool _exportedContentURLConsumed;
    id _identifier;
    NSString *_UUID;
    WARichText *_text;
    WAPageableItemView *_presentingItemView;
    NSURL *_alAssetURL;
    double _rotationAngle;
    WAMultiSendMediaItemQuality *_quality;
    NSDate *_date;
    CDUnknownBlockType _exportProgressHandler;
    unsigned long long _currentExportType;
    WAGIFAsset *_gifAsset;
    NSNumber *_gifProvider;
    NSArray *_interactiveAnnotations;
    NSURL *_sourceURL;
    CIFilter *_filter;
    WAMediaFilterRenderer *_filterRenderer;
    struct CGSize _cropSize;
    struct CGPoint _anchorPoint;
}

+ (id)multiSendMediaItemWithTemporaryFileURL:(id)arg1 isVideo:(_Bool)arg2 quality:(id)arg3;
+ (id)multiSendMediaItemWithMediaPickerItem:(id)arg1 automaticGIFExport:(_Bool)arg2 quality:(id)arg3;
+ (id)multiSendMediaItemWithMediaPickerItem:(id)arg1 quality:(id)arg2;
+ (id)itemForExportedPlaceholderItem:(id)arg1 quality:(id)arg2;
+ (id)mediaItemForGIFData:(id)arg1 gifProvider:(id)arg2 quality:(id)arg3;
+ (id)mediaItemWithAssetIdentifier:(id)arg1 media:(id)arg2 info:(id)arg3 quality:(id)arg4;
+ (id)mediaItemWithAssetIdentifier:(id)arg1 media:(id)arg2 quality:(id)arg3;
+ (id)fileURLToTemporaryDirectory;
+ (void)initialize;
@property(retain, nonatomic) WAMediaFilterRenderer *filterRenderer; // @synthesize filterRenderer=_filterRenderer;
@property(retain, nonatomic) CIFilter *filter; // @synthesize filter=_filter;
@property(readonly, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(copy, nonatomic) NSArray *interactiveAnnotations; // @synthesize interactiveAnnotations=_interactiveAnnotations;
@property(retain, nonatomic) NSNumber *gifProvider; // @synthesize gifProvider=_gifProvider;
@property(retain, nonatomic) WAGIFAsset *gifAsset; // @synthesize gifAsset=_gifAsset;
@property(nonatomic, getter=isExportedContentURLConsumed) _Bool exportedContentURLConsumed; // @synthesize exportedContentURLConsumed=_exportedContentURLConsumed;
@property(nonatomic) _Bool exportAutomatically; // @synthesize exportAutomatically=_exportAutomatically;
@property(readonly, nonatomic) _Bool needsRender; // @synthesize needsRender=_needsRender;
@property(readonly, nonatomic) unsigned long long currentExportType; // @synthesize currentExportType=_currentExportType;
@property(nonatomic, getter=isRenderingEnabled) _Bool renderingEnabled; // @synthesize renderingEnabled=_renderingEnabled;
@property(nonatomic) _Bool removeFileUponDeallocation; // @synthesize removeFileUponDeallocation=_removeFileUponDeallocation;
@property(readonly, nonatomic) float exportProgress; // @synthesize exportProgress=_exportProgress;
@property(copy, nonatomic) CDUnknownBlockType exportProgressHandler; // @synthesize exportProgressHandler=_exportProgressHandler;
@property(readonly, nonatomic) NSURL *exportedContentURL; // @synthesize exportedContentURL=_exportedContentURL;
@property(readonly, nonatomic) NSDate *date; // @synthesize date=_date;
@property(readonly, nonatomic) WAMultiSendMediaItemQuality *quality; // @synthesize quality=_quality;
@property(readonly, nonatomic) _Bool renderingInProgress; // @synthesize renderingInProgress=_renderingInProgress;
@property(nonatomic) double rotationAngle; // @synthesize rotationAngle=_rotationAngle;
@property(nonatomic) struct CGPoint anchorPoint; // @synthesize anchorPoint=_anchorPoint;
@property(nonatomic) struct CGSize cropSize; // @synthesize cropSize=_cropSize;
@property(readonly, nonatomic) NSURL *alAssetURL; // @synthesize alAssetURL=_alAssetURL;
@property(nonatomic) __weak WAPageableItemView *presentingItemView; // @synthesize presentingItemView=_presentingItemView;
@property(readonly, copy, nonatomic) NSURL *referenceURL; // @synthesize referenceURL=_referenceURL;
@property(nonatomic) _Bool isWebPreviewMedia; // @synthesize isWebPreviewMedia=_isWebPreviewMedia;
@property(nonatomic, getter=isOriginalGIF) _Bool originalGIF; // @synthesize originalGIF=_originalGIF;
@property(copy, nonatomic) WARichText *text; // @synthesize text=_text;
@property(readonly, copy, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
@property(copy, nonatomic) id identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long firstScanLength;
- (void)submitExportEventIfNecessary;
- (void)submitDocumentDetectionEventIfNecessary;
@property(retain, nonatomic) UIImage *highResolutionImage;
@property(readonly, nonatomic) _Bool isLikeDocument;
@property(readonly, nonatomic) UIImage *filteredOriginalImageForPreview;
- (void)advanceToNextFilter;
- (void)didChangeFilter;
@property(readonly, nonatomic) _Bool hasFilter;
- (void)didUpdatePaintCanvasContent;
@property(readonly, nonatomic) WAPaintCanvas *paintCanvas;
@property(retain, nonatomic) WAPaintCanvasDevice *paintCanvasDevice;
@property(readonly, copy, nonatomic) NSString *accessibilityValue;
@property(readonly, copy, nonatomic) NSString *accessibilityLabel;
- (id)thumbnailFromLocalPhotoLibrary;
@property(readonly, nonatomic) UIImage *thumbnail;
@property(readonly, nonatomic) UIColor *accentColor;
- (id)generateOriginalImageForPreview;
- (void)invalidateOriginalImageForPreview;
- (void)invalidateThumbnail;
@property(readonly, nonatomic) UIImage *originalImageForPreview;
@property(readonly, nonatomic) UIImage *renderedImage;
@property(readonly, nonatomic) id renderedContent;
- (void)downgradeToQualityIfNeeded:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reallyExportWithProgressHandler:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)internalExportContent;
- (void)exportWithSendingType:(unsigned long long)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)cancelCurrentExport;
- (void)setNeedsExport;
- (void)performBlockAfterRendering:(CDUnknownBlockType)arg1;
- (void)renderWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)internalRenderContent;
- (void)setNeedsRender;
@property(readonly, nonatomic, getter=isIdentityTransform) _Bool identityTransform;
@property(readonly, nonatomic) _Bool rightAngleRotationOnly;
- (void)didChangeTransform;
- (void)setRotationAngle:(double)arg1 adjustCropSize:(_Bool)arg2;
@property(nonatomic) CDStruct_6b9f5eac transformInfo;
@property(readonly, nonatomic, getter=isFilterable) _Bool filterable;
@property(readonly, nonatomic, getter=isCroppable) _Bool croppable;
- (void)saveToCameraRollAsynchronouslyIfNeeded;
- (void)didReceiveMemoryWarning;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
@property(readonly, nonatomic, getter=isEditable) _Bool editable;
@property(readonly, nonatomic) _Bool isExportedPlaceholder;
@property(readonly, nonatomic) _Bool isPlaceholder;
@property(readonly, nonatomic) _Bool isGIF;
@property(nonatomic, getter=isVideoAsGIF) _Bool videoAsGIF;
- (_Bool)isGIFCapeable;
@property(readonly, nonatomic) _Bool isVideo;
- (void)prepareWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)description;
- (void)dealloc;
- (void)copyAttributesFromItem:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSourceURL:(id)arg1 assetIdentifier:(id)arg2 quality:(id)arg3;

@end

