//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPaintBrushContentCollectionViewCell.h"

@class WAEmojiStamp, WAPaintBrushEmojiStampCollectionViewCellTextLabel;

__attribute__((visibility("hidden")))
@interface WAPaintBrushEmojiStampCollectionViewCell : WAPaintBrushContentCollectionViewCell
{
    WAPaintBrushEmojiStampCollectionViewCellTextLabel *_label;
}

- (void).cxx_destruct;
- (void)didChangeContent;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(retain, nonatomic) WAEmojiStamp *content; // @dynamic content;

@end

