//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WATableViewController.h"

#import "WAPaymentLoadingViewControllerType-Protocol.h"

@class NSArray, NSIndexPath, NSString, UIBarButtonItem, UILabel, UIView, WAActivityLabel, WAViewControllerConnectionObserver;

__attribute__((visibility("hidden")))
@interface WAPaymentUPIAccountsViewController : WATableViewController <WAPaymentLoadingViewControllerType>
{
    double _cachedRowHeight;
    NSIndexPath *_selectedIndexPath;
    NSIndexPath *_previouslySelectedIndexPath;
    WAActivityLabel *_titleActivityLabel;
    UIBarButtonItem *_cancelItem;
    CDUnknownBlockType _loadingCancelledHandler;
    WAViewControllerConnectionObserver *_connectionObserver;
    CDUnknownBlockType _completionHandler;
    NSArray *_accounts;
    UIView *_tableHeader;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
}

+ (id)controller;
@property(nonatomic) __weak UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *tableHeader; // @synthesize tableHeader=_tableHeader;
@property(copy, nonatomic) NSArray *accounts; // @synthesize accounts=_accounts;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void).cxx_destruct;
- (void)stopLoadingUI;
- (void)startLoadingUIWithCancelHandler:(CDUnknownBlockType)arg1;
- (id)identifier;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)cancelAction;
- (void)updateTitleAndBarItem;
- (void)wa_fontSizeDidChange;
- (_Bool)wa_prefersMinimalBackButton;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

