//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class WAPaymentTransaction, WAPaymentTransactionCell;

@protocol WAPaymentTransactionCellDelegate
- (void)paymentTransactionCell:(WAPaymentTransactionCell *)arg1 didCancelOutgoingCollectRequestTransaction:(WAPaymentTransaction *)arg2;
- (void)paymentTransactionCell:(WAPaymentTransactionCell *)arg1 didDeclineIncomingCollectRequestTransaction:(WAPaymentTransaction *)arg2;
- (void)paymentTransactionCell:(WAPaymentTransactionCell *)arg1 didAcceptIncomingCollectRequestTransaction:(WAPaymentTransaction *)arg2;
@end

