//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAPaintCanvas, WAPaintPositionSample;
@protocol CAMetalDrawable;

@protocol WAPaintCanvasDelegate <NSObject>
- (void)paintCanvas:(WAPaintCanvas *)arg1 didUpdateSampleForPinch:(WAPaintPositionSample *)arg2;
- (void)paintCanvas:(WAPaintCanvas *)arg1 didDeleteItemAtCropSpacePosition: /* Error: Ran out of types for this method. */;
- (void)paintCanvas:(WAPaintCanvas *)arg1 shouldEnterPendingDeletionState:(_Bool)arg2;
- (_Bool)paintCanvas:(WAPaintCanvas *)arg1 shouldDeleteItemAtCropSpacePosition: /* Error: Ran out of types for this method. */;
- (void)paintCanvasDidUpdateTextItems:(WAPaintCanvas *)arg1;
- (void)paintCanvasDidChangeViewport:(WAPaintCanvas *)arg1;
- (struct CGSize)drawableSizeForPaintCanvas:(WAPaintCanvas *)arg1;
- (id <CAMetalDrawable>)drawableForPaintCanvas:(WAPaintCanvas *)arg1;
@end

