//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableString, NSString, UIImage, WAWeakTimer;
@protocol WAPasscodeViewDelegate;

__attribute__((visibility("hidden")))
@interface WAPasscodeView : UIView
{
    UIImage *_setImage;
    UIImage *_unsetImage;
    NSMutableString *_currentPasscode;
    double _lastCharacterAddedTime;
    WAWeakTimer *_redrawTimer;
    _Bool _enabled;
    _Bool _splitsCenter;
    id <WAPasscodeViewDelegate> _delegate;
    unsigned long long _maxCharacterCount;
}

@property(readonly, nonatomic) _Bool splitsCenter; // @synthesize splitsCenter=_splitsCenter;
@property(readonly, nonatomic) unsigned long long maxCharacterCount; // @synthesize maxCharacterCount=_maxCharacterCount;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <WAPasscodeViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(nonatomic, getter=isSecureTextEntry) _Bool secureTextEntry;
@property(nonatomic) long long keyboardType;
- (void)deleteBackward;
- (void)insertText:(id)arg1;
@property(readonly, nonatomic) _Bool hasText;
- (void)touchesEstimatedPropertiesUpdated:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)shakeWithCompletion:(CDUnknownBlockType)arg1;
- (void)clearPasscodeEntry;
@property(readonly, nonatomic) _Bool passcodeFilled;
@property(readonly, nonatomic) NSString *passcode;
- (id)initWithFrame:(struct CGRect)arg1 maxCharacterCount:(unsigned long long)arg2 splitsCenter:(_Bool)arg3;

// Remaining properties
@property(nonatomic) long long autocapitalizationType;
@property(nonatomic) long long autocorrectionType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool enablesReturnKeyAutomatically;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long keyboardAppearance;
@property(nonatomic) long long returnKeyType;
@property(nonatomic) long long smartDashesType;
@property(nonatomic) long long smartInsertDeleteType;
@property(nonatomic) long long smartQuotesType;
@property(nonatomic) long long spellCheckingType;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *textContentType;

@end

