//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAPaintCanvasAnimatableObject-Protocol.h"

@class NSString, WAPaintBrushRenderer, WAPaintPositionSample;

__attribute__((visibility("hidden")))
@interface WAPaintCanvasAnimatableSample : NSObject <WAPaintCanvasAnimatableObject>
{
    // Error parsing type: , name: _initialSize
    // Error parsing type: , name: _size
    unsigned int _index;
    WAPaintPositionSample *_sample;
    WAPaintBrushRenderer *_renderer;
}

@property(readonly, nonatomic) unsigned int index; // @synthesize index=_index;
@property(readonly, nonatomic) WAPaintBrushRenderer *renderer; // @synthesize renderer=_renderer;
@property(readonly, nonatomic) WAPaintPositionSample *sample; // @synthesize sample=_sample;
- (void).cxx_destruct;
- (CDUnknownBlockType)updateAnimationBlock;
@property(nonatomic) struct CGSize size;
- (id)initWithSample:(id)arg1 renderer:(id)arg2 index:(unsigned int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

