//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "WAVerificationLinkHandling-Protocol.h"

@class NSString, NSTimer, UIButton, UILabel, UIProgressView, UITextField, UIView, WAOverlayView;
@protocol WAPassInputViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAPassInputViewController : WAViewController <WAVerificationLinkHandling>
{
    int _codeInputBlockState;
    WAOverlayView *_overlayView;
    double _keyboardHeight;
    NSTimer *_codeInputBlockProgressUpdateTimer;
    NSTimer *_codeRequestButtonsStateUpdateTimer;
    _Bool _shouldShowActivityIndicator;
    _Bool _registerRequestInProgress;
    _Bool _changePhoneNumberMode;
    id <WAPassInputViewControllerDelegate> _delegate;
    NSString *_verificationCodeFromURL;
    NSString *_acceptedVerificationCode;
    UIView *_viewContainer;
    UILabel *_labelHelperText1;
    UILabel *_labelHelperText2;
    UIView *_codeInputFieldContainer;
    UITextField *_textFieldCode;
    UILabel *_labelCode;
    UIView *_codeRequestButtonsContainer;
    UIButton *_buttonRequestSMS;
    UIButton *_buttonRequestCall;
    UIView *_viewUIBlocked;
    UILabel *_labelUIBlocked;
    UIProgressView *_progressViewBlock;
}

+ (void)processAvailabilityOfVerificationMethodsInServerResponse:(id)arg1;
+ (_Bool)isDateDistantFuture:(id)arg1;
@property(retain, nonatomic) UIProgressView *progressViewBlock; // @synthesize progressViewBlock=_progressViewBlock;
@property(retain, nonatomic) UILabel *labelUIBlocked; // @synthesize labelUIBlocked=_labelUIBlocked;
@property(retain, nonatomic) UIView *viewUIBlocked; // @synthesize viewUIBlocked=_viewUIBlocked;
@property(retain, nonatomic) UIButton *buttonRequestCall; // @synthesize buttonRequestCall=_buttonRequestCall;
@property(retain, nonatomic) UIButton *buttonRequestSMS; // @synthesize buttonRequestSMS=_buttonRequestSMS;
@property(retain, nonatomic) UIView *codeRequestButtonsContainer; // @synthesize codeRequestButtonsContainer=_codeRequestButtonsContainer;
@property(retain, nonatomic) UILabel *labelCode; // @synthesize labelCode=_labelCode;
@property(retain, nonatomic) UITextField *textFieldCode; // @synthesize textFieldCode=_textFieldCode;
@property(retain, nonatomic) UIView *codeInputFieldContainer; // @synthesize codeInputFieldContainer=_codeInputFieldContainer;
@property(retain, nonatomic) UILabel *labelHelperText2; // @synthesize labelHelperText2=_labelHelperText2;
@property(retain, nonatomic) UILabel *labelHelperText1; // @synthesize labelHelperText1=_labelHelperText1;
@property(retain, nonatomic) UIView *viewContainer; // @synthesize viewContainer=_viewContainer;
@property(readonly, nonatomic) NSString *acceptedVerificationCode; // @synthesize acceptedVerificationCode=_acceptedVerificationCode;
@property(nonatomic) _Bool changePhoneNumberMode; // @synthesize changePhoneNumberMode=_changePhoneNumberMode;
@property(copy, nonatomic) NSString *verificationCodeFromURL; // @synthesize verificationCodeFromURL=_verificationCodeFromURL;
@property(nonatomic) __weak id <WAPassInputViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)launchedFromVerificationURLWithCode:(id)arg1;
- (void)enterVerificationCodeFromURL:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)wa_applicationDidBecomeActive;
- (void)wa_tintColorDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)touchCatcherButtonTapped;
- (void)viewDidLoad;
- (void)presentLearnMoreAlert:(id)arg1 message:(id)arg2;
- (void)presentAppStoreAlert:(id)arg1;
- (void)presentUnspecifiedErrorAlert;
- (void)presentGenericAlert:(id)arg1;
- (void)presentContactSupportAlert:(id)arg1 withContext:(id)arg2;
- (void)presentCodeEntryFailedAlertWithTitle:(id)arg1 message:(id)arg2;
- (void)validationOfCode:(id)arg1 failedWithError:(id)arg2;
- (void)validationOfCode:(id)arg1 finishedWithResult:(id)arg2;
- (void)validateCurrentCodeWithEntryMethod:(int)arg1;
- (void)codeEditedAction:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
@property(readonly, nonatomic) long long verificationCodeLength;
- (void)retryWithSavedPasscodeIfNeeded;
- (void)formatCodePresentation;
- (void)resetCodeInput;
- (void)activateCodeInputFieldIfPossible;
- (void)validateCodeInputBlockState;
- (void)updateCodeInputBlockProgress:(id)arg1;
- (void)startCodeInputBlockProgressUpdateTimer;
- (void)setCodeInputBlockState:(int)arg1;
- (void)setFullVerificationCode:(id)arg1;
- (void)codeRequestFailedWithError:(id)arg1;
- (void)codeRequestWithMethod:(id)arg1 finishedWithResult:(id)arg2;
- (void)requestVerificationCodeWithMethod:(id)arg1;
- (void)requestCall:(id)arg1;
- (void)requestSMS:(id)arg1;
- (void)validateStateOfCodeRequestButtons;
- (void)updateStateOfCodeRequestButtons:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)finishController;
- (void)setHeaderLabelText:(_Bool)arg1;
- (void)adjustHelperTextFont;
- (void)resizeHelperTextLabels;
- (void)layoutAllSubviews;
- (void)hideOverlayWithCompletion:(CDUnknownBlockType)arg1 setViewTitle:(id)arg2;
- (void)showOverlay:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

