//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAPaintCanvasLayerDelegate-Protocol.h"

@class MTLRenderPassDescriptor, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSUndoManager, UIImage, UIImpactFeedbackGenerator, WACachedCopyMutableArray, WAPaintBrush, WAPaintBrushBasic, WAPaintBrushDesaturate, WAPaintBrushPixelate, WAPaintBrushRenderer, WAPaintBrushStrokeInterpolator, WAPaintCanvasDevice;
@protocol MTLCommandBuffer, MTLCommandQueue, MTLLibrary, MTLRenderPipelineState, WAPaintCanvasDelegate;

__attribute__((visibility("hidden")))
@interface WAPaintCanvas : NSObject <WAPaintCanvasLayerDelegate>
{
    _Bool _needsRedraw;
    _Bool _needsSnapshot;
    WAPaintBrushRenderer *_rendererAfterSnapshot;
    _Bool _needsFullRedraw;
    float _pixelsPerUnit;
    float _lastPaintedPixelsPerUnit;
    // Error parsing type: {?="columns"[3]}, name: _mat
    NSArray *_layers;
    WAPaintBrush *_currentBrush;
    UIImage *_fullCanvasSnapshotImage;
    long long _pauseCounter;
    _Bool _needsNotifyDelegateOfViewportChangeWhenUnpausing;
    _Bool _interacting;
    _Bool _needsRedrawAfterInteracting;
    _Bool _needsInvalidateFullSnapshotAndNotifyAfterDrawing;
    UIImpactFeedbackGenerator *_impactFeedbackGenerator;
    MTLRenderPassDescriptor *_renderPassDescriptor;
    id <MTLCommandQueue> _commandQueue;
    id <MTLLibrary> _shaderLibrary;
    id <MTLCommandBuffer> _lastCommandBuffer;
    id <MTLRenderPipelineState> _layerQuadsPipelineState;
    WAPaintBrushBasic *_basicBrush;
    WAPaintBrushDesaturate *_desaturateBrush;
    WAPaintBrushPixelate *_pixelateBrush;
    NSMutableDictionary *_stampBrushes;
    WAPaintBrushStrokeInterpolator *_currentInterpolator;
    WAPaintBrush *_brushForCurrentInterpolator;
    NSMutableArray *_strokes;
    WACachedCopyMutableArray *_textItems;
    float _fullCanvasAspectRatio;
    NSUndoManager *_undoManager;
    WAPaintCanvasDevice *_device;
    id <WAPaintCanvasDelegate> _delegate;
    long long _brushType;
    NSString *_identifier;
    CDStruct_6b9f5eac _transformInfo;
    // Error parsing type: {?="columns"[3]}, name: _canvasSpaceToCropSpaceTransform
    // Error parsing type: {?="columns"[3]}, name: _cropSpaceToCanvasSpaceTransform
}

@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
// Error parsing type for property cropSpaceToCanvasSpaceTransform:
// Property attributes: T{?=[3]},R,N,V_cropSpaceToCanvasSpaceTransform

@property(readonly, nonatomic) long long brushType; // @synthesize brushType=_brushType;
@property(nonatomic) __weak id <WAPaintCanvasDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) WAPaintCanvasDevice *device; // @synthesize device=_device;
@property(readonly, nonatomic) float fullCanvasAspectRatio; // @synthesize fullCanvasAspectRatio=_fullCanvasAspectRatio;
// Error parsing type for property canvasSpaceToCropSpaceTransform:
// Property attributes: T{?=[3]},R,N,V_canvasSpaceToCropSpaceTransform

@property(readonly, nonatomic) CDStruct_6b9f5eac transformInfo; // @synthesize transformInfo=_transformInfo;
@property(readonly, nonatomic) NSUndoManager *undoManager; // @synthesize undoManager=_undoManager;
- (void).cxx_destruct;
- (void)paintCanvasLayerNeedsRedraw:(id)arg1;
- (void)prepareEncoderForDrawingLayerQuads:(id)arg1;
- (id)renderedOverlayImageOfSize:(struct CGSize)arg1 transformInfo:(CDStruct_6b9f5eac)arg2;
- (_Bool)isTriangleVisibleP0:p1:p2: /* Error: Ran out of types for this method. */;
- (_Bool)isRectangleVisibleP0:p1:p2:p3: /* Error: Ran out of types for this method. */;
- (void)updateTextItemOrientation:(id)arg1 withItem:(id)arg2;
- (void)endTextPinch:(id)arg1;
- (void)updateTextPinch:(id)arg1 withP0:p1: /* Error: Ran out of types for this method. */;
- (id)beginTextPinchWithP0:p1: /* Error: Ran out of types for this method. */;
- (id)textItemAtP0:p1: /* Error: Ran out of types for this method. */;
- (id)textItemAtPosition: /* Error: Ran out of types for this method. */;
- (void)updateTextItem:(id)arg1 withItem:(id)arg2;
- (void)removeTextItem:(id)arg1;
- (void)addTextItem:(id)arg1;
@property(readonly, nonatomic) NSArray *textItems;
- (void)replacePaintPositionSampleAtIndex:(unsigned int)arg1 inRenderer:(id)arg2 fromSample:(id)arg3 toSample:(id)arg4;
- (_Bool)isRendererValid:(id)arg1;
- (void)endStampPinch:(id)arg1;
- (void)deleteSample:(id)arg1 atIndex:(unsigned int)arg2 renderer:(id)arg3;
- (void)updateStampPinch:(id)arg1 withP0:p1: /* Error: Ran out of types for this method. */;
- (id)beginStampPinchWithP0:p1: /* Error: Ran out of types for this method. */;
- (id)bitmapContextRendererAt: /* Error: Ran out of types for this method. */;
- (_Bool)isPinchPossibleAtP0:p1: /* Error: Ran out of types for this method. */;
- (void)endPinch:(id)arg1;
- (_Bool)updatePinchInfo:(id)arg1 withP0:p1: /* Error: Ran out of types for this method. */;
- (void)updatePinch:(id)arg1 withP0:p1: /* Error: Ran out of types for this method. */;
- (id)beginPinchWithP0:p1: /* Error: Ran out of types for this method. */;
- (_Bool)getRendererAtP0:(out id *)arg1 p1:(out unsigned int *)arg2 renderer:index: /* Error: Ran out of types for this method. */;
- (void)replaceBrushContent:(id)arg1 aspectRatio:(struct CGSize)arg2 ofRenderer:(id)arg3 completion:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) NSDictionary *metadata;
- (void)invalidateCachedTexturesForPixelEffects;
-     // Error parsing type: @128@0:8{CGSize=dd}16{?=[3]}32{?={CGSize=dd}{CGPoint=dd}d}80@120, name: snapshotImageWithSize:transformMatrix:transformInfo:overlayImage:
- (id)fullCanvasSnapshotImageWithSize:(struct CGSize)arg1;
- (void)invalidateFullSnapshotAndNotify;
- (void)setNeedsInvalidateFullSnapshotAndNotifyAfterDrawing;
- (id)imageWithTexture:(id)arg1 overlayImage:(id)arg2;
- (id)snapshotImageWithSize:(struct CGSize)arg1;
- (id)snapshotImage;
- (void)waitUntilGPUCompleted;
@property(readonly, nonatomic) _Bool hasDrawing;
@property(readonly, nonatomic) _Bool hasStickers;
@property(readonly, nonatomic) _Bool hasSignificantContent;
@property(readonly, nonatomic, getter=isEmpty) _Bool empty;
- (void)clearAll;
@property(readonly, nonatomic) unsigned long long blobCountOfCurrentStroke;
- (void)undoLastStrokeAndPrepareForRedo:(_Bool)arg1;
- (void)redoStroke:(id)arg1;
- (void)internalEndStroke;
- (_Bool)endStrokeAndDiscardIfTooShort:(_Bool)arg1;
- (void)internalMoveStrokeToPosition:(float)arg1 size:(double)arg2 angle:(double)arg3 touchForce:(_Bool)arg4 timestamp:(_Bool)arg5 snapshotPeriodically:interactive: /* Error: Ran out of types for this method. */;
- (void)moveStrokeToPosition:(double)arg1 size:(double)arg2 touchForce:timestamp: /* Error: Ran out of types for this method. */;
- (void)addPositionSampleAtPosition:(float)arg1 size:(float)arg2 angle:(CDUnknownBlockType)arg3 effectValue:color:completion: /* Error: Ran out of types for this method. */;
- (void)internalBeginStrokeWithBrush:(id)arg1 size:(float)arg2 effectValue:(float)arg3 color:(double)arg4 position:(double)arg5 angle:(_Bool)arg6 touchForce:timestamp:interactive: /* Error: Ran out of types for this method. */;
- (void)beginStrokeWithSize:(float)arg1 effectValue:(double)arg2 color:(double)arg3 position:touchForce:timestamp: /* Error: Ran out of types for this method. */;
- (_Bool)hasActiveStroke;
- (void)setPixelsPerUnit:(float)arg1;
- (float)pixelsPerUnit;
- (void)recalculateViewport;
-     // Error parsing type: v84@0:8o^{?=[3]}16o^{?=[3]}24o^{?=[3]}32{?={CGSize=dd}{CGPoint=dd}d}40f80, name: getCanvasToNormalizedDeviceCoordinatesTransformMatrix:cropSpaceToCanvasSpaceTransformMatrix:canvasSpaceToCropSpaceTransformMatrix:fromTransformInfo:fullCanvasAspectRatio:
- (void)setTransformInfo:(CDStruct_6b9f5eac)arg1 fullCanvasAspectRatio:(float)arg2;
- (id)renderPassDescriptorWithTexture:(id)arg1;
- (_Bool)renderSinceLastSnapshot:(_Bool)arg1 snapshotWhenDone:(_Bool)arg2 beforeRendering:(id)arg3;
- (void)redraw;
- (void)addStroke:(id)arg1 isRedo:(_Bool)arg2;
- (_Bool)repaint;
- (void)endPausingRedraw;
- (void)beginPausingRedraw;
- (_Bool)isRedrawPaused;
- (void)redrawIfNeeded;
- (void)setNeedsFullRedraw;
- (void)setNeedsSnapshotBeforeDrawingRenderer:(id)arg1;
- (void)setNeedsRedraw;
- (void)setNeedsUpdateViewSize;
- (id)brushWithType:(long long)arg1 content:(id)arg2;
- (void)setBrushType:(long long)arg1 brushContent:(id)arg2;
@property(readonly, nonatomic) struct CGSize brushAspectRatio;
- (id)initWithDevice:(id)arg1 identifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

