//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface WAPBReceipts : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *receiptsArray; // @dynamic receiptsArray;
@property(readonly, nonatomic) unsigned long long receiptsArray_Count; // @dynamic receiptsArray_Count;

@end

