//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, NSMutableArray, NSString, WAPBMessage;

__attribute__((visibility("hidden")))
@interface WAPBContextInfo : GPBMessage
{
}

+ (id)descriptor;
- (_Bool)isEmpty;
- (void)clearQuotedMessage;

// Remaining properties
@property(copy, nonatomic) NSData *conversionData; // @dynamic conversionData;
@property(nonatomic) unsigned int conversionDelaySeconds; // @dynamic conversionDelaySeconds;
@property(copy, nonatomic) NSString *conversionSource; // @dynamic conversionSource;
@property(nonatomic) _Bool hasConversionData; // @dynamic hasConversionData;
@property(nonatomic) _Bool hasConversionDelaySeconds; // @dynamic hasConversionDelaySeconds;
@property(nonatomic) _Bool hasConversionSource; // @dynamic hasConversionSource;
@property(nonatomic) _Bool hasIsForwarded; // @dynamic hasIsForwarded;
@property(nonatomic) _Bool hasParticipant; // @dynamic hasParticipant;
@property(nonatomic) _Bool hasQuotedMessage; // @dynamic hasQuotedMessage;
@property(nonatomic) _Bool hasRemoteJid; // @dynamic hasRemoteJid;
@property(nonatomic) _Bool hasStanzaId; // @dynamic hasStanzaId;
@property(nonatomic) _Bool isForwarded; // @dynamic isForwarded;
@property(retain, nonatomic) NSMutableArray *mentionedJidArray; // @dynamic mentionedJidArray;
@property(readonly, nonatomic) unsigned long long mentionedJidArray_Count; // @dynamic mentionedJidArray_Count;
@property(copy, nonatomic) NSString *participant; // @dynamic participant;
@property(retain, nonatomic) WAPBMessage *quotedMessage; // @dynamic quotedMessage;
@property(copy, nonatomic) NSString *remoteJid; // @dynamic remoteJid;
@property(copy, nonatomic) NSString *stanzaId; // @dynamic stanzaId;

@end

