//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, WAPBGroupInfoExtension_GroupDescription, WAPBGroupInfoExtension_Permissions;

__attribute__((visibility("hidden")))
@interface WAPBGroupInfoExtension : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int autoMuted; // @dynamic autoMuted;
@property(retain, nonatomic) WAPBGroupInfoExtension_GroupDescription *groupDescription; // @dynamic groupDescription;
@property(nonatomic) _Bool hasAutoMuted; // @dynamic hasAutoMuted;
@property(nonatomic) _Bool hasGroupDescription; // @dynamic hasGroupDescription;
@property(nonatomic) _Bool hasPermissions; // @dynamic hasPermissions;
@property(nonatomic) _Bool hasReceivedUserMessage; // @dynamic hasReceivedUserMessage;
@property(nonatomic) _Bool hasSuperadminJid; // @dynamic hasSuperadminJid;
@property(retain, nonatomic) WAPBGroupInfoExtension_Permissions *permissions; // @dynamic permissions;
@property(nonatomic) _Bool receivedUserMessage; // @dynamic receivedUserMessage;
@property(copy, nonatomic) NSString *superadminJid; // @dynamic superadminJid;

@end

