//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

__attribute__((visibility("hidden")))
@interface WAPendingPrekeyTask : NSObject
{
    NSMutableSet *_pendingJids;
    CDUnknownBlockType _completion;
}

@property(readonly, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) NSMutableSet *pendingJids; // @synthesize pendingJids=_pendingJids;
- (void).cxx_destruct;
- (void)finishedWaitingForJid:(id)arg1;
@property(readonly, nonatomic) _Bool finished;
- (id)initWithPendingJids:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

