//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL, WAStorage;

__attribute__((visibility("hidden")))
@interface WAPersistentKeyValueStore : NSObject
{
    WAStorage *_storage;
}

- (void).cxx_destruct;
- (_Bool)_insertKeysAndValues:(id)arg1 forKeyNamespace:(id)arg2 error:(out id *)arg3;
- (id)_fetchKeysAndValuesWithRequest:(id)arg1 capacity:(unsigned long long)arg2 hasMore:(_Bool *)arg3 error:(id *)arg4;
- (_Bool)clearElementsBeforeDate:(id)arg1 inNamespace:(id)arg2 maxCount:(unsigned long long)arg3 error:(id *)arg4 confirmBlock:(CDUnknownBlockType)arg5;
- (_Bool)clearElementsInNamespace:(id)arg1 maxCount:(unsigned long long)arg2 error:(id *)arg3 confirmBlock:(CDUnknownBlockType)arg4;
- (_Bool)clearElementsForKeys:(id)arg1 inNamespace:(id)arg2 error:(id *)arg3;
- (_Bool)setKeysAndValues:(id)arg1 inNamespace:(id)arg2 error:(id *)arg3;
- (_Bool)setValue:(id)arg1 forKey:(id)arg2 inNamespace:(id)arg3 error:(id *)arg4;
- (id)fetchSomeRecentNonEmptyKeysAndValuesWithCursor:(id)arg1 error:(id *)arg2;
- (id)fetchSomeNonEmptyKeysAndValuesInNamespace:(id)arg1 maxCount:(unsigned long long)arg2 hasMore:(_Bool *)arg3 error:(id *)arg4;
- (id)fetchAllNonEmptyKeysAndValuesInNamespace:(id)arg1 error:(id *)arg2;
- (id)fetchValuesForKeys:(id)arg1 inNamespace:(id)arg2 error:(id *)arg3;
- (id)fetchValueForKey:(id)arg1 inNamespace:(id)arg2 error:(id *)arg3;
@property(readonly, nonatomic) NSURL *fileURL;
- (id)initWithFileURL:(id)arg1 blacklistBackup:(_Bool)arg2;
- (id)initWithFileURL:(id)arg1;

@end

