//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;
@protocol WADeviceDate;

__attribute__((visibility("hidden")))
@interface WAPrewarmedHostEntry : NSObject
{
    NSDate<WADeviceDate> *_creationDate;
    _Bool _isFB;
    NSString *_host;
}

@property(readonly, nonatomic) _Bool isFB; // @synthesize isFB=_isFB;
@property(readonly, nonatomic) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool expired;
- (id)initWithHost:(id)arg1 isFB:(_Bool)arg2;

@end

