//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WAPushController;

@protocol WAPushControllerDelegate <NSObject>
- (_Bool)pushControllerShouldDeferCompletionHandler:(WAPushController *)arg1;
- (void)pushController:(WAPushController *)arg1 didReceiveScheduledPushWithID:(NSString *)arg2;
- (void)pushController:(WAPushController *)arg1 didReceiveVisiblePushForChatFromJID:(NSString *)arg2;
- (void)pushController:(WAPushController *)arg1 didReceiveCallWithID:(NSString *)arg2;
- (void)pushController:(WAPushController *)arg1 didReceiveMissedCallWithID:(NSString *)arg2;
- (void)pushControllerReloadUserNotificationSettings:(WAPushController *)arg1;
- (void)pushControllerWillRegisterForAPNSToken:(WAPushController *)arg1;
- (_Bool)pushControllerShouldProcessRemoteNotification:(WAPushController *)arg1;
- (void)pushControllerDidWakeForVOIPPush:(WAPushController *)arg1;
@end

