//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface WARegistrationURLBuilder : NSObject
{
    NSString *_phoneNumber;
    _Bool _encryptQueryParams;
    NSURL *_proxyURL;
    NSArray *_baseParams;
}

+ (id)registrationDomainProbeURL;
+ (id)twoFactorAuthenticationURL;
+ (id)sameDeviceCheckURL;
+ (id)codeRequestURL;
+ (id)registrationURL;
+ (id)registrationURLWithBaseURLString:(id)arg1 params:(id)arg2 encryptWithProxyURL:(id)arg3;
- (void).cxx_destruct;
- (id)twoFactorResetWithWipeTokenRequestURL:(id)arg1;
- (id)twoFactorResetViaEmailRequestURL;
- (id)twoFactorVerifyRequestURLWithCode:(id)arg1;
- (id)registrationRequestURLWithVerificationCode:(id)arg1 entryMethod:(int)arg2;
- (id)verificationCodeRequestURLWithMethod:(id)arg1 mcc:(id)arg2 mnc:(id)arg3 jailbroken:(_Bool)arg4;
- (id)sameDeviceCheckRequestURL;
- (void)disableProxying;
- (void)enableProxyingWithProxyURL:(id)arg1;
- (id)initWithCountryCode:(id)arg1 phoneNumber:(id)arg2 language:(id)arg3 locale:(id)arg4 recoveryToken:(id)arg5 chatPrivateKey:(id)arg6 e2eKeyBundle:(id)arg7;

@end

