//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableAttributedString, WACachedCopyMutableArray;

__attribute__((visibility("hidden")))
@interface WARichText : NSObject
{
    NSMutableAttributedString *_attributedString;
    WACachedCopyMutableArray *_mentions;
}

+ (id)detectMentionsInAttributedText:(id)arg1;
+ (void)updateMentionAttributesInText:(id)arg1 nameAttributes:(id)arg2 atAttributes:(id)arg3;
+ (id)attributedText:(id)arg1 withMentions:(id)arg2 chatsStorage:(id)arg3;
+ (id)attributedText:(id)arg1 withMentions:(id)arg2;
+ (id)mentionStringForName:(id)arg1 jid:(id)arg2;
- (void).cxx_destruct;
- (void)resetStringAttributesToDefaults;
- (_Bool)isLocationInsideOfMention:(unsigned long long)arg1;
- (void)invalidateMention:(id)arg1;
- (void)trackMentions:(id)arg1;
- (id)trackMentionAtRange:(struct _NSRange)arg1 jid:(id)arg2;
@property(readonly, copy, nonatomic) NSArray *mentions;
- (id)mentionsForMessaging;
- (_Bool)containsMentions;
- (id)textForMessaging;
- (void)removeAttribute:(id)arg1 range:(struct _NSRange)arg2;
- (void)addAttribute:(id)arg1 value:(id)arg2 range:(struct _NSRange)arg3;
- (void)setAttributes:(id)arg1 range:(struct _NSRange)arg2;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;
- (id)attributesAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (id)string;
- (id)attributedString;
- (unsigned long long)length;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithAttributedString:(id)arg1;
- (id)initWithString:(id)arg1;
- (id)init;

@end

