//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSString, UIImage, UIImageView, WAButtonLabel;
@protocol WARoundButtonDelegate;

__attribute__((visibility("hidden")))
@interface WARoundButton : UIButton
{
    WAButtonLabel *_bottomLabel;
    UIImageView *_mask;
    UIImageView *_whiteImageView;
    UIImageView *_blackImageView;
    UIImageView *_blurredImageView;
    _Bool _pressed;
    _Bool _selectable;
    int _theme;
    UIImage *_iconImage;
    id <WARoundButtonDelegate> _delegate;
}

+ (id)button;
@property(nonatomic) int theme; // @synthesize theme=_theme;
@property(nonatomic) __weak id <WARoundButtonDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isSelectable) _Bool selectable; // @synthesize selectable=_selectable;
@property(retain, nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
- (void).cxx_destruct;
- (void)sendAction:(SEL)arg1 to:(id)arg2 forEvent:(id)arg3;
- (void)setEnabled:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)updateButtonState;
- (void)setPressed:(_Bool)arg1;
@property(nonatomic) _Bool bottomLabelHidden;
@property(copy, nonatomic) NSString *bottomLabelText;
- (void)updateBlurredImageIfNeeded;
- (void)setCenter:(struct CGPoint)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

