//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WASMBAutomaticMessageManagerDelegate-Protocol.h"

@class NSDate, NSString, WAPersistentKeyValueStore, WASMBAutomaticMessageManager, WASMBAwayMessageConfig, WASMBGreetingMessageConfig;

__attribute__((visibility("hidden")))
@interface WASMBManager : NSObject <WASMBAutomaticMessageManagerDelegate>
{
    WAPersistentKeyValueStore *_localKeyValueStore;
    WAPersistentKeyValueStore *_backedUpKeyValueStore;
    WASMBAutomaticMessageManager *_automaticMessageManager;
}

- (void).cxx_destruct;
- (void)clearAwayMessageRecordIfNeededForAutomaticMessageManager:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)hasAwayMessageSentForAutomaticMessageManager:(id)arg1 forJid:(id)arg2;
- (void)recordAwayMessageSentForAutomaticMessageManager:(id)arg1 forJid:(id)arg2;
- (id)awayMessageConfigForAutomaticMessageManager:(id)arg1;
- (id)greetingMessageConfigForAutomaticMessageManager:(id)arg1;
- (void)recomputeNextAwayMessageRecordClearTime;
- (void)clearAwayMessageRecordTableWithCompletion:(CDUnknownBlockType)arg1;
- (id)readSMBConfigDataForKey:(id)arg1 inNamespace:(id)arg2 fromKeyValueStore:(id)arg3;
- (void)saveSMBConfig:(id)arg1 forKey:(id)arg2 inNamespace:(id)arg3 fromKeyValueStore:(id)arg4;
@property(retain, nonatomic) NSDate *awayMessageRecordClearTime;
@property(retain, nonatomic) WASMBAwayMessageConfig *awayMessageConfig;
@property(retain, nonatomic) WASMBGreetingMessageConfig *greetingMessageConfig;
- (id)initWithLocalKeyValueStore:(id)arg1 backedUpKeyValueStore:(id)arg2 nameDirectory:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

