//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WATask.h"

__attribute__((visibility("hidden")))
@interface WASpotlightBlockTask : WATask
{
    CDUnknownBlockType _block;
}

- (void).cxx_destruct;
- (void)runTaskFromQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithDomainPrefix:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)initWithDescription:(id)arg1;

@end

