//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAGIFBatchToken.h"

__attribute__((visibility("hidden")))
@interface WAStarredBatchToken : WAGIFBatchToken
{
    long long _offset;
}

+ (id)firstBatch;
@property(readonly, nonatomic) long long offset; // @synthesize offset=_offset;
- (_Bool)isFirstBatch;
- (id)stringValue;
- (id)initWithOffset:(long long)arg1;

@end

