//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSNumber, NSString, NSURL, WAMessage;

__attribute__((visibility("hidden")))
@interface WAStreamingMediaLoaderMessageInfo : NSObject
{
    _Bool _canPrefetch;
    _Bool _canUseCellularToPrefetch;
    _Bool _canUseCellularToAutoDownload;
    _Bool _verifiedFileSize;
    int _messageType;
    int _mediaOrigin;
    int _fileSize;
    WAMessage *_message;
    NSString *_chatJID;
    NSString *_uniqueKey;
    NSString *_directPath;
    double _wamMediaType;
    NSString *_contentType;
    NSString *_mediaURL;
    NSURL *_assetURL;
    NSData *_mediaKey;
    NSString *_fileHash;
    NSString *_encFileHash;
    NSData *_sidecar;
    NSNumber *_playbackCount;
}

+ (id)infoForMessage:(id)arg1;
@property(retain, nonatomic) NSNumber *playbackCount; // @synthesize playbackCount=_playbackCount;
@property(nonatomic) _Bool verifiedFileSize; // @synthesize verifiedFileSize=_verifiedFileSize;
@property(readonly, nonatomic) _Bool canUseCellularToAutoDownload; // @synthesize canUseCellularToAutoDownload=_canUseCellularToAutoDownload;
@property(readonly, nonatomic) _Bool canUseCellularToPrefetch; // @synthesize canUseCellularToPrefetch=_canUseCellularToPrefetch;
@property(readonly, nonatomic) _Bool canPrefetch; // @synthesize canPrefetch=_canPrefetch;
@property(readonly, copy, nonatomic) NSData *sidecar; // @synthesize sidecar=_sidecar;
@property(readonly, copy, nonatomic) NSString *encFileHash; // @synthesize encFileHash=_encFileHash;
@property(readonly, copy, nonatomic) NSString *fileHash; // @synthesize fileHash=_fileHash;
@property(readonly, copy, nonatomic) NSData *mediaKey; // @synthesize mediaKey=_mediaKey;
@property(readonly, copy, nonatomic) NSURL *assetURL; // @synthesize assetURL=_assetURL;
@property(readonly, copy, nonatomic) NSString *mediaURL; // @synthesize mediaURL=_mediaURL;
@property(readonly, copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(nonatomic) int fileSize; // @synthesize fileSize=_fileSize;
@property(readonly, nonatomic) double wamMediaType; // @synthesize wamMediaType=_wamMediaType;
@property(readonly, nonatomic) int mediaOrigin; // @synthesize mediaOrigin=_mediaOrigin;
@property(readonly, nonatomic) int messageType; // @synthesize messageType=_messageType;
@property(readonly, copy, nonatomic) NSString *directPath; // @synthesize directPath=_directPath;
@property(readonly, copy, nonatomic) NSString *uniqueKey; // @synthesize uniqueKey=_uniqueKey;
@property(readonly, copy, nonatomic) NSString *chatJID; // @synthesize chatJID=_chatJID;
@property(readonly, nonatomic) WAMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (id)initWithMessage:(id)arg1;

@end

