//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, WAProfilePictureThumbnailView;

__attribute__((visibility("hidden")))
@interface WAStatusProfilePictureThumbnailView : UIView
{
    UIImageView *_plusIconView;
    WAProfilePictureThumbnailView *_thumbnailView;
}

@property(readonly, nonatomic) WAProfilePictureThumbnailView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

