//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAStickerDownloadInfoProviding-Protocol.h"

@class NSArray, NSData, NSString;

__attribute__((visibility("hidden")))
@interface WASticker : NSObject <WAStickerDownloadInfoProviding>
{
    NSString *_stickerPackId;
    NSString *_imageFilePath;
    NSString *_url;
    NSString *_fileHash;
    NSString *_encFileHash;
    long long _fileLength;
    NSData *_mediaKey;
    NSString *_mimeType;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, copy, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(readonly, copy, nonatomic) NSData *mediaKey; // @synthesize mediaKey=_mediaKey;
@property(readonly, nonatomic) long long fileLength; // @synthesize fileLength=_fileLength;
@property(readonly, copy, nonatomic) NSString *encFileHash; // @synthesize encFileHash=_encFileHash;
@property(readonly, copy, nonatomic) NSString *fileHash; // @synthesize fileHash=_fileHash;
@property(readonly, copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(readonly, copy, nonatomic) NSString *imageFilePath; // @synthesize imageFilePath=_imageFilePath;
@property(readonly, copy, nonatomic) NSString *stickerPackId; // @synthesize stickerPackId=_stickerPackId;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) NSArray *emojis;
- (id)copyWithImageFilePath:(id)arg1;
- (id)initWithMessage:(id)arg1;
- (id)initWithStickerPackId:(id)arg1 imageFilePath:(id)arg2 url:(id)arg3 fileHash:(id)arg4 encFileHash:(id)arg5 fileLength:(long long)arg6 mediaKey:(id)arg7 mimeType:(id)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

