//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSSet, NSString, WASyncedContactList;

@protocol WASyncedContactListProviding <NSObject>
@property(nonatomic) _Bool listInSync;
- (void)syncedContactListDidUpdate:(WASyncedContactList *)arg1;
- (void)fetchJIDsForSyncedContactList:(WASyncedContactList *)arg1 completion:(void (^)(NSError *, NSArray *))arg2;
- (void)syncedContactList:(WASyncedContactList *)arg1 didRequestSendJIDs:(NSSet *)arg2 webClientRequestID:(NSString *)arg3 completion:(void (^)(NSError *))arg4;
- (void)permanentlySaveJIDs:(NSArray *)arg1 forSyncedContactList:(WASyncedContactList *)arg2;
- (NSString *)pathToPendingContactsStoreForSyncedContactList:(WASyncedContactList *)arg1;
- (NSArray *)permanentlySavedJIDsForSyncedContactList:(WASyncedContactList *)arg1;
@end

