//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, WATaskManager;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WATaskQueue : NSObject
{
    NSMutableArray *_tasks;
    long long _currentTaskIndex;
    unsigned long long _disableModes;
    _Bool _lowPower;
    unsigned long long _readyCount;
    double _minimumInterval;
    double _lowPowerMultiplier;
    WATaskManager *_manager;
    NSObject<OS_dispatch_queue> *_targetQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *targetQueue; // @synthesize targetQueue=_targetQueue;
@property(nonatomic) __weak WATaskManager *manager; // @synthesize manager=_manager;
@property(nonatomic) double lowPowerMultiplier; // @synthesize lowPowerMultiplier=_lowPowerMultiplier;
@property(nonatomic) double minimumInterval; // @synthesize minimumInterval=_minimumInterval;
- (void).cxx_destruct;
- (void)runTaskInGroup:(id)arg1;
- (id)findNextTask;
- (void)resume;
- (void)pause;
@property(readonly, nonatomic) _Bool readyToRun;
- (void)cancelTaskAtIndex:(long long)arg1;
- (void)cancelTask:(id)arg1;
- (_Bool)isTaskScheduled:(id)arg1;
- (void)scheduleTask:(id)arg1;
- (void)didLeaveMode:(unsigned long long)arg1;
- (void)didEnterMode:(unsigned long long)arg1;
- (id)initWithDisabledModes:(unsigned long long)arg1;
- (id)init;

@end

