//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WATextAttachmentLoader : NSObject
{
    NSMutableArray *_registeredSizes;
    NSDictionary *_symbolDict;
    NSMutableDictionary *_scaledSizeToFilenameSuffixDict;
    NSArray *_symbolArray;
}

+ (id)skinToneModifierSet;
+ (id)customEmojiSet;
+ (id)regionalPairSet;
+ (id)sharedLoader;
@property(copy, nonatomic) NSArray *symbolArray; // @synthesize symbolArray=_symbolArray;
- (void).cxx_destruct;
- (id)bestImageForName:(id)arg1 pointSize:(double)arg2;
- (id)bestRegisteredSizeForPointSize:(double)arg1;
- (id)textAttachmentForName:(id)arg1 pointSize:(double)arg2;
- (void)registerSize:(long long)arg1;
- (id)init;

@end

