//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/MKAnnotationView.h>

@class UIImageView;

__attribute__((visibility("hidden")))
@interface WAUserLocationAnnotationView : MKAnnotationView
{
    UIImageView *_imageView;
    UIImageView *_dotImageView;
}

- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setAnnotation:(id)arg1;

@end

