//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAVCardSerializing-Protocol.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface WAVCardSharingGroup : NSObject <WAVCardSerializing>
{
    _Bool _sharingEnabled;
    NSArray *_sharingUnits;
}

+ (id)optionalSharingGroupsForContact:(id)arg1;
+ (id)vCardStringWithVCardSerializingObjects:(id)arg1;
@property(copy, nonatomic) NSArray *sharingUnits; // @synthesize sharingUnits=_sharingUnits;
@property(nonatomic) _Bool sharingEnabled; // @synthesize sharingEnabled=_sharingEnabled;
- (void).cxx_destruct;
- (void)addRepeatedSharingUnitWithClass:(Class)arg1 forContact:(id)arg2;
- (void)addSharingUnitsWithClasses:(id)arg1 forContact:(id)arg2;
- (_Bool)isEmpty;
@property(readonly, copy, nonatomic) NSString *stringForVCard;
- (id)initWithContact:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

