//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAsset, AVAssetExportSession, AVAssetReader, AVAssetReaderOutput, AVAssetReaderTrackOutput, AVAssetWriter, AVAssetWriterInput, AVVideoComposition, NSError, NSURL, WAVideoTranscoderDescriptor;
@protocol OS_dispatch_group, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WAVideoTranscoder : NSObject
{
    NSObject<OS_dispatch_queue> *_exportQueue;
    NSObject<OS_dispatch_group> *_exportDispatchGroup;
    CDUnknownBlockType _completionHandler;
    float _progress;
    unsigned long long _bgTask;
    WAVideoTranscoderDescriptor *_descriptor;
    _Bool _cancelExportRequested;
    AVAsset *_asset;
    AVVideoComposition *_videoComposition;
    AVAssetReader *_assetReader;
    AVAssetReaderOutput *_videoOutput;
    AVAssetReaderTrackOutput *_audioOutput;
    AVAssetWriter *_assetWriter;
    AVAssetWriterInput *_videoInput;
    AVAssetWriterInput *_audioInput;
    AVAssetExportSession *_passThroughExportSession;
    long long _status;
    NSError *_error;
    double _exportedDuration;
}

+ (id)genericUnusableVideoError;
+ (id)errorWithCode:(long long)arg1 reason:(id)arg2;
+ (void)prepareAssetForTranscoderOperations:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)transcodeToMpeg4IfNeededForVideoAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) double exportedDuration; // @synthesize exportedDuration=_exportedDuration;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (void)finishUp;
- (void)tagAsGIFIfNeeded;
- (void)reallyPerformPassThroughExport;
- (void)transcoderDidFinishExportingWithCancellation:(_Bool)arg1;
- (void)finishExporting;
- (void)writeSamplesStartingAtTime:(CDStruct_1b6d18a9)arg1;
- (void)reallyPerformExportWithTimeRange:(CDStruct_e83c9415)arg1;
- (void)passThroughExportForVideoOnlyNonTrimmedMedia;
- (void)passThroughExportWithTimeRange:(CDStruct_e83c9415)arg1;
- (void)performExportWithTimeRange:(CDStruct_e83c9415)arg1 mediaFileInfoHint:(id)arg2;
- (void)abortWithError:(id)arg1;
- (struct CGSize)transcodedSizeFromNaturalSize:(struct CGSize)arg1;
- (_Bool)isVideoEligibleForPassThrough;
@property(readonly, nonatomic) float progress;
- (void)cancelExport;
- (void)exportAsynchronouslyWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)mediaInfoHint;
@property(readonly, copy, nonatomic) NSURL *outputURL;
- (id)videoCompositionFromVideoComposition:(id)arg1 byCompositingImage:(id)arg2;
- (id)initWithAsset:(id)arg1 videoComposition:(id)arg2 descriptor:(id)arg3;

@end

