//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface WebVideoContainerView : UIView
{
    // Error parsing type: , name: webURL
    // Error parsing type: , name: delegate
    // Error parsing type: , name: status
    // Error parsing type: , name: aspectRatioHint
    // Error parsing type: , name: playerView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

