//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMPPStanzaElement.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface XMPPPayStanzaElement : XMPPStanzaElement
{
}

+ (unsigned long long)typeForString:(id)arg1;
+ (id)stringForType:(unsigned long long)arg1;
+ (id)stringsForTypes;
@property(readonly, copy, nonatomic) NSString *receiverJID;
@property(readonly, copy, nonatomic) NSString *currency;
@property(readonly, nonatomic) long long amount_1000;
- (_Bool)hasAmount;
@property(readonly, nonatomic) unsigned long long type;
- (id)initWithType:(unsigned long long)arg1 amount:(float)arg2 currency:(id)arg3 credentialId:(id)arg4 receiverJID:(id)arg5 receiverHandle:(id)arg6 deviceId:(id)arg7 mpin:(id)arg8 transactionId:(id)arg9;

@end

