//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMPPStanza.h"

__attribute__((visibility("hidden")))
@interface XMPPChatStateStanza : XMPPStanza
{
}

+ (id)stringForChatState:(unsigned long long)arg1;
+ (id)chatStateStrings;
- (id)log;
@property(nonatomic) unsigned long long state;
- (id)initWithState:(unsigned long long)arg1;

@end

