//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface XMPPWebClientLoginInfo : NSObject
{
    _Bool _temporary;
    NSString *_operatingSystem;
    NSString *_browser;
}

@property(readonly, nonatomic, getter=isTemporary) _Bool temporary; // @synthesize temporary=_temporary;
@property(readonly, copy, nonatomic) NSString *browser; // @synthesize browser=_browser;
@property(readonly, copy, nonatomic) NSString *operatingSystem; // @synthesize operatingSystem=_operatingSystem;
- (void).cxx_destruct;
- (id)initWithResponse:(id)arg1;

@end

