//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMPPStanza.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface XMPPMessageStanza : XMPPStanza
{
    NSDate *_timeOfArrival;
}

+ (id)ciphertextTypeForString:(id)arg1;
+ (id)stringForCiphertextType:(unsigned long long)arg1;
+ (void)xmppMessageType:(out unsigned long long *)arg1 xmppMediaType:(out unsigned long long *)arg2 fromWAMessageType:(int)arg3 mediaOrigin:(int)arg4 multiVCard:(_Bool)arg5 payment:(_Bool)arg6;
+ (id)stringForMediaType:(unsigned long long)arg1;
+ (id)encNodeForCiphertextPayload:(id)arg1 withMediaType:(unsigned long long)arg2 retryCount:(unsigned long long)arg3 locationSharingEndDate:(id)arg4;
+ (id)outgoingMessageStanzaToJid:(id)arg1 messageId:(id)arg2 participant:(id)arg3 messageType:(int)arg4 mediaOrigin:(int)arg5 phash:(id)arg6 retryCount:(unsigned long long)arg7 multicast:(_Bool)arg8 multiVCard:(_Bool)arg9 payment:(_Bool)arg10 textFromURL:(_Bool)arg11 numberFromURL:(_Bool)arg12 locationSharingEndDate:(id)arg13 broadcastListName:(id)arg14 broadcastListParticipants:(id)arg15 withFanoutCiphertextPayload:(id)arg16 commonCiphertextPayload:(id)arg17;
+ (id)outgoingMessageStanzaForWAMessage:(id)arg1 withParticipant:(id)arg2 retryCount:(unsigned long long)arg3 qCount:(unsigned long long)arg4 withFanoutCiphertextPayload:(id)arg5 commonCiphertextPayload:(id)arg6;
+ (id)outgoingMessageStanzaForSharedItem:(id)arg1 withFanoutCiphertextPayload:(id)arg2 commonCiphertextPayload:(id)arg3;
+ (unsigned long long)typeForString:(id)arg1;
+ (id)stringForType:(unsigned long long)arg1;
+ (id)stringsForTypes;
@property(retain, nonatomic) NSDate *timeOfArrival; // @synthesize timeOfArrival=_timeOfArrival;
- (void).cxx_destruct;
- (id)log;
- (id)vcard;
- (id)body;
- (id)media;
- (void)setMediaOrigin:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long mediaOrigin;
@property(nonatomic) unsigned long long type;
- (void)setMulticast:(_Bool)arg1;
@property(readonly, nonatomic) _Bool multicast;
@property(readonly, copy, nonatomic) NSString *uniqueKey;
@property(readonly, nonatomic) _Bool broadcast;
- (id)initWithFromJID:(id)arg1 toJID:(id)arg2 type:(unsigned long long)arg3;

@end

