//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMPPStanzaElement.h"

@class NSArray, NSDate, NSDictionary, NSError, NSString;
@protocol WAServerDate;

__attribute__((visibility("hidden")))
@interface XMPPStanza : XMPPStanzaElement
{
    NSDictionary *_connectionInfo;
}

+ (id)generateSID;
+ (id)generateUniqueIdentifier;
+ (id)generateCallIdentifier;
+ (id)generateUniqueMessageIdentifier;
+ (id)prefixForMessageIdentifier;
+ (int)voipStanzaTypeFromString:(id)arg1;
@property(copy, nonatomic) NSDictionary *connectionInfo; // @synthesize connectionInfo=_connectionInfo;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isReceivedWithActiveWebClientSession) _Bool receivedWithActiveWebClientSession;
@property(readonly, nonatomic) int offlineCount;
@property(readonly, nonatomic) _Bool offline;
@property(readonly, nonatomic) NSError *error;
@property(readonly, nonatomic) NSString *errorCode;
@property(readonly, nonatomic) NSDate<WAServerDate> *timestamp;
@property(copy, nonatomic) NSString *participant;
@property(copy, nonatomic) NSString *fromJID;
@property(copy, nonatomic) NSString *toJID;
@property(copy, nonatomic) NSString *uniqueIdentifier;
- (id)initWithName:(id)arg1 fromJID:(id)arg2 toJID:(id)arg3;
- (void)performSanityCheckIncludingDuration:(_Bool)arg1;
- (void)fillCommonVoipHeader:(CDStruct_b067a95f *)arg1;
@property(readonly, nonatomic) int callRekeyRetryCount;
@property(readonly, nonatomic) int callOfferRetryCount;
@property(readonly, nonatomic, getter=isGroupCall) _Bool groupCall;
@property(readonly, nonatomic, getter=isVideoCall) _Bool videoCall;
@property(readonly, nonatomic) NSArray *callPeerParticipants;
- (id)messageId;
- (id)callId;
@property(readonly, nonatomic) int voipInnerType;
@property(readonly, nonatomic) NSString *callCreatorJid;
@property(readonly, nonatomic) int callWakeupSource;
- (id)voipAckStanzaWithType:(id)arg1;

@end

